Makefile, src/cmd/moby/build.go
Hey, 
this is currently what happen when I type `make` on the master branch.
```
tar cf - vendor src/initrd src/pad4 -C src/cmd/moby . | docker run --rm --net=none --log-driver=none -i -e GOOS=darwin -e GOARCH=amd64 linuxkit/go-compile:4513068d9a7e919e4ec42e2d7ee879ff5b95b7f5@sha256:bdfadbe3e4ec699ca45b67453662321ec270f2d1a1dbdbf09625776d3ebd68c5 --package github.com/docker/moby --ldflags "-X main.GitCommit=d422c70ac6da78da3d32237735d86eb9001df384 -X main.Version="0.0" " -o bin/moby > tmp_moby_bin.tar
gofmt...
govet...
golint...
ineffassign...
go build...
src/initrd/initrd.go:10:2: cannot find package "github.com/linuxkit/linuxkit/src/pad4" in any of:
/go/src/github.com/docker/moby/vendor/github.com/linuxkit/linuxkit/src/pad4 (vendor tree) …
```
=> Rename old repo to linuxkit/linuxkit to let the build work

projects/miragesdk/roadmap.md
Signed-off-by: Mindy Preston <mindy.preston@docker.com>
Fixed typos
Used keyboard
```
4.04.0+afl🐫  (copyedit) mirageos:~/linuxkit/projects/miragesdk$ echo "deamon" | aspell list
deamon
4.04.0+afl🐫  (copyedit) mirageos:~/linuxkit/projects/miragesdk$ echo "daemon" | aspell list
4.04.0+afl🐫  (copyedit) mirageos:~/linuxkit/projects/miragesdk$ 
```
The second change requires a speaker of English conversant in tense agreement.
This change does not need to be included in the changelog.  If inclusion is necessary, "fix typos in miragesdk roadmap" is sufficient.
```
,,,=^.^=,,,~~~
```
=> typo fixes

projects/kubernetes/README.md, projects/kubernetes/ssh_into_kubelet.sh
The Kubernetes images have been migrated to Alpine Linux which
does not include bash by default.
Signed-off-by: Matt Bajor <matt@notevenremotelydorky.com>
Updated the ssh_into_kubelet.sh shell script to use ash shell
Run through the Kubernetes project [README](projects/kubernetes/README.md) (specifically running `ssh_into_kubelet.sh`)
Use ash when sshing to Kubernetes
=> Migrate the Kubernetes shell to ash

src/cmd/moby/run_vmware.go
I've added in the capability to look for the `vmdk` from the use of the prefix
Duplicated the same functionality from `qemu` and `hypervisor`
`./moby run vmware vmware`
Modified the default behaviour of the `qemu` plugin to match  expected <prefix> behaviour.
=> Fix for prefix for linuxkit

linuxkit.yml
Update the top-level `linuxkit.yml` example assembly with the `linuxkit` hub repo images, following conversation from: https://github.com/linuxkit/linuxkit/pull/1673#discussion_r112793578
Tested with a successful `moby build`/`moby run` locally.
=> Update top-level linuxkit.yml with images from linuxkit org

Makefile, src/cmd/moby/run_gcp.go
This PR introduces two changes required to add LTP tests to CI
- Adds a -skip-cleanup flag to moby run gcp to allow CI to perform cleanup
- Adds a make test-ltp target to the Makefile and adds this to the ci targets used for master and tags
LTP tests take 18-20 minutes to complete
Closes: #1230
=> Changes required to run LTP tests in CI

Makefile, docs/gcp.md, examples/gcp.yml, src/cmd/moby/config.go, src/cmd/moby/main.go, src/cmd/moby/output.go, src/cmd/moby/push.go, src/cmd/moby/push_gcp.go, src/cmd/moby/run_gcp.go, src/cmd/moby/schema.go
This currently only changes the `gcp` target, but is the new
model - the `build` command will only do things locally, then
you need to `push` to an image store such as GCP or other ones
in order to `run` for platforms that cannot boot directly from
a local image.
Fix #1618
cc @dave-tucker
=> Split build and push, and remove push code from run

README.md, docs/gcp.md
* removed incomplete command from README.md; it does not work without specifying GCP project and bucket
* `moby <push|run>` -> `linuxkit ...`
* `myfile` -> `myprefix`, because there is no file named `myfile`
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
=> update gcp docs

src/cmd/linuxkit/run.go
Signed-off-by: Carlton-Semple <carlton.semple@ibm.com>
I changed the `linuxkit run --help` text to say `See 'linuxkit run [backend] --help' for details.` rather than `See 'moby run [backend] --help' for details.`
=> Fix for old moby reference in linuxkit CLI

projects/kubernetes/boot-master.sh, projects/kubernetes/boot-node.sh
Fixes #1711
Signed-off-by: Tiago Pires <tandrepires@gmail.com>
Updated the `boot-master` and `boot-node` scripts.
Fixed kubernetes boot scripts.
=> Use linuxkit on boot scripts instead of moby

examples/docker.yml, examples/gcp.yml, examples/packet.yml, examples/sshd.yml, examples/vmware.yml, linuxkit.yml, pkg/ca-certificates/Dockerfile, pkg/ca-certificates/Makefile, projects/etcd/etcd.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/okernel/examples/okernel_simple.yaml, test/docker-bench/test-docker-bench.yml, test/ltp/test-ltp.yml, test/test.yml, test/virtsock/test-virtsock-server.yml
We were using Debian but Alpine more consistent. Use nested build.
Currently extract the hash in a nasty way but this can be fixed later
when we switch over hashing method.
=> Update ca-certificates to be based on Alpine and use nested build

examples/swap.yml, pkg/swap/Dockerfile, pkg/swap/Makefile, pkg/swap/README.md, pkg/swap/swap.sh
Add support for creating swap files in linuxkit image
add onboot image `linuxkit/swap`, which contains script to read params and set up swapfile
Run with various options:
* no `--path` provided
* invalid swapfile
* no mounted disk (cannot use in `/var` because it is tmpfs
* disk too small
* check conditions
Add image with support for swapfiles to be used in onboot
** Notes **
1. I used the Makefile from [pkg/mount](https://github.com/linuxkit/linuxkit/tree/master/pkg/mount) as a template. I was unsure the level of adherence to the shahash versioning scheme, but figured something that already is in and is similar is a good start.
2. …
=> First cut of swap image and example

Makefile
Signed-off-by: Lorenzo Fontana <lo@linux.com>
Just fixed the platform for `test-hyperkit` and `test-qemu-efi` so that they work only under the right circumstances 
**qemu**
```
make test-qemu-efi
```
Now only runs using qemu and not the default platform.
**hyperkit**
```bash
make test-hyperkit
```
Now runs only on applicable platforms (Mac)
```zsh
➜  linuxkit git:(fix/makefile-test-targets) make test-hyperkit
rm -f disk.img
bin/linuxkit run hyperkit test | tee test.log
FATA[0000] Error creating hyperkit:  Could not find hyperkit executable 
Makefile:55: recipe for target 'test-hyperkit' failed
make: *** [test-hyperkit] Error 1
```
=> Specified platform for hyperkit and qemu

examples/minimal.yml, examples/node_exporter.yml, linuxkit.yml, pkg/init/etc/init.d/rcS, projects/etcd/etcd.yml, projects/logging/pkg/init/etc/init.d/rcS, projects/miragesdk/pkg/init/etc/init.d/rcS, projects/selinux/init/etc/init.d/rcS, projects/wireguard/init-wireguard/etc/init.d/rcS
Not sure when this arrived but it was stopping anything running.
Appears not to be in the older test `init` containers.
=> Fix typo "ndodev"

Makefile, examples/docker.yml, examples/gcp.yml, examples/node_exporter.yml, examples/packet.yml, examples/sshd.yml, examples/vmware.yml, linuxkit.yml, pkg/binfmt/Makefile, pkg/init/Makefile, pkg/rngd/Makefile, test/docker-bench/test-docker-bench.yml, test/virtsock/test-virtsock-server.yml, tools/c-compile/Makefile, tools/go-compile/Makefile, tools/tini/Makefile, tools/toybox-media/Makefile
Set up notary delegations and Makefile `sign` targets for:
```
docker.io/linuxkit/binfmt
docker.io/linuxkit/rngd
docker.io/linuxkit/go-compile
docker.io/linuxkit/c-compile
docker.io/linuxkit/toybox-media
docker.io/linuxkit/tini
```
Also updated yml files and Makefiles to verify signatures where appropriate.
=> Signing targets for binfmt, rngd, compilers, toybox, tini

src/cmd/linuxkit/run_qemu.go
To use `-drive` as an analog for `-hda` or `-hdb`, etc. the qemu
docs note that "media" and "index" are required flags. Local
testing shows that drive shows up properly as `/dev/sda` after
this change.
=> The `-drive` parameter for qemu run requires more flags

scripts/LinuxKit.ps1
This script can create/start/stop/remove Hyper-V VMs. The
VMs are configured as Gen2 VMs which boot from EFI ISOs.
Network and Disk configuration is optional.
=> scripts: Add simple Powershell script to manage  Hyper-V VMs

Makefile
Always do `moby build --pull` on CI.
=> Pull images on CI

.gitignore, Makefile, kernel/Dockerfile, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/run_qemu.go, tools/mkimage-gcp/make-gcp, tools/mkimage-iso-bios/make-iso, tools/mkimage-iso-efi/make-efi, tools/mkimage-qcow/make-qcow, tools/mkimage-vhd/make-vhd, tools/mkimage-vmdk/make-vmdk
Previously we hardcoded `bzImage` which is not used for all
use cases or architectures.
fix #1630
~~Requires https://github.com/moby/tool/pull/8 to be merged~~
=> Change to use kernel not bzImage everywhere

scripts/kernels/Dockerfile.deb, scripts/kernels/debian.sh, scripts/kernels/mainline.sh, scripts/kernels/ubuntu.sh
This PR adds support for repackaging kernel debian packages from the Ubuntu mainline PPA (which tracks kernel.org releases) as well as the main Ubuntu and Debian kernel packages.
The scripts are written in a way that they should be run daily/weekly as they scrape the relevant websites and determine the kernel version. It then compares this with images on Hub before building/signing/pushing.
I have not started the scripts yet, but will when merged.
wip: #1431
closes: #1265
=> Add support for building mainline, Ubuntu and Debian kernel packages

examples/swap.yml, pkg/swap/swap.sh
Fix `examples/swap.yml` to:
1. Use correct path for `swap.sh`
2. Updated to a more recent kernel version
Run.
Update kernel in swap.yml example and use correct path to script for onboot container
=> use updated kernel and correct path in examples/swap.yml

examples/swap.yml, pkg/swap/Dockerfile, pkg/swap/README.md, pkg/swap/swap.sh
* Added support for encrypted swap
* Added encrypted-swap.yml example
1. Add `cryptsetup` to `linuxkit/swap` image
2. Add `--encrypt` option
3. When `--encrypt` is provided, use `cryptsetup` to set up encrypted swap
Run it with `--encrypt`. When successful (takes a few seconds), the swapfile should be `/dev/mapper/swap` (check in `/proc/swaps`), which is devicemapped via plain encryption to `/var/external/swap` (or whatever is in the `.yml` file)
Add support for encrypted swap as an `onboot` option, along with example `.yml` file.
=> Add support for encrypted swap

docs/kernels.md, scripts/kernels/Dockerfile.deb, scripts/kernels/Dockerfile.rpm, scripts/kernels/centos.sh, scripts/kernels/debian.sh, scripts/kernels/fedora.sh, scripts/kernels/mainline.sh, scripts/kernels/ubuntu.sh
- Add selected Fedora and CentOS kernels (resolves #1431)
- Improve scripts:
- Don't pull to check if an image is on hub. For some repos there are many, many images
- Run `depmod` on modules. Allows `modprobe` to work. (wip #1742)
- Clean images after build
- Add `System.map` to kernel image
- Update documentation
=> Add CentOS/Fedora kernels. Fix/Improve kernel images

docs/kernels.md
Hey,
i think there is a typo at the end of `docs/kernels.md`.
=> Fix typo in docs/kernels.md

examples/docker.yml, pkg/docker-ce/Dockerfile
Bring it into line with official images: remove `jq`, `sfdisk` which
are not needed; we used them for disk mounting but this is down standalone.
Add the tools for other filesystems, which are needed for `dm`, `btrfs`.
cc @cpuguy83 
We should move this to `moby` soon.
=> Adjust docker-ce package

src/cmd/linuxkit/run_qemu.go
- Use 'disk-size' for disk size
- Use 'disk' for the path to the disk image
- Use 'fw' for the path to the EFI firmware
related to #1756
=> cmd: Unify 'run' cmdline options

projects/kubernetes/boot-master.sh, projects/kubernetes/boot-node.sh
It seems that `-disk-size` is now `-disksize`.
Also, drop `hyperkit` from the `linuxkit run` invocation, thus causing the
linuxkit tool to pick the platform's default backend (which is qemu on my Linux
system, which works better than hyperkit in this environment).
(full disclosure: I've booted master, booting node seems to require me to read more of the README, but I propagated the same changes blindly nonetheless)
Updated `projects/kubernetes/boot-*.sh`
emacs
Run the `boot-master.sh` script.
=> projects/kubernetes: Fixup boot-*.sh

docs/kernels.md, kernel/Dockerfile, test/kmod/Dockerfile, test/kmod/check.sh, test/kmod/kmod.yml, test/kmod/run_test.sh, test/kmod/src/Makefile, test/kmod/src/hello_world.c
- Fix the contents of `kernel-dev.tar`. This now contains all the necessary headers/files to compile kernel modules against the specific kernel
- Add sample/test for kernel module building and loading
- Add documentation on how to build modules
resolves #1263 
wip #1568
=> Add support for building custom kernel modules

.gitignore, Makefile
This makes it easier for CI to grab artifacts from the ephemeral build
VMs and provides a stable location so they can be used in subsequent
tests. For example, running the LTP tests.
=> Makefile: gather all build artifacts in one location

Makefile, src/initrd/initrd.go
In the WIP code in `moby` we now have a standard base tarball format,
that includes the kernel and cmdline as files in `/boot` so that the
entire output of the yaml file can default to a single tarball. Then
this can be split back up by LinuxKit into initrd, kernel and cmdline
as needed. This will probably become the only output of the `moby build`
stage, with a `moby package` stage dealing with output formats.
We may remove the output format specification from the yaml file as well,
and just have it in the command.
=> Code in the initrd generator to split a single tarball

docs/external-disk.md
Added doc for using external disk with `linuxkit run`
Wrote a single markdown doc in `docs/`
Read it.
Doc explaining how to mount external disk when running `linuxkit run ... `
As requested by @rneugeba in Slack channel. Following this one, will have separate one for mount options with containers.
=> Add docs on how to use external disk

docs/yaml.md
Added documentation capturing the additional mount options sometimes needed when a container should create a new mount that propagates beyond the container itself.
As requested by @rneugeba and @justincormack 
Modified `docs/yaml.md`
Read it. I expect I made some errors. :-)
Document special mounting options.
=> Add docs how to use mount options for special mounting containers

Makefile
Adds support for tar output, various fixes.
=> Update moby tool

Makefile
Symlinks were being handled incorrectly in initrd output.
Fix #1792
=> Update moby tool to fix symlinks handling

examples/minimal.yml, examples/node_exporter.yml, linuxkit.yml, pkg/init/etc/init.d/rcS, projects/etcd/etcd.yml
This was there due to some bugs that are now fixed, so remove.
=> Remove making directories from init

docs/metadata.md, pkg/metadata/main.go
Fixed a bug in parsing the input JSON and added a less verbose mechanism to populate a data (i.e. not executable) file 
If a file key corresponds to a string rather than a map take that to be the desired file contents and write it with the default rw permissions (moduo `umask`). If the key corresponds to a map then the existing scheme (with separate `content` and `perm` keys) is maintained.
Provide e.g. `{ "foo": { "bar": "some contents" } }` and observe that `/var/config/foo/bar` contains `some contents`.
Metadata JSON can now contain a simple string which will be written to the file
=> Metadata fix + a simpler file content option

docs/metadata.md, src/cmd/linuxkit/main.go, src/cmd/linuxkit/metadata.go, src/cmd/linuxkit/run_hyperkit.go
This is a thin wrapper to create an iso file in the format expected by
`pkg/metadata`.
Currently very basic and just takes the content on the command line but could
be extended to read from a file etc.
Added a new `linuxkit` subcommand to create a metadata iso
Emacs
Run `linuxkit mkmetadata meta.iso '{ "foo": { "bar": "some contents" } }'` and boot an image (with #1802 merged) using that ISO. Observe that `/var/config/foo/bar` contains `some contents`
Added new `mkmetadata` subcommand to `linuxkit`
=> Add `linuxkit metadata create` command

.gitignore, Makefile, tools/mkimage-img-gz/Dockerfile, tools/mkimage-img-gz/Makefile, tools/mkimage-img-gz/make-img-gz
This is a fairly generic bootable disk with syslinux. Should
work if you `dd` it onto a USB stick, and should also work for AWS.
You need to uncompress it of course! Default size is 1G.
`moby` PR coming shortly.
=> Add image builder for compressed disk image

examples/docker.yml, examples/gcp.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/runc/Dockerfile, projects/etcd/etcd.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/okernel/examples/okernel_simple.yaml, test/cases/test-docker-bench.yml, test/cases/test-kernel-config.yml, test/cases/test-ltp.yml, test/cases/test-virtsock-server.yml, test/kmod/kmod.yml
Works around https://github.com/moby/moby/issues/33176 and fixes #1807.
Updated al users of linuxkit/runc:2649198589ef0020d99f613adaeda45ce0093a38 to
this new build.
Removed unexpected `/root/go/src/github.com/opencontainers/runc` from runc image.
Moving the `WORKDIR` immediately after the `FROM scratch` to workaround https://github.com/moby/moby/issues/33176
Use `docker save` to inspect the image (as shown in #1807) or boot a LinuxKit image and check for `/root/go`.
Removed stray `/root/go/src/github.com/opencontainers/runc` from runc image.
=> pkg/runc: WORKDIR as first item in second stage

projects/kubernetes/ssh.sh
Signed-off-by: Jesse Adametz <jesseadametz@gmail.com>
Fixes #1814 
Added the `--rm` flag to the `docker run` command inside of `projects/kubernetes/ssh.sh`
=> Add rm flag to projects/kubernetes ssh script

projects/kubernetes/ssh_into_kubelet.sh
Signed-off-by: Jesse Adametz <jesseadametz@gmail.com>
Fixes #1817 
Specified `root@` before the interpreted IP address within the `projects/kubernetes/ssh_into_kubelet.sh` script.
Follow the `projects/kubernetes/README.md` instructions and successfully SSH into a running kubelet without having to manually specify the user.
=> Specifies root user in projects/kubernetes ssh_into_kubelet script

.gitignore, Makefile, src/cmd/linuxkit/run_gcp.go, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/run_vmware.go
Some runners require state to be kept somewhere while they are executing. Examples are the virtio socket unix domain socket for HyperKit and various log and config files for the VMware runner. This patch set introduces a new `-state` argument to the HyperKit and VMware runners. These are the only ones which require such state (the qemu backend ony optionally creates a userdata disk). The state directory defaults to `<prefix>-state\` but can be overwritten.
Having a state directory allows us to enable the virtio socket interface for the HyperKit runner.
While at it, also clean up the backend code somewhat. The different runners were written by different people and the variables and other implementation details were inconsistent.
=> Use a "state" directory for linuxkit run state and enable virtio sockets

src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/util.go, vendor.conf, vendor/github.com/moby/hyperkit/README.md, vendor/github.com/moby/hyperkit/go/hyperkit.go, vendor/github.com/moby/hyperkit/src/include/xhyve/firmware/bootrom.h, vendor/github.com/moby/hyperkit/src/include/xhyve/firmware/fbsd.h, vendor/github.com/moby/hyperkit/src/include/xhyve/firmware/kexec.h, vendor/github.com/moby/hyperkit/src/include/xhyve/firmware/multiboot.h, vendor/github.com/moby/hyperkit/src/lib/pci_virtio_net_vpnkit.c
Adds a new option `-vsock-ports` that can be used to make listed vsock ports in the guest available as unix domain sockets in the state-directory.
Also updates the hyperkit version in `/vendor`. 
(Running `vndr` from the root dir removed several of the existing dependencies as they were reported to not be in use, but I didn't include the deleted files in this PR.)
=> Add option for forwarding vsock ports in linuxrun for hyperkit

reports/sig-security/2017-05-24.md, sigs/README.md, sigs/security/README.md
Following up on https://github.com/moby/mobywebsite/pull/11, adding more info and agenda/notes to the linuxkit repo under a `sigs` top level dir.  I've setup the zoom meeting and forum topic as well.  Aiming for May 24th as the first meeting, though this is flexible (intro email coming soon)
I'll update the mobywebsite repo once this is merged
cc @chanezon 
=> Add security SIG info and notes

.gitattributes
Ignore go files in `vendor`
Kernel config files are text and not Logos
=> Fix Github language detection

docs/testing.md
This documents the current CI setup and how to run and write tests.
=> Document the CI setup

kernel/Makefile, kernel/patches-4.11.x/0001-vmbus-introduce-in-place-packet-iterator.patch, kernel/patches-4.11.x/0002-vmbus-vmbus_open-reset-onchannel_callback-on-error.patch, kernel/patches-4.11.x/0003-vmbus-add-the-matching-tasklet_enable-in-vmbus_close.patch, kernel/patches-4.11.x/0004-vmbus-remove-goto-error_clean_msglist-in-vmbus_open.patch, kernel/patches-4.11.x/0005-vmbus-dynamically-enqueue-dequeue-a-channel-on-vmbus.patch, kernel/patches-4.11.x/0006-hv_sock-implements-Hyper-V-transport-for-Virtual-Soc.patch, kernel/patches-4.11.x/0007-VMCI-only-try-to-load-on-VMware-hypervisor.patch, kernel/patches-4.11.x/0008-hv_sock-add-the-support-of-auto-loading.patch, kernel/patches-4.11.x/0009-hvsock-fix-a-race-in-hvs_stream_dequeue.patch
While testing the new support for Hyper-V sockets in 4.11 we discovered some issues. The updated patches from Microsoft in this PR address this issue. I have run some light stress tests and they passed (after failing previously). I will run more tests over night but this is a definite improvement over the previous patches.
While at it, also make the Hub org configurable during build, ie:
```
make push_4.11.x ORG=rneugeba
```
pushes the image to my Hub account for testing (wip #1824)
=> Update Hyper-V patches for 4.11 and add Hub org override for kernel builds

kernel/Dockerfile
The vmlinux image is the un-stripped kernel image containing
full debug information which is useful for kernel debugging.
=> kernel: Add vmlinux to debug builds

src/cmd/linuxkit/run_qemu.go
`linuxkit run --containerized foo`
Added `--containerized` option to the Qemu runner, to aid in reproducing https://github.com/linuxkit/linuxkit/issues/1828.
Typing.
`linuxkit run qemu --containerized` will run in a container 
`linuxkit run qemu --containerized` can now be used to force the use of the Qemu container rather than host Qemu.
=> Allow forcing qemu backend to use container via command line

src/cmd/linuxkit/run_qemu.go, vendor/golang.org/x/crypto/ssh/terminal/terminal.go, vendor/golang.org/x/crypto/ssh/terminal/util.go, vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go, vendor/golang.org/x/crypto/ssh/terminal/util_linux.go, vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go, vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
Otherwise escape codes (arrow keys etc) do not.
For clarity spell `--tty-` and `--interactive` out in full rather than using
the short versions.
Added `--tty` to `docker run` for the Qemu runner. This fixes #1828
Emacs.
Run a linuxkit image with `linuxkit run qemu --containerized` and check that arrow keys and `ls --color` etc should work without echoing escape codes to the terminal
Arrow keys and other escape codes now work when running Qemu via a container
=> Pass `--tty` to `docker run` when running Qemu via a container

src/cmd/linuxkit/run_qemu.go
- show errors by outputting stderr
- as no input is wired up, fails as requests a tty, so don't do that
=> Fixes for running qemu-img in a container

src/cmd/linuxkit/run_qemu.go, test/cases/010_platforms/000_qemu/010_run_iso/test.sh, test/cases/010_platforms/000_qemu/020_run_efi/test.sh, test/cases/010_platforms/000_qemu/030_run_qcow/test.sh, test/cases/010_platforms/000_qemu/030_run_qcow/test.yml, test/cases/020_kernel/000_config_4.4.x/test.sh, test/cases/040_packages/000_sysctl/test.sh
For all output formats except kernel+initrd, recommend that people just
add the full path of the file they want to run. If you do this, generally
make the options automatic.
Split the uefi option to mean "use uefi firmware" not be ISO specific.
Allow specifying a bootable disk image, so we can test disk image output
formats with qemu too.
Specifying a prefix for anything other than kernel+initrd is deprecated
and will be removed at some point.
=> Clean up of Qemu run

examples/redis-os.yml
=> examples: switch dhcpd to onboot in redis-os example

examples/docker.yml, examples/gcp.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/binfmt/Dockerfile, pkg/dhcpcd/Dockerfile, pkg/rngd/Dockerfile, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/okernel/examples/okernel_simple.yaml, projects/swarmd/swarmd.yml, test/cases/000_build/000_outputs/test.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/hack/test.yml
This adds the config label to the `binfmt`, `dhcpcd`, and `rngd` packages and updates the YAML files to remove the now unnecessary additional container configs. `dhcpcd` and `rngd` are easily the most commonly used packages.
While at it, I also update the packages to use the latest Alpine base
=> Add moby config label to common packages

docs/security-events.md
As of the time of this patch, the CVE was not available yet in the mitre
db.
=> docs: add a blurb about CVE-2017-1000363

docs/external-disk.md, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/run_vmware.go, src/cmd/linuxkit/util.go
- '-disk-size' is now always in MB
- The disk will be created if it doesn't exist (didn't happen in qemu)
Update the documentation.
resolves: #1886
=> cmd: Unify disk command line options for local hypervisors

pkg/mkimage/Dockerfile, pkg/mkimage/Makefile, pkg/mkimage/mkimage.sh, test/cases/040_packages/001_mkimage/mkimage.yml, test/cases/040_packages/001_mkimage/run.yml, test/cases/040_packages/001_mkimage/test.sh
This is a package that creates bootable disk images. This will be used to replace the `mkimage-*` packages. It is generally expected that you will use `qemu` to make these, so it can make `raw` or `qcow2` images, or other supported disk formats. Currently it will make `ext4` bootable `syslinux` based images, but I plan to add more configuration options later.
=> Add a mkimage package

reports/sig-security/2017-06-07.md
cc @fntlnz for buildchain security discussion topic
cc @avsm @samoht for time-allocation - do you think we need more time for the deep dive?  I can shuffle topics around :)
=> Add buildchain security to agenda, proposed time allocations

docs/signing/notary.md, pkg/ca-certificates/Makefile, pkg/containerd/Makefile, pkg/dhcpcd/Makefile, pkg/format/Makefile, pkg/init/Makefile, pkg/metadata/Makefile, pkg/mount/Makefile, pkg/openntpd/Makefile, pkg/runc/Makefile, pkg/sshd/Makefile, pkg/sysctl/Makefile, pkg/sysfs/Makefile, tools/alpine/Makefile
I've setup signing for more repos, notably:
```
docker.io/linuxkit/alpine
docker.io/linuxkit/sysctl
docker.io/linuxkit/sysfs
docker.io/linuxkit/dhcpcd
docker.io/linuxkit/init
docker.io/linuxkit/metadata
docker.io/linuxkit/mount
docker.io/linuxkit/format
docker.io/linuxkit/openntpd
docker.io/linuxkit/sshd
docker.io/linuxkit/runc
docker.io/linuxkit/containerd
docker.io/linuxkit/ca-certificates
```
NOTE: I haven't gone through and repushed all of those repos with content trust yet - once I do that I'll also update the appropriate yml files to require trust for these repos.
I've also added a brief primer doc on setting up the signing process - it relies on keys that I maintain/safely store.  @justincormack @rneugeba @ijc25 as maintainers we can figure out the best way to securely share them …
=> More signing!

src/cmd/linuxkit/run_hyperkit.go, vendor.conf, vendor/github.com/moby/hyperkit/README.md, vendor/github.com/moby/hyperkit/go/hyperkit.go, vendor/github.com/moby/hyperkit/src/lib/block_if.c, vendor/github.com/moby/hyperkit/src/lib/mirage_block_c.c, vendor/github.com/moby/hyperkit/src/lib/mirage_block_c.h
Adds a flag to launch a new vpnkit instance. This enables port
forwarding to be configured via a 9p mount (tag:port) if the guest 
supports it. Vsock port 62373 is also opened so vpnkit can forward 
connections back to the guest.
If -start-vpnkit is not specified HyperKit will connect to the
vpnkit instance managed by Docker for Mac, as before.
=> Add -start-vpnkit flag to linuxkit run hyperkit

src/cmd/linuxkit/run_qemu.go
As I am using this command in the internals of `moby` the
verboseness is annoying.
=> Only output qemu disk creation info in debug mode

projects/ima-namespace/Makefile, projects/ima-namespace/ima-namespace.yml, projects/ima-namespace/ima-utils/Makefile
`linuxkit/kernel-ima` and `linuxkit/ima-utils` exist now, so let's use images that have been uploaded there.
=> Add ima kernel images

tools/alpine/packages, tools/alpine/versions
While not used anywhere, adding it to the based makes it easy
to add temporarily add it to init (or elsewhere) for debugging.
New hash is: linuxkit/alpine:451603daf499e3a40308dbf5571dcffed2343ffa
=> tools: Add strace to the Alpine base

src/cmd/linuxkit/run_qemu.go
The error was incorrect when unable to parse the disk size.
Noticed that the error for unable to parse disk size was the wrong way around
Modified the error output so that it notifies the user that the size couldn't be parsed correctly.
```
./linuxkit run qemu -disk-size 10A0G ./util.go 
FATA[0000] Couldn't parse disk-size 10A0G: strconv.Atoi: parsing "10A0": invalid syntax 
```
Corrected the typo error when unable to parse a `disk-size`
=> Fixes disk size output typo

src/cmd/linuxkit/run_hyperkit.go, vendor.conf, vendor/github.com/moby/hyperkit/go/hyperkit.go
Adds a new bool option to disable networking with `linuxkit run hyperkit`.
Networking is enabled by default.
Fixes #1912
=> hyperkit: Add --networking option

examples/docker.yml, examples/gcp.yml, linuxkit.yml, pkg/binfmt/Dockerfile, pkg/metadata/Dockerfile, pkg/metadata/Makefile, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/040_packages/002_binfmt/test-binfmt.yml, test/pkg/virtsock/Dockerfile
This removes the use of the go-compile package for package builds and converts the metadata package to use a multi-stage build
resolves #1919
=> Remove remaining uses of tools/go-compile from packages

pkg/qemu-ga/Dockerfile, pkg/qemu-ga/Makefile, projects/swarmd/swarmd.yml
We don't actually build it here, we just use the alpine package.
Can be instantiated with a service stanza such as:
```
- name: qemu_ga
image: "linuxkit/qemu_ga:ffc2c35a1126aeab5a324254ce83c4b302eeaf04"
binds:
- /dev/vport1p1:/dev/vport1p1
command: ["/usr/bin/qemu-ga", "-p", "/dev/vport1p1"]
net: host
```
Note that `net: host` is required since one function (and the only one I've
tested) is to report IP addresses to the host (e.g. via `virsh domifaddr`).
The mdev tool appears to not create the symlinks which udev would provide
`/dev/virtio-ports/org.qemu.guest_agent.0` hence the need to hardcode the
potentially unstable `/dev/vportNp1`, `N` seems to depend on the number and
order of virtio devices in use. I don't know if it is possible to get mdev to
create these links. For reference the …
=> Add a simple qemu guest agent package

src/cmd/linuxkit/push.go
This fixes the push function as it currently gives the help for `run`
not `push`.
Fixed the Usage function call inside of `push.go`
Fixed the typo so it called `pushUsage()` instead of `runUsage()`
```
./bin/linuxkit push
USAGE: linuxkit push [backend] [options] [prefix]
'backend' specifies the push backend.
Supported backends are
gcp
'options' are the backend specific options.
See 'linuxkit push [backend] --help' for details.
'prefix' specifies the path to the VM image.
```
Fixed push Usage typo.
=> Fix correct usage function

docs/signing.md
Moved the signing doc to the top level `/docs` dir since it made more sense there, and also addressed @ijc25's comments to remove the unused `apple js` tags since we're only viewing off of GitHub at present.
=> docs: move signing doc to top level and remove applejs tags

docs/security-events.md
Here's some writeups of recent CVEs. Patches for some are still making their way through the CVE process, so they are outstanding in linuxkit.
=> docs: add some writeups of recent CVEs

src/cmd/linuxkit/push.go, src/cmd/linuxkit/push_vcenter.go, src/cmd/linuxkit/run_vcenter.go
Re-factored the `run` code to create the `push` functionality.
Added the capability to `push` Linuxkit `.iso` images to VMware vCenter. It uses a either a `-folder=<NAME>` or will take the name of the image and create that folder to host the uploaded image.
Modified `run_vcenter.go` to allow `push_vcenter.go` to log in to vCenter and upload images without creating a full VM. 
`Push` functionality
```
./bin/linuxkit push vcenter -datastore=vSphereNFS -hostname=esxi01.fnnrn.me -folder=sharedLinuxKit2  ./vcenter.iso 
Uploading LinuxKit file [./vcenter.iso]
```
`run` functionality (ensuring changes haven't broken existing functionality.
```
./bin/linuxkit run vcenter …
```
=> vCenter push capability

docs/external-disk.md, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/run_vmware.go, src/cmd/linuxkit/util.go, test/cases/010_platforms/000_qemu/030_run_qcow/test.sh, test/cases/040_packages/013_mkimage/test.sh
I needed multiple disks for `mkimage` to make it easier to pass data in and out as using the network under `qemu` was a pain. Still need to change the other backends to use the same CLI syntax, just seeing if any objections...
This changes the CLI specification for disks, as it needs to be able to
be repeated.
```
linuxkit run qemu -disk name,size=1G,format=qcow2 ...
```
Options may be omitted.
=> Support multiple disks in qemu

pkg/mkimage/Dockerfile, pkg/mkimage/mkimage.sh, test/cases/040_packages/013_mkimage/mkimage.yml, test/cases/040_packages/013_mkimage/test.sh
This uses the qemu multi disk support for the `mkimage` package - instead of baking in the images into the VM, it passes them as a tarball, disguised as a raw disk. This means you can use the same `mkimage` VM again and again without rebuilding it each time, plus it is faster as the image is smaller. This was nicer than using the network in the end.
=> Update mkimage to use a tarball as source for files

projects/compose/.gitignore, projects/compose/Makefile, projects/compose/README.md, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/compose/docker-compose.yml, projects/compose/html-a.html, projects/compose/html-b.html, projects/compose/image/Dockerfile, projects/compose/image/load-images-and-compose.sh, projects/compose/image/waitfordocker.sh
Added examples to run compose on a linuxkit image, both dynamic (loads container images from registry runtime) and static (loads container images into linuxkit image)
1. Container image `linuxkit/compose` that has both `docker` client and `docker-compose` in it, as well as a `waitfordocker.sh` that waits for docker to be ready, and a `load-images-and-compose.sh` that looks for images in a specified path and compose in a specified path.
2. `README.md` describing how it works and how to use it
3. `Makefile` to build the various parts, including caching local images
4. linuxkit `.yml` files (one each for dynamic and static) to implement
Run each version. See that the services start.
Add compose …
=> add compose dynamic

projects/miragesdk/yaml/dhcp-client.yml, projects/miragesdk/yaml/dhcp.capnp
The intention with the yaml fragment is that it specifies the
set of processes that form the daemon, with minimal privileges
for each component and each running inside a separate container.
In addition to the normal container capabilities, there is also
a new field which lets a startup process establish an RPC channel,
based on a Capnp specification. This allows for extremely
unprivileged components to be started, such as the `dhcp-engine`
in this example which can only communicate with the outside world
via the `dhcp-network` (to transmit) or `dhcp-actuator` (to alter
the state of the local Linux distribution).
This is a first cut at the yaml interface and the capnp, with the
intention to refine it as we combine it with the rest of the existing
prototype (which currently doesnt have an …
=> projects/miragesdk: add a frontend yaml format for dhcp-client

projects/miragesdk/src/test/jbuild, projects/miragesdk/src/test/test.ml
This fixes basic build issues.
=> sdk: update the tests to use mtime 1.0 and logs.fmt

examples/vsudd.yml, pkg/vsudd/Dockerfile, pkg/vsudd/Makefile, pkg/vsudd/README.md
Adds new package`vsudd` that clones and builds `linuxkit/virtsock/cmd/vsudd`. This is #1947 with the vsudd code removed.
I've added a minimal example and a README.md for controlling containerd from the host with ctr.
Pushed to a temporary hub user for now so the example works.
=> Add /pkg/vsudd

docs/gcp.md
The proper way to output an image for GCP is to use `-output gcp-img`.
Fixes #1966
Signed-off-by: David Gageot <david@gageot.net>
=> Fix outdated GCP docs

src/cmd/linuxkit/push_aws.go
Signed-off-by: Dieter Reuter <dieter.reuter@me.com>
Fix coding error, so the default `-img-name` will now be set correctly to the basename of the provided image file.
Use filename from variable `src` as the default for `-img-name`.
Before the fix, the used image name was empty, so you'll see `Key: ".img"` in the debug log and the import/register as AMI raises an error.
```
$ linuxkit -v push aws -bucket <BUCKET_NAME> aws.img
DEBU[0000] PutObject:
{
Body: buffer(0xc42000c0e0),
Bucket: "<BUCKET_NAME>",
ContentLength: 209715200,
ContentType: "application/octet-stream",
Key: ".img"
}
```
With the fix, it'll work correctly with `Key: "aws.img"` and the correct AMI name `aws` will be used.
Fix setting …
=> Fix empty AWS default image name

Makefile
The GOOS and GOARCH are currently set based on the host 'make'
is executed on. On macOS this sets up cross compilation with
a Linux container.
Making them over-writeable allows users to test different
cross compilations, e.g., trying to build Linux binaries on macOS.
=> build: Make GOOS and GOARCH over-writeable

examples/getty.yml
From discussion on https://github.com/linuxkit/linuxkit/pull/1977#issuecomment-306940223 - the correct getty tag is this one.
=> pkg/getty: fix example image tag

Makefile, pkg/Makefile, pkg/binfmt/Dockerfile, pkg/ca-certificates/Dockerfile, pkg/dhcpcd/Dockerfile, pkg/docker-ce/Dockerfile, pkg/format/Dockerfile, pkg/init/Dockerfile, pkg/mkimage/Dockerfile, pkg/mount/Dockerfile, pkg/open-vm-tools/Dockerfile, pkg/openntpd/Dockerfile, pkg/qemu-ga/Dockerfile, pkg/rngd/Dockerfile, pkg/runc/Dockerfile, pkg/sshd/Dockerfile, pkg/swap/Dockerfile, pkg/sysctl/Dockerfile, pkg/sysfs/Dockerfile, pkg/vsudd/Dockerfile, projects/swarmd/swarmd/Dockerfile, projects/wireguard/tools/Dockerfile, test/pkg/virtsock/Dockerfile
0eb21735ae1b73d6012beff2898aaae49bf46f34 accidentally broke some package
builds by switching linuxkit/alpine to linuxkit/containerd. Let's revert
the ones that shouldn't be there.
Closes #1991
=> fix package builds in some cases

test/cases/020_kernel/000_config_4.4.x/test.sh, test/cases/020_kernel/001_config_4.9.x/test.sh, test/cases/020_kernel/003_config_4.11.x/test.sh, test/cases/020_kernel/010_kmod_4.9.x/test.sh, test/cases/040_packages/002_binfmt/test.sh, test/cases/040_packages/003_ca-certificates/test.sh, test/cases/040_packages/004_dhcpcd/test.sh, test/cases/040_packages/019_sysctl/test.sh, vendor.conf, vendor/github.com/moby/hyperkit/go/hyperkit.go, vendor/github.com/moby/hyperkit/go/pty_util_darwin.go, vendor/github.com/moby/hyperkit/go/pty_util_fallback.go, vendor/github.com/moby/hyperkit/go/vendor.conf
The newly vendored HyperKit go bindings allow for redirection of stdout (resolves #1923) and thus allows us to use HyperKit on OSX for the kernel and most of the package tests.
Ideally we would set labels on which platforms these tests are run, but there seems to be an [issue](https://github.com/linuxkit/rtf/issues/16) with labels and `rtf`.
=> Convert some tests to run on hyperkit when run on OSX

linuxkit.yml
The 'docker.json' file is not used in the top level
example and was merely there as an example use of the
'file' section. Since we now have the containerd config
file in the 'file' section the 'docker.json' entry is
no longer needed.
=> example: Remove docker.json from linuxkit.yml

examples/getty.yml, pkg/getty/Makefile
Make the `makefile` consistent with the others. This updates the tag again, so hopefully this resolves that issue.
=> Getty cleanup

test/cases/000_build/000_outputs/test.sh
I disabled this for speed when content trust cache was not working
See also #1995
=> Re-enable content trust on build test

Makefile
This patch adds cross compilation steps for Linux, macOS and,
Windows to the CI targets to ensure that the all commands cross
compile nicely.
Although the CI runs on Linux we still explicitly compile for
Linux in case developers use the CI targets locally on a
non-Linux host.
=> build: Make sure the tools compile on Linux/macOS/Windows

.mailmap
relates to https://github.com/linuxkit/linuxkit/pull/1999
When mapping e-mail addresses and names;
<preferred@example.com> <foo@bar.com>
Maps `foo@bar.com` to `preferred@example.com`, whereas:
Preferred Name <preferred@example.com> <foo@bar.com>
Will update the e-mail address _and_ set the preferred name, _if_ the original
e-mail address in the commit was `<foo@bar.com>` (otherwise the rule is not
executed).
Finally, this rule:
Preferred Name <preferred@example.com>
Will set the name to `Preferred Name` if the e-mail address in the commit
matches `preferred@example.com`
Empty the entries from the `AUTHORS` file, and regenerate it with `scripts/generate-authors.sh`. The generated AUTHORS file should not change
**- A picture of a cute animal (not …
=> Update .mailmap to make auto-generating work

pkg/init/etc/init.d/000-issue, pkg/init/init
Removed the `getty` functionality from `linuxkit/init`. The only tty-related code left is to `cat /etc/issue` to the given tty, and even that probably could be removed or replaced.
Remove most of the code from `setup_console()` in `pkg/init/init`
1. Build the container image
2. Build a linuxkit image using this new `init` image instead of the original one
3. See that no getty is started: you cannot login on console, nor do you get a shell
Remove getty functionality from init in favour of `linuxkit/getty`
Another croc, because that is what I did for the getty PR:
Some important points:
1. This should be merged in only *after* the PR …
=> Remove all getty from init

examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vsudd.yml
Updated `linuxkit/init` to the gettyless version per #1978  and inserted `linuxkit/getty` as a `service` per #1977 for relevant examples. 
Updated the yml files.
Build and run them.
Update init in images to use gettyless and use getty where relevant.
Per the request on the other PRs to update examples.
=> Update linuxkit/init to gettyless; add getty to relevant examples

docs/external-disk.md, src/cmd/linuxkit/util.go
Most cloud providers allow disk size allocation on in units
of GB. Make it the default for linuxkit disk "size" arguments.
Users can override the unit by appending a M to the disk size.
=> cmd: Default disk "size" parameter to GB

projects/miragesdk/examples/mirage-dhcp.yml, projects/miragesdk/src/Dockerfile, projects/miragesdk/src/Makefile, projects/miragesdk/src/dhcp-client-calf/unikernel.ml
Changed the MirageSDK dhcp client example to use a branch of `charrua-client` with a better API for MirageSDK.
=> MirageSDK: Use newer dhcp client

pkg/metadata/provider_aws.go
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>
There is a lot of metadata available from the AWS metadata service. We originally were only capturing a few fields, this PR adds some of the more common data as well to make it easily available when you need it.
New fields added:
- public ipv4 address
- private ipv4 address
- availability zone
- instance id
- instance type
- local hostname
changed the metadata package to query the data from AWS metadata service and write the data to the /var/config directory.
build the package and run on aws, and then look inside of `/var/config` you will notice more data available.
Enhanced the AWS provider in the metadata package, to include more data.
=> Enhanced the AWS provider in the metadata package, to include more data.

test/cases/000_build/000_outputs/test.yml, test/cases/010_platforms/000_qemu/000_run_kernel/test.yml, test/cases/010_platforms/000_qemu/010_run_iso/test.yml, test/cases/010_platforms/000_qemu/020_run_efi/test.yml, test/cases/010_platforms/000_qemu/030_run_qcow/test.yml, test/cases/010_platforms/000_qemu/040_run_raw/test.yml, test/cases/010_platforms/000_qemu/100_container/test.yml, test/cases/010_platforms/010_hyperkit/000_run_kernel/test.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
If you also use console=tty0 you lose the output of commands running from
the system, as they run on the second console which is discarded.
Also drop page-poison as not relevant for tests.
=> Only use console=ttyS0 for tests

docs/platform-hyperkit.md, examples/vpnkit-forwarder.yml, pkg/vpnkit-forwarder/Dockerfile, pkg/vpnkit-forwarder/Makefile, pkg/vpnkit-forwarder/README.md
Adds /pkg/vpnkit-forwarder which downloads and builds `vpnkit-forwarder`
and `vpnkit-expose-port` from moby/vpnkit. Also includes an example for
forwarding `sshd` and updates the documentation for `hyperkit` to
include a `vpnkit` section.
`vpnkit` still requires a 9P mount for coordination, so the `socat`
forwarding is simpler to set up at the moment.
I've pushed to a temporary location so the example works.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
=> vpnkit-forwarder: add /pkg/vpnkit-forwarder

docs/security-events.md
update these docs to reflect that the kernel bumps fix them.  Changed around categories to better fit the scope of LinuxKit.  cc @tych0 
=> docs: update security events with new kernels

Makefile, examples/azure.yml, examples/packet.yml, examples/sshd.yml, examples/vpnkit-forwarder.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/okernel/examples/okernel_simple.yaml
This requires moby tool update to support `~` in paths, but
makes everything much nicer.
=> Use the user's ssh key automatically in ssh examples

src/cmd/linuxkit/run_hyperkit.go, vendor.conf, vendor/github.com/moby/hyperkit/go/hyperkit.go
Now hyperkit Go API has multiple disk support, allow using them from linuxkit
=> Update hyperkit and support multiple disks

examples/docker.yml, pkg/docker-ce/Dockerfile, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/kubernetes/image-cache/Dockerfile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
Adds vpnkit-expose-port to the docker-ce image.
vpnkit-expose-port is the dockerd userland proxy used to expose
forwarding ports with vpnkit. This adds the binary to the image in
/usr/bin/vpnkit-expose-port, but does not enable it by default.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
=> pkg/docker-ce: add vpnkit-expose-port

docs/platform-azure.md, src/cmd/linuxkit/push.go, src/cmd/linuxkit/push_aws.go, src/cmd/linuxkit/push_azure.go, src/cmd/linuxkit/push_gcp.go, src/cmd/linuxkit/push_vcenter.go
- Use 'flags' for the subcommand FlagSet
- Use %v to print errors
- Use 'path' for the path
- Fix cases where the 'path' refers to a different directory
- Don't use CamelCase for command line options
=> cmd: Unify the push coding style

projects/miragesdk/examples/https-unikernel/.dockerignore, projects/miragesdk/examples/https-unikernel/.gitignore, projects/miragesdk/examples/https-unikernel/Dockerfile, projects/miragesdk/examples/https-unikernel/Makefile, projects/miragesdk/examples/https-unikernel/README.md, projects/miragesdk/examples/https-unikernel/opam, projects/miragesdk/examples/https-unikernel/src/api.ml, projects/miragesdk/examples/https-unikernel/src/common.ml, projects/miragesdk/examples/https-unikernel/src/debug.ml, projects/miragesdk/examples/https-unikernel/src/http_main.ml, projects/miragesdk/examples/https-unikernel/src/http_server.ml, projects/miragesdk/examples/https-unikernel/src/jbuild, projects/miragesdk/examples/https-unikernel/src/main.ml, projects/miragesdk/examples/https-unikernel/src/proto.capnp, projects/miragesdk/examples/https-unikernel/src/store.ml, projects/miragesdk/examples/https-unikernel/src/store_main.ml, projects/miragesdk/examples/https-unikernel/src/test_store.py, projects/miragesdk/examples/https-unikernel/src/tls_main.ml, projects/miragesdk/examples/https-unikernel/src/tls_terminator.ml
[ Making a PR now so that @avsm can link it in his slides - this is not ready yet ]
I added a sample Mirage project that runs an Irmin-backed https web-server using processes communicating over capnp-rpc. This is intended to demonstrate the RPC system and Irmin.
There is a README in the project directory with instructions. You can build and test everything using Docker, or build it on your host using opam.
Add sample Mirage HTTPS service.
=> Add https example

blueprints/README.md, blueprints/docker-for-mac.yml
Adds a blueprint for the open source components of Docker for Mac. It includes support for VPNKit networking and port forwarding to the host. Docker can be controlled via a unix domain socket in the linuxkit state directory.
=> Docker for Mac blueprint

tools/mkimage-dynamic-vhd/Dockerfile, tools/mkimage-dynamic-vhd/Makefile, tools/mkimage-dynamic-vhd/make-dynamic-vhd
Adding a mkimage package to create dynamic VHD images (static/fixed VHD images are already supported by LinuxKit). Dynamic VHD files are smaller in size, making them much easier to upload to our cloud.
Signed-off-by: Dave Freitag <dcfreita@us.ibm.com>
Created a mkimage package to support the creation of dynamic VHD images. 
I based the new files off of the existing vhd and vmdk mkimage filesets.
Once built into the moby tool as an output format, it can be verified. I can submit a PR to the moby tool for that, but will need assistance getting the tagged 'linuxkit/mkimage-dynamic-vhd:<hash>' image built and pushed first.
Added a mkimage package to support the dynamic VHD output format
=> Adding Dynamic VHD mkimage package

examples/aws.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml
`library` org refers to the [official images](https://hub.docker.com/explore/) on docker hub, which includes nginx, alpine, etc
=> Use library org in examples to verify nginx, other official images

src/cmd/linuxkit/run_hyperkit.go, vendor.conf, vendor/github.com/moby/hyperkit/go/hyperkit.go
Allows routed networking, so long as you runhyperkit as root.
This has quite a few downsides, including the requirement to
run as root in order to set up the networking, but some people
really want VMs that are routable from the host.
=> Add vmnet support to linuxkit run hyperkit

Makefile
This brings updated help text and fixes handling of labels as reported
in https://github.com/linuxkit/rtf/issues/16
=> Update RTF version

docs/kernels.md
Converted link of .kernel in docs/kernels.md to point to ../kernel/README.md
Modified it. 
Read it and verify link works
FIX Docs Link: ./kernel to ../kernel/README.md
=> FIX Docs Link: ./kernel to ../kernel/README.md

README.md
Fixed a typo in the main README.md that was causing a dead link to the
platform-vmware.md file.
Click on it, it resolves now. 
Fixed a typo in the main README.md that was causing a dead link to the
platform-vmware.md file.
Signed-off-by: Dave Freitag <dcfreita@us.ibm.com>
=> Fix Dead Link to VMWare File

kernel/Dockerfile, tools/alpine/packages, tools/alpine/versions
Include `gnupg` package in the base alpine image for kernel signing verification (see https://github.com/linuxkit/linuxkit/issues/2088)
Also include `zfs` from other issue and discussion at moby summit
=> alpine: include gnupg and zfs packages

pkg/binfmt/Makefile, pkg/ca-certificates/Makefile, pkg/containerd/Makefile, pkg/dhcpcd/Makefile, pkg/docker-ce/Makefile, pkg/format/Makefile, pkg/getty/Makefile, pkg/init/Makefile, pkg/metadata/Makefile, pkg/mkimage/Makefile, pkg/mount/Makefile, pkg/node_exporter/Makefile, pkg/open-vm-tools/Makefile, pkg/openntpd/Makefile, pkg/package.mk, pkg/qemu-ga/Makefile, pkg/rngd/Makefile, pkg/runc/Makefile, pkg/sshd/Makefile, pkg/swap/Makefile, pkg/sysctl/Makefile, pkg/sysfs/Makefile, pkg/vpnkit-forwarder/Makefile, pkg/vsudd/Makefile
These now inherit from a top-level package.mk
Options like use of the network can be enabled on a per package basis
This removes a lot of duplicate code and make the maintenace of these
Makefiles much easier
=> Simplify Makefiles for Packages

test/cases/000_build/200_blueprints/010_docker_for_mac/test.sh, test/cases/000_build/200_blueprints/group.sh, test/cases/group.sh
Adds a new test group "linuxkit.build.blueprints" and a test for
building blueprints/docker-for-mac.yml, as requested in #2039.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
=> tests: add build test for Docker for Mac blueprint

test/cases/010_platforms/000_qemu/020_run_efi/test.sh
See #1872 this is very flaky and without a controlled known
working environment this is not helpful.
=> Disable Qemu EFI ISO test for now

Makefile
Remove some incorrect parts, like `tar xf tmp_linuxkit_bin.tar > $@`
Split out the cross build testing, and give it some parallelism, as it is a bit slow.
=> Makefile cleanups

pkg/metadata/main.go, pkg/metadata/provider_vultr.go
Vultr uses a very similar approach to AWS, including using the
same IP address for serving metadata. In fact, it seems
as though if AWS appears first in the list of providers, that
provider mistakenly believes to be running on AWS (hence the
insertion of `NewVultr` in between GCP and AWS). I don't believe
AWS servers will accidentally try to use the Vultr provider,
as it seems that the `/v1/` endpoint doesn't exist on AWS. It would
probably pay to come up with a better way of differentiating between
them though, just to be safe.
Added a metadata provider to gather information from Vultr VPSs.
Copied the AWS provider and made modifications.
I verified it by running a LinuxKit machine on Vultr and examined the resultant metadata. …
=> Add a metadata provider for Vultr

test/cases/040_packages/003_containerd/test.sh, test/cases/040_packages/007_getty-containerd/test-ctr.yml, test/cases/040_packages/007_getty-containerd/test.exp, test/cases/040_packages/007_getty-containerd/test.sh
Fix a typo in the main containerd test too.
Added a test that `ctr run` (and `dist pull`) work from within the `getty` container, to avoid regressions in #2102.
Some `expect(1)` based insanity.
The tests should pass.
Doesn't need anything above the #2102 entry IMHO.
[![](https://upload.wikimedia.org/wikipedia/en/1/15/Alice_in_Chains_Jar_of_Flies.jpg "Alice in Chains, Jar of Flies")](https://en.wikipedia.org/wiki/Jar_of_Flies)
=> test: ensure ctr works in getty container

blueprints/docker-for-mac.yml, pkg/trim-after-delete/Dockerfile, pkg/trim-after-delete/Makefile, pkg/trim-after-delete/README.md, pkg/trim-after-delete/main.go
Previously in Docker for Mac we run `fstrim /var` every 15 minutes from `cron` to reclaim space. If an image is deleted then it can take a long time for the space to be freed on the host. This PR adds a helper which watches for Docker events  and triggers an `fstrim` after an image delete. If a batch of image deletes happen within 10s (e.g. as part of a `docker system prune`) then only one `fstrim` will be issued.
Caused `fstrim /var` to be run after Docker images are deleted.
Added a new package `pkg/trim-after-delete` which contains the Docker event watcher and modified `blueprints/docker-for-mac.yml` to hook it up.
Viewing the log file `/var/log/trim-after-delete.log` from a `linuxkit run docker-for-mac`. Log lines are created …
=> RFC: add "trim after image delete" to the Docker for Mac blueprint

pkg/auditd/Dockerfile, pkg/auditd/Makefile, pkg/auditd/audit.rules, pkg/auditd/auditd.conf, pkg/auditd/runaudit.sh, tools/alpine/packages
Two things to note here: we unfortunately can't just exec audit, because it
dies if /var/log/audit doesn't exist, so we have to do a wrapper script.
Second, it also dies if it can't re-nice itself, so we have to give it
CAP_SYS_NICE as well as the audit caps.
I didn't add this to the default linuxkit.yml because the linuxkit/audit
repo doesn't exist yet, but we should probably (?) do that.
Closes #52
=> add an auditd container

pkg/auditd/Dockerfile, pkg/auditd/build.sh
Whoops :)
This file is referenced in the dockerfile, but i forgot to add it in the other PR.
=> auditd: add missing build.sh file

MAINTAINERS
Avi has been contributing to many areas of LinuxKit, including support
for containerised `getty`, encrypted swap and other areas.
=> Add Avi Deitcher as a maintainer

projects/miragesdk/src/fdd/.gitignore, projects/miragesdk/src/fdd/Dockerfile, projects/miragesdk/src/fdd/Makefile, projects/miragesdk/src/fdd/README.md, projects/miragesdk/src/fdd/common.ml, projects/miragesdk/src/fdd/common.mli, projects/miragesdk/src/fdd/fdd.ml, projects/miragesdk/src/fdd/fdd.opam, projects/miragesdk/src/fdd/init.ml, projects/miragesdk/src/fdd/init.mli, projects/miragesdk/src/fdd/jbuild, projects/miragesdk/src/fdd/share.ml, projects/miragesdk/src/fdd/share.mli, projects/miragesdk/src/fdd/test.ml, projects/miragesdk/src/fdd/test.mli
```
$ fdd init &
$ fdd share /tmp/foo # serve a fresh socketpair on that path
$ fdd test /tmp/foo  # read both sides of the socketpair and test that it works
```
Instead of `fdd test` (which is only useful for testing), users are expected to
connect to the unix domain socket and call `recvmsg(2)`. They will get one side
of the socketpair. Two different processes can do this and they will be able to
talk to each other.
=> sdk: add a file-descriptor sharing server

examples/docker.yml
bind /etc/docker/daemon.json so dockerd can read it
With following setting the dockerd is also listening on TCP:
files:
- path: etc/docker/daemon.json
contents: '{"debug": false, "hosts":["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"]}'
=> Bind /etc/docker/daemon.json in examples/docker.yml 

blueprints/docker-for-mac.yml, examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vpnkit-forwarder.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/etc/motd, pkg/getty/etc/profile.d/namespace.sh, pkg/getty/usr/bin/rungetty.sh, pkg/sshd/etc/motd, pkg/sshd/etc/profile.d/namespace.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
This PR fixes #2078 by implementing the suggestions from the discussion there
- Add a reminder in the MOTD
- Add a reminder in the $PS1
To do this I used `agetty` from `util-linux` instead of the provided busybox getty
Note: this will fail CI as I don't have signing permissions for getty
=> Make it more obvious that getty/sshd are namespaced

pkg/auditd/Makefile, pkg/binfmt/Makefile, pkg/ca-certificates/Makefile, pkg/containerd/Makefile, pkg/dhcpcd/Makefile, pkg/docker-ce/Makefile, pkg/format/Makefile, pkg/getty/Makefile, pkg/init/Makefile, pkg/metadata/Makefile, pkg/mkimage/Makefile, pkg/mount/Makefile, pkg/node_exporter/Makefile, pkg/open-vm-tools/Makefile, pkg/openntpd/Makefile, pkg/package.mk, pkg/qemu-ga/Makefile, pkg/rngd/Makefile, pkg/runc/Makefile, pkg/sshd/Makefile, pkg/swap/Makefile, pkg/sysctl/Makefile, pkg/sysfs/Makefile, pkg/trim-after-delete/Makefile, pkg/vpnkit-forwarder/Makefile, pkg/vsudd/Makefile
This commit moves the include statement to the bottom of the file to
ensure that all variables are set before conditionals are evaluated.
I also changed the ifndef NETWORK to ifdef NETWORK as the former was
incorrect. We want `NET_OPTS="--network=none"` in cases where NETWORK is
not defined.
Fixes: #2134
=> Makefile: Fix bug where network was not disabled

blueprints/README.md, blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/docker-17.06-ce.yml, test/cases/000_build/200_blueprints/010_docker_for_mac/test.sh
This splits the Docker for Mac blueprint into a base and docker image. This allows the base to be built and tested with different versions of Docker in the future.
Bonus updates:
- vsock port now same as in Docker for Mac (was 2375, now 2376)
- update containerd to the version missed in https://github.com/linuxkit/linuxkit/pull/2113
=> Split DfM blueprint in base and docker yml

blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/docker-17.06-ce.yml, pkg/vpnkit-expose-port/Dockerfile, pkg/vpnkit-expose-port/Makefile, pkg/vpnkit-expose-port/README.md, pkg/vpnkit-forwarder/Dockerfile, pkg/vpnkit-forwarder/README.md
Add support for forwarding swarm service ports to the host in the Docker for Mac blueprint. This should now work: 
`docker service create --publish 8080:80 nginx`
This PR adds a new package for binaries that are not part of the `pkg/vpnkit-forwarder` service called `pkg/vpnkit-expose-port`. The two binaries in this package are `vpnkit-expose-port` (userland proxy) and `vpnkit-iptables-wrapper` (iptables wrapper for swarm, new in this PR). 
These binaries have to be either copied into the dockerd container (e.g. in a multistage build) or bind-mounted into it by using `pkg/vpnkit-expose-port` as an init-container. I've updated `docker-for-mac.yml` to use it as an init-container, as we can then use a standard `docker-ce` package (yml hashes are currently temporary).
`docker-ce` already …
=> DfM: Add support for exposing swarm service ports

kernel/Makefile, pkg/Makefile, pkg/package.mk, tools/Makefile, tools/go-compile/Makefile, tools/qemu/Makefile
Various fixes/improvements to `pkg/package.mk`:
* Added a convenience target to print out the tag
* Simplified implementation of `-dirty` suffix and restricted it to only consider the package directory (same as for the hash itself)
* Consolidated the uses of `$(ORG)/$(IMAGE):$(HASH)`
* Fixed hash calculation for Jessie era git (loosely based on https://github.com/linuxkit/linuxkit/pull/2063#issuecomment-310465640)
Typing.
I used:
```
$ for pkg in init containerd ; do make -C pkg/$pkg --no-print-directory show-tag; ( cd pkg/$pkg && make show-tag ); done
linuxkit/init:36c56f0664d49c5a6adc1120d1bf5ba6ac30b389-dirty
linuxkit/init:36c56f0664d49c5a6adc1120d1bf5ba6ac30b389-dirty …
```
=> Fixes/improvements to `pkg/package.mk`

tools/mkimage-gcp/Dockerfile, tools/mkimage-gcp/Makefile, tools/mkimage-gcp/make-gcp
This was incorrectly removed in e782a469d522d473efbafee7b951dea4627136b7
=> tools: Bring back mkimage-gcp

Makefile
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>
Fixed ``make`` to work behind proxy.
Added ``env`` variable of ``http_proxy/https_proxy`` in ``docker run`` command
``make`` with proxy settings enabled on shell
- Now ``make`` works behind the proxy.
=> docker run works behind proxy too.

pkg/acpid/Dockerfile, pkg/acpid/Makefile, tools/alpine/packages, tools/alpine/versions
This adds a new service for running busybox's `acpid`. It needs `busybox-initscripts` for `/etc/acpi`, which contains the poweroff script. I've tested this with Docker for Mac and it successfully shuts down on power button events.
Alpine hash is temporary
=> Add pkg/acpid

docs/platform-hyperkit.md, test/cases/010_platforms/010_hyperkit/010_acpi/test.exp, test/cases/010_platforms/010_hyperkit/010_acpi/test.sh, test/cases/010_platforms/010_hyperkit/010_acpi/test.yml
- Add minimal acpi example
- Update hyperkit platform docs
I wasn't sure where to add the documentation for this as it is most likely similar for all platforms. I added it to hyperkit specifically though, as that's the platform I'm working on at the moment. 
This only adds a minimal example, but perhaps ACPI support should be included in more of the existing examples?
(see also previous discussion in #2154)
=> Add ACPI hyperkit test and update platform docs

pkg/package.mk, projects/swarmd/swarmd/Makefile
Firstly add option to disable content trust, for the use of e.g. projects which
are pushing to the linuxkitprojects org (which has no trust setup) rather than
the main linuxkit org.
Secondly, when trust _is_ enabled then enable it globally, in particular it is
now active for the `docker build` and hence containers referenced in
Dockerfiles via "FROM" will be checked.
Made it possible for individual packages to opt out of docker content trust. Use this for `projects/swarmd/swarmd`.
If `DOCKER_CONTENT_TRUST` is not already set in the environment then set it by default unless the package has opted out by setting `NOTRUST`, which I set in the swarmd package.
`make -C …
=> pkg: Update content trust handling.

blueprints/docker-for-mac/base.yml
- Adds the new ACPI service to the blueprint. This allows the VM to be shut down properly on power events (typically that the hyperkit process receives SIGTERM). (requires #2154)
- Adds the metadata package to use metadata configuration if available
=> Update Docker for Mac with ACPI and metadata support

projects/miragesdk/examples/https-unikernel/Dockerfile, projects/miragesdk/examples/https-unikernel/README.md, projects/miragesdk/examples/https-unikernel/opam, projects/miragesdk/examples/https-unikernel/src/common.ml, projects/miragesdk/examples/https-unikernel/src/http_server.ml, projects/miragesdk/examples/https-unikernel/src/jbuild, projects/miragesdk/examples/https-unikernel/src/main.ml, projects/miragesdk/examples/https-unikernel/src/store.ml, projects/miragesdk/examples/https-unikernel/src/tls_terminator.ml
Updated the `projects/miragesdk/examples/https-unikernel` example to use the latest library versions. This also avoids a build failure due to `irmin-watcher-0.2.0.tbz` having moved (reported by Nick Betteridge).
Follow the instructions in the example's `README.md` to build and run the example.
Update https-unikernel example to latest API.
=> Update https-unikernel example to latest API

blueprints/docker-for-mac/base.yml, pkg/host-timesync-daemon/Dockerfile, pkg/host-timesync-daemon/Makefile, pkg/host-timesync-daemon/README.md, pkg/host-timesync-daemon/main.go
Cause the Docker for Mac VM clock to be resynchronised when the host awakes from sleep.
Host-side code on Docker for Mac `connect`s to an `AF_VSOCK` socket (port `0xf3a4`) whenever it detects that the Mac has resumed from sleep. This connection is received by a daemon called `host-timesync-daemon` in the VM which reads `/dev/rtc0` and calls `settimeofday` (this requires `CAP_SYS_TIME`)
The first version of this code was originally written in C by @MagnusS -- I've ported it to Go in this PR.
- `moby build docker-for-mac.yml`
- `linuxkit run docker-for-mac`
- `tail -f /var/log/host-timesync-daemon.log `
- on the Host in the `blueprints` directory: `echo "00000003.0000f3a4" | nc -U ./docker-for-mac-state/connect `
- observe in the …
=> Add Docker for Mac host time sync daemon

docs/external-disk.md
Formatting was incorrect due to mismatched mark; also, it appears that
qemu also uses the state directory now for the created disk image. Also
used the same italicized style for param reference in text instead of
some bracketed and some italicized.
=> Fix markdown format mistake and text re: disk path

README.md
Add missing backtick (`)
Add missing backtick (\`) through github's editing features. This automatically forked it. Then I cloned it locally and checked out the patch-branch. Then did `git commit -s --amend`
A visual diff of the README.md should now show a 'better' README.md around the section of 
*Booting and Testing*
Fix formatting error in README.md
=> Fix formatting error in README.md

examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vpnkit-forwarder.yml, examples/vsudd.yml, examples/vultr.yml, linuxkit.yml
This means more users will see console output at boot time.
Remove page poison from example CLIs, we should document this
elsewhere and put in blueprints, but it is unnecessary in every example
=> Move ttyS0 after tty0 as it is more common

blueprints/docker-for-mac/base.yml
Hyperkit sets up PV entropy driver, so we do not need `rngd`
cc @MagnusS
=> Remove rngd from Mac blueprint

blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/docker-17.06-ce.yml
This mounts the disk image in /var/lib (instead of /var/lib/docker) and
moves the logs to /var/lib/log. This is a temporary solution to have the
logs on disk until we have a better solution in place.
Bonus: remove double bind of the vpnkit port
=> dfm: Move logs from memory to disk

src/cmd/linuxkit/push_vcenter.go, src/cmd/linuxkit/run_vcenter.go
- Added the parameter `datacenter` for the vCenter backend
- **(looking for feedback on that one)** Deleted the `checkFile` and `uploadFile` step when using the `run` command
By using the govmomi function [DatacenterOrDefault](https://github.com/vmware/govmomi/blob/master/find/finder.go#L384) instead of DefaultDatacenter.
- requirement: have vCenter with multiple datacenters
Upload the Linuxkit image to vCenter:
```
linuxkit push vcenter -datastore <your_vsphere_datastore> -hostname <your_vsphere_host> -network "<your_vsphere_network>" -url "https://<your_vsphere_username>:<your_vsphere_password>@<your_vsphere_server>/sdk" -datacenter "<your_vsphere_datacenter>" -folder <your_vsphere_folder_in_datastore> …
```
=> Backend vCenter: add the datacenter parameter

kernel/Dockerfile
The original kernel Dockerfile hardcodes the amd64 as the
only arch supported, this patch removes this kind of hardcode
and make the Dockerfile is ready to support both amd64 and
arm64 by using the runtime arch type.
Remove the hardcode of x86
Get the info of the ARCH through runtime 'uname -m' command
Build the kernel docker image on both arm64 and amd64 platform, then add this component into linuxkit.yml, run 'bin/moby build linuxkit.yml' 'bin/linuxkit run linuxkit'. you got it!
=> ARM64: Adapt the kernel Dockerfile to multiarch support

examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vultr.yml, pkg/getty/README.md, pkg/getty/usr/bin/rungetty.sh
Changed `pkg/getty` as follows:
* Instead of _modifying_ `/etc/securetty` to match `console=` lines, _read_ `/etc/securetty` to determine if a getty can be started for a given tty device
* If a console tty device does *not* exist in `/etc/securetty`, refuse to start a `getty` on that terminal, and report an error message
* Override default in-container `/etc/securetty` with file from rootfs, similar to `/etc/getty.shadow`
Typing. :-)
Try the following scenarios:
1. Build with securetty matching console, see getty is available
2. Build with securetty *not* matching console, see error message and getty is not available 
Use existing tty to determine …
=> Use existing securetty

tools/alpine/Dockerfile
We should use this from a container at top level instead; it makes it
much harder to port to other architectures if we have to have this as
it is written in Haskell making a multi arch build much harder.
=> Remove shellcheck from base

reports/sig-security/2017-07-19.md
Exciting WireGuard deep-dive planned from @zx2c4 (let me know if you'd like a different/modified description in the agenda).  I'll follow up with emails/forum posts once we finalize this.
=> sig-security: add preliminary agenda for 2017-07-19

src/cmd/linuxkit/run_qemu.go
This commit fixes an issue reported on Slack where `linuxkit run` will
assume that a file that is neither a kernel or iso must be a disk image
without first checking that it exists. This would result in `qemu-img`
attempting to create a disk with 0 size due to the default behaviour of
creating disk images that do not exist.
Before:
```
$ linuxkit -v run qemu foo
DEBU[0000] Creating new qemu disk [foo] format
DEBU[0000] [/usr/local/bin/qemu-img create -f  foo 0M]
FATA[0000] Error creating disk [foo] format :  exit status 1
```
After:
```
$ linuxkit -v run qemu foo
FATA[0000] foo is not a valid disk image
```
=> linuxkit: Fix qemu run behaviour when file does not exist

src/cmd/linuxkit/run_qemu.go
Current implementation uses a fixed firmware(bios) binary
installed by the build process of the qemu container image,
which will prevent us from providing an external firmware binary
outside the container. This patch removes this limitation, thus we
can assign a firware binary image file with "-fw" option outside
the container.
Remove the original limitation when boot the kernel image in UEFI mode.
Add '-v' option when running qemu container to pass the external firmware bin into the container.
Run below command in both x86 and arm64 platform:
'bin/linuxkit run qemu -containerized -fw "/home/arch/bios.bin" -uefi linuxkit
The kernel image will boot to shell successfully.
Without this …
=> ARM64: specify external firware binary for containerized qemu

tools/alpine/Dockerfile, tools/alpine/Makefile, tools/alpine/versions
Two things:
* Kept a copy of the original (upstream Alpine) `/etc/apk/repositories`. This will be useful in dependent containers which want to include a working `apk` configuration by avoiding the need to include alpine version numbers there
* Record the hash of the pushed alpine bash container, currently this relies on the committer remembering to include it in the commit message. `tools/alpine` now supports the `show-tag` target like `pkg/package.mk` based builds do.
Note that nothing here is updated to use the new alpine hash.
Note2 I had planned to use the first change to add `apk` to the `getty` and `sshd` containers but ran into a blocker, see #2206.
Updated the `Dockerfile` and `Makefile`
This should validate both of my …
=> Small alpine mirror improvements

test/cases/020_kernel/000_config_4.4.x/test-kernel-config.yml, test/cases/020_kernel/001_config_4.9.x/test-kernel-config.yml, test/cases/020_kernel/003_config_4.11.x/test-kernel-config.yml, test/hack/test.yml, test/pkg/kernel-config/check-kernel-config.sh
Do not assume that these are modules in all kernels.
You can now run it with `docker run linuxkit/test-kernel-config:7e8bcae3e661f5b48c00cf2f15bbef19b35fac76` on any docker host to see if the test passes.
=> Allow config test modprobe to fail

Makefile, blueprints/README.md, blueprints/lcow.yml, pkg/init-lcow/Dockerfile, pkg/init-lcow/Makefile, src/cmd/linuxkit/run_qemu.go, tools/alpine/Dockerfile, tools/alpine/Makefile, tools/alpine/versions
A previous commit already added the kernel support (hopefully) necessary for LCOW (Linux Containers for Windows). This PR adds a new init container based on https://github.com/Microsoft/opengcs/blob/master/docs/customosbuildinstructions.md and a blueprint to create a kernel+initrd.
We currently can't test if this actually works...
=> Add experimental support for LCOW

examples/docker.yml
fix that docker.yml wasn't working correctly
add the configs to make directory before docker container running.
1. build original docker.yml, and run it. ensure that 
I wanted to try moby and linuxkit, so I downloaded example/docker.yml, built it, and ran it with linuxkit.
but I can't execure /bin/sh on docker in my environment. I looked for the cause, so I found following logs.
```
FATA[0000] failed to create task                         error="rpc error: code = Unknown desc = runtime create failed: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/docker\\\\\\\" to …
```
=> fix that docker.yml wasn't working correctly

tools/go-compile/Makefile, tools/qemu/Makefile
tools/qemu and toos/go-compile define the IMAGE after the
package.mk, which result in below error if 'make ORG=other_org':
...
invalid argument "other_org/:2c6d9e1d9c52167f4f2b7a8fd235eda318175c99"for t: invalid reference format
See 'docker build --help'.
../../pkg/package.mk:47: recipe for target 'tag' failed
make: *** [tag] Error 125
This because '../../pkg/package.mk' need to use IMAGE variable first.
Fix the Makefile issue for some tools
Change the order sequence in the Make to meet the usage requirement
Under, for instance, the tools/qemu:
make ORG=other_org
=> tools: Fix the order sequence issue in Makefile

tools/qemu/Dockerfile
Update the qemu Dockerfile to support both amd64 and arm64.
Change the qemu Dockerfile to support multi-arch(currently amd64 and arm64). We prefer the 'case' to 'if...else...' given the possible other architecture support in the future.
Take different action according to the ARCH type abstracted by runtime $(uname -m)
'docker build' this file on both amd64 and arm64 platform, then 'docker run... /bin/ash' the built image, in the shell, to check if the qemu-system-ARCH has been installed correctly and the 'bios.bin' for amd64 is in the correct place. 
=> ARM64: Multi-arch support in qemu Dockerfile

docs/kernels.md
Updated the kernel build doc to describe:
* Difference between building external modules vs in-tree modules and options
* How to build based on a modified config
* How and when to use `menuconfig` vs direct editing
* How to get a ready-to-build-kernel environment
Slack with @justincormack and @rn and then typed it all up!
Read the docs. If they make sense, it works.
Update kernel build docs with more detail on building modules and the kernel.
=> Update kernel build docs

test/cases/040_packages/007_getty-containerd/test.exp
It is a far smaller download. Also pin to a specific version to protect against
the possibility of the output string changing.
The new image name is a bit of a mouthful, put it (and the expected output)
into a variable.
Lets assume this fixes #2229 until shown otherwise.
=> Use hello-world instead of redis for getty test

Makefile, linuxkit.yml
Add the yaml config to the default `linuxkit.yml`. You can check
this with `cat /proc/1/root/etc/linuxkit-config`.
=> Update moby to support metadata

Makefile
This update brings in linuxkit/rtf#24 that fixes panics in cases where
there are concurrent reads/writes of the logging backends.
=> Makefile: Update rtf version

blueprints/docker-for-mac/base.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/etc/init.d/001-getty, pkg/getty/usr/bin/rungetty.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
1. Add `INITGETTY=true` env var when running from `/etc/init.d/001-getty`
2. Only `wait` in `rungetty` if `INITGETTY` is true
`wait` was causing onboot to block. See [this](https://github.com/linuxkit/linuxkit/pull/2233#discussion_r127970030)
Typed
Run in `services` and in `init`. Ensure everything starts when in `init`.
Remove block of `init` when getty is in `init` mode.
No, a squid is _not_ cute, but it is the first animal that came to mind.
=> flag in init and background only if not in init

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
This temporarily uses my dev branch of opengcs, which contains various fixes to the networking setup.
It also moves runc back into the YAML file now that the hard coded path has been removed from opengcs
=> Fix networking in LCOW

Makefile, docs/vendoring.md, tools/go-compile/Dockerfile
I noticed that running the runes in docs/vendoring.md made a bunch of files
which are omitted by modern vndr come back, presumably due to the old version
of vndr referenced there. So update the go-compile package to the current
version everywhere.
Also correct the use of `make` variable syntax (`$(PWD)`) where shell syntax
command substitution for `pwd` was desired.
=> Update to latest alpine base for go-compile

reports/sig-security/2017-07-19.md
Thanks to Jason Donenfeld for the correction.
=> correct the calculation of wireguard header overhead

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/vultr.yml, pkg/metadata/main.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/swarmd/swarmd.yml
I prevented large chunks of configuration .json (some of which could be secret) from being logged to the console.
I suppressed printing the .json value when there is no `perm` or `content` attribute i.e. when the node is a directory.
Using configuration .json like:
```json
{
"etc": {
"ssl": {
"certs": {
"ca-certificates.crt": {
"perm": "0644",
"content": "large amount of certificate text"
}
}
}
}
}
```
Without this patch, I see on the console:
```
2017/07/20 10:03:04 CDROM: Probe succeeded
2017/07/20 10:03:04 No permission provided ssl:map[certs:map[ca-certificates.crt:map[perm:0644 content:large amount of certificate text]]]
- 000-metadata
```
With this patch, I see on the console:
```
2017/07/20 09:54:18 CDROM: Probe succeeded …
```
=> metadata: avoid printing large chunks of configuration json to the console

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vpnkit-forwarder.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/Dockerfile, pkg/sshd/Dockerfile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/okernel/examples/okernel_simple.yaml, projects/shiftfs/shiftfs.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
Made it possible to run `apk` commands (such as `apk add`) in the `getty` and `sshd` containers
Fixes #2206.
Added `apk-tools` to both images, used 00a2f2ac8caca2b10f0b61bfe0116892c5f2687d to provide an appropriate repositories config and stopped nuking the apk state.
I also dropped the bind mount of `/var` from both packages. Quoting the relevant bit of commit message:
>    Doing this requires that we not share `/var` with the login containers since we
>    want the apk database therein. Previously it was thought that the containers
>    might need some parts of `/var` for `ctr` to work (e.g. `/var/lib/containerd`)
>    but this is not the case now (if it ever was) based on my testing.
Although not strictly necessary, bumped the version of alpine base …
=> Add apk to login (sshd & getty) containers

README.md, docs/platform-openstack.md, src/cmd/linuxkit/push.go, src/cmd/linuxkit/push_openstack.go
Added the capability to do a `linuxkit push` to OpenStack, with the following capabilities:
- Password support
- Project support (multi tenancy)
- Multi image format support
- Support for separate keystone and glance servers (in the event the services are separated out)
- Domain support (defaults to `"Default"`)
Took the OpenStack APIs and wrapped them into an `openstack` backend, that supports password based authentication and `openstack` projects.
Push an image to OpenStack and check that it appears under the images, and also part of the correct project. [Tested on Ocata release]
```
./linuxkit push openstack -keystoneAddr=http://devstack.fnnrn.me:5000 \
-username=admin \ …
```
=> OpenStack Push support

docs/wireguard.md, tools/alpine/Dockerfile
As discussed with @rn, wireguard-tools should be a package available from tools/alpine. Then, it can be included in sshd and getty, since it's on the same level as iproute2, and wireguard is going to be an essential feature of linuxkit, so it's important for folks to get acquainted with it.
This PR takes the first step of making it into a package.
From @rn, it works:
```
make ORG=rneugeba  tag
docker run --rm -ti rneugeba/alpine:5ca5d83ef72f74bdc2a7b96bc17d58031a42306d /bin/sh
/ # apk search wireguard
wireguard-tools-0.0.20170629-r0
```
=> wireguard: add tools to alpine as package not into filesystem

examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vpnkit-forwarder.yml, examples/vultr.yml, pkg/getty/Dockerfile, pkg/sshd/Dockerfile
WireGuard is on the same level as iproute2, which is also in sshd and getty. If WireGuard is going to become an important component of LinuxKit, it should be available for people to play with in these containers. Adding the tools adds hardly any increase and size, and will make developing LinuxKit+WireGuard considerably smoother. This is also needed to use these in reproducable/networkless configurations, since /mirrors is not available after boot.
Suggested by @rn and @justincormack.
=> Add wireguard to sshd and getty

projects/swarmd/swarmd.yml, projects/swarmd/swarmd/Dockerfile
Refreshed the getty, weave and swarmd packages in projects/swarmd to current versions. In particular the swarmd package is now up to date with containerd v1.0.0-alpha1.
emacs again.
Run the swarmd project.
swarmd project has been updated to be compatible with containerd v1.0.0-alpha1
[![](https://f4.bcbits.com/img/a2993129801_2.jpg "Corsair, Corsair")](https://shadowkingdomrecords.bandcamp.com/album/corsair)
=> swarmd: refresh versions

tools/alpine/packages, tools/alpine/versions
Added the following packages to `linuxkit/alpine` local mirror:
* autoconf
* gettext
* gettext-dev
* libtool
* openssl-dev
As discussed in Slack with @rn 
1. Added packages to `packages`
2. Ran `make` to build and saved versions
3. Commited
4. Pushed
5. Opened this PR
Run the image. See that `apk add` works with those packages.
Add 5 development packages to alpine mirror
=> Add development tools to linuxkit/alpine mirror

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, examples/vpnkit-forwarder.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/Dockerfile, pkg/sshd/Dockerfile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
Mounted `/var/log` back into getty and sshd containers
Closes #2269 for @ijc 
Added to the labels
1. Run it
2. See `/var/log`
Return mount for `/var/log` to getty and sshd containers
=> Mount /var/log to getty and ssh again

test/cases/020_kernel/000_config_4.4.x/test-kernel-config.yml, test/cases/020_kernel/001_config_4.9.x/test-kernel-config.yml, test/cases/020_kernel/003_config_4.11.x/test-kernel-config.yml, test/pkg/kernel-config/check-kernel-config.sh
This is what CONFIG_DEBUG_SET_MODULE_RONX was renamed to; since we want
that one, presumably we want this one too.
=> check-kernel-config: check for STRICT_MODULE_RWX too

tools/alpine/Dockerfile, tools/alpine/Makefile
This was added in 17.06 and allows us to avoid using `$(BASE):build` which is
not safe against parallel builds etc.
Having done this restructure the build to not always delete the built container
and to separate out the `hash` and `version` file rules so that they can be
included in both the `tag` and `push` targets.
This carries a change from https://github.com/linuxkit/linuxkit/pull/2258 which was dropped from there due to being off-topic.
See above.
Used `docker build --no-cache --iidfile iid .` to build an `iid` file (which will contain `sha256:[0-9a-f]{64}`) and refactored the `hash` and `versions` generation into dedicated targets depending on that. Updated everything using `$(IMAGE):build` to use …
=> alpine: Use `docker build --iidfile`

tools/alpine/versions.aarch64
This updates the alpine base for arm64 to an image hash which is actually pushed to hub.
/cc @arm64b
=> tools/alpine: Update arm64 base image

scripts/update-component-sha.sh
Added a script that updates all instances of an image with a given tag. The existing script replaces tag `<OLD>` with `<NEW>`. This changes the hash for any occurrence of `<IMAGE>` to `<NEW>`, no matter what the old one was.
Existing is fine, but often I find the need to just "change them all."
Typing.
Run it, see the changes.
Script to support changing tag for all occurrences of an image.
=> Add script to update tag for all image matches

scripts/update-component-sha.sh
Removed a bashism from [update-component-sha.sh](./scripts/update-component-sha.sh) per https://github.com/linuxkit/linuxkit/issues/2284#issuecomment-317685142 
Removed the duplicate word `function`
Run it in different modes.
Remove bashism from script.
=> Remove bashism in script

tools/alpine/versions.x86_64
Somewhere between the various updates yesterday the hash in
'versions.x86_64' went wrong and there is no image with hash
available on hub.
This commit updates the alpine base to the latest version and
thus rectifies the issue
=> tools/alpine: Resync alpine base image

tools/alpine/Makefile, tools/alpine/versions.aarch64
We should always pull and push linuxkit/alpine with content trust
irrespective of architecture, unless explicitly disabled.
Currently, we have to dance around various other issues on arm64,
which are now documented in the Makefile.
=> tools/alpine: Make sure we use content trust for linuxkit/alpine

kernel/Dockerfile
Simple version bump. Release notes [from the mailing list](https://lists.zx2c4.com/pipermail/wireguard/2017-July/001580.html):
-----
* global: wireguard.io --> wireguard.com
We have a new domain name -- WireGuard.com -- moving away from the .io, due to
security concerns. Along with the new domain, we also have a commonly
requested page for donations: https://www.wireguard.com/donations/ in addition
to a Patreon page for those who are into that: https://www.patreon.com/zx2c4 .
* ratelimiter: consistently use non-bh rcu
* socket: style
* wg-quick: usage typos
* qemu: update default testing kernel
* qemu: warn on all unseeded random usage when in debug mode
* compat: work around odd kernels that backport kvfree
* selftests: ensure that there isnt CPU lag when testing rate limiter
The usual …
=> wireguard: version bump

pkg/package.mk
This is like the `push` target but omits the pulls and depends on forcetag
instead. With the git commit now being embedded into the image this is now a
necessary part of rebasing a PR for which images have already been pushed.
Also adds PHONY targets for existing forcetag and push targets which were
missing.
NB $(error) appends a "." to omit the final one from the error message
=> pkg: Add forcepush target

projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/kubernetes/kubernetes/Dockerfile
After #2289 we need to bind /etc/resolv.conf into the docker and kubelet
containers on both node and master.
Also since #2289 the metadata container requires /etc/resolv.conf to be
populated on the host, which means running DHCP earlier in oneshot onboot mode,
do so.
=> kubernetes: provide /etc/resolv.conf to kube and docker containers.

src/cmd/linuxkit/run_qemu.go, tools/alpine/Dockerfile, tools/alpine/packages.x86_64, tools/alpine/versions.x86_64, tools/qemu/Dockerfile
- Add the `ovmf` package to the mirror instead of installing it to the `linuxkit/alpine` rootfs. This has the added benefit of the version of the package being recorded.
- Install the `ovmf` package in `tools/qemu`.
- Update the `linuxkit run qemu` code to use the new image
- While working on this, I also noticed that, when run in containerised mode, we would always bind mount the FW into the container. Clearly we'd want to use the FW in the container by default. Now, it only bind mounts the FW if the location specified via `-fw` is not the default.
Note that when run on Docker for Mac in containerised mode qemu currently segfaults when using the efi boot. I doubt this is a regression introduced by theses changes and the EFI image boots fine on Hyper-V.
=> Various OVMF related fixes

blueprints/docker-for-mac/base.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/etc/profile.d/namespace.sh, pkg/getty/usr/bin/rungetty.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/memorizer/memorizer.yml, projects/miragesdk/examples/fdd.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, projects/swarmd/swarmd.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
This is an attempt at fixing #2213
If pid 1 isn't /sbin/init we're in a container
If we can see `containerd|runc` in the `pstree` then we're in the host
pid namespace but still in a container.
Otherwise, we're not in a namespace.
I"ve tested this with getty on `init`, in `services` with both a `host`
and `new` pid namespace and it seems to work as expected.
=> getty: Detect if you are in a namespace

examples/docker.yml, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml
Signed-off-by: Matt Bentley <matt.bentley@docker.com>
Changed command for docker to run and added a bind mount for resolv.conf because DNS is great - remembering all of those IPs is really hard.  Fixed for both the docker example and the static & dynamic compose project examples
vim :)
moby build foo.yml
linuxkit run foo
Updated commands as the path for docker changed and added resolv.conf to bind mounts
=> Fixed commands and resolv.conf in docker example

pkg/package.mk
Current package.mk will operate on the first dependence object
'check-dirty', which result in the make process abort earlier
with below message:
pkg/package.mk:60: *** Your repository is not clean. Will not push package image.  Stop.
This is not expected behavior since we have no chance to build
a docker image locally in case of the user has no intention to
push that image.
This patch adjust the dependece order for the those targets, thus
we can build the docker image locally but can't push that image
if we're in a dirty git repository.
make the docker image build can succeed locally but the image can't be pushed for reason of dirty git repository 
change the dependence order for the target: build first, …
=> package.mk: Adjust the targe sequence to avoid early abort

pkg/getty/etc/securetty
We need to add 'ttyAMA0' console used on ARM64 platform into
securetty file to make it's possible to log into the system
as root. Also it will dismiss the below warning message before
login:
"getty: cmdline has console=ttyAMA0 but does not exist in
/etc/securetty; will not be able to log in as root on this tty ttyAMA0."
Dismiss the console warning message before login.
Add the 'ttyAMA0' used on ARM64 into /etc/securetty
The warning message is disappeared after this patch applied. 
=> pkg/getty: Add ARM 'ttyAMA0' console into securetty

docs/platform-azure.md
The document showed the incorrect sub-command options for LinuxKit run azure  which needs to be updated and hence fixed it.
Modified the incorrect Linuxkit run command for Azure.
linuxkit run azure -resourceGroupName <resource-group-name> -accountName <storage-account-name> -location westeurope <path-to-your-azure.vhd>
$git clone https://github.com/linuxkit/linuxkit
$cd linuxkit
$make
$cp -rf bin/moby /usr/local/bin/
$cp -rf bin/linuxkit /usr/local/bin/
$cd linuxkit/examples/azure
$moby build -o vhd azure.yml
$ linuxkit run azure --resourceGroupName mylinuxkitresource --accountName mylinuxkitstorage -location eastasia azure.vhd
=> Updated document with the right LinuxKit command for pushing VHD to Azure Platform

Makefile, tools/alpine/Makefile, tools/alpine/push-manifest.sh, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
- Add a modified version of the `manifest-tool` to the top-level Makefile
- Append `-amd64` and `-arm64` to the architecture specific base images
- After pushing the image use `push-manifest.sh`, which:
- Extracts the current hashes from the `version.*` files
- Creates a `manifest-tool` YAML file
- Push the manifest list to hub using the hash of the `x86_64` images (without the `-amd64`)
- Sign the manifest using `notary`
- Note, the build requires a modified version of `manifest-tool` and `jq` to be installed. On macOS it also requires the `docker-credential-osxkeychain.bin` which is installed with Docker for Mac, and on Linux it requires `base64` (though that is currently not used).
There now is signed a multi-arch image on hub as: …
=> Create a multi-arch alpine base image

projects/kubernetes/image-cache/Dockerfile, projects/kubernetes/image-cache/Makefile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/kubernetes/kubernetes/Dockerfile
- Updated `getty` and `sshd` which were lagging.
- Fixes up some fallout from the switch to a `tmpfs` on `/var` and in particular the change to `/var/run` being a symlink to `/run`.
- Updated to Kube 1.7.2
- Reintroduced k8s-dns images in the cache, since they are now used.
Emacs
I like the sock shop demo for this.
Kubernetes project is now based on Kube 1.7.2.
[![](https://upload.wikimedia.org/wikipedia/en/d/d3/Leprous_Congregation_Cover.jpg "Leprous, The Congregation")](https://en.wikipedia.org/wiki/The_Congregation_(Leprous_album))
=> projects/kubernetes: fixup and bump to kube 1.7.2

Makefile, tools/mkimage-iso-bios/make-iso
Now that LinuxKit works on a truly immutable filesystem, for an
ISO it makes sense to use the ISO filesystem rather than using
an initrd. Only major difference is you may need to specify the
device for the root filesystem in the kernel command line, but
we set a sane default of `/dev/sr0` if unspecified.
=> Unpack filesystem for BIOS ISO

src/cmd/linuxkit/run.go, src/cmd/linuxkit/run_openstack.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/doc.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/urls.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/doc.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/requests.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/results.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/urls.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/errors.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/urls.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/util.go
Signed-off-by: Nick Jones <nick@dischord.org>
Added basic support for launching instances on an OpenStack platform.
Made use of the Gophercloud library in order to handle creating an instance with a set of options such as flavor and which network to attach the virtual machine to.
As an example:
```shell
linuxkit run openstack \
-authurl https://compute.datacentred.io:5000/v3 \
-username "username" \
-password "xxx" \
-project "default" \
-network c5d02c5f-c625-4539-8aed-1dab3aa85a0a \
-name LinuxKitTest
```
Or it'll inherit a standard set of [OpenStack client environment variables](https://docs.openstack.org/mitaka/install-guide-obs/keystone-openrc.html) for these options, simplifying the command to something such as:
```shell …
```
=> Initial support for launching instances on OpenStack

src/cmd/linuxkit/run_qemu.go, test/cases/040_packages/003_containerd/test.sh, test/cases/040_packages/007_getty-containerd/test.sh
Made it so qemu stores pidfile within state directory the same way hyperkit does
* Unconditionally create state directory as its required no matter what for our pidfile
* pass `-pidfile $STATE_DIR/qemu.pid` to qemu to create pid file
`./bin/linuxkit run linuxkit` (or any image) and `cat linuxkit-state/qemu.pid` (replace linuxkit-state if you specified `-state` to linuxkit)
Save qemu pid to file within state directory
=> save qemu pid in state directory

docs/platform-openstack.md, src/cmd/linuxkit/push_openstack.go, src/cmd/linuxkit/run_openstack.go
* Update `push` support to inherit relevant environment information, where available;
* Change `run` support so that it's consistent with other providers, notably GCP and AWS.  It now takes the name of the image as the first argument without requiring much else;
* Update documentation to cover support for new features and changed options.
Workflow now looks like:
```shell
$ bin/linuxkit push openstack -img-name "LinuxKitImage" ~/Desktop/linuxkitmage.qcow2 
Uploading file /Users/nick/Desktop/linuxkitmage.qcow2 with Image ID c5b4d9e8-38fb-4728-bc66-c9670201aac7
Image uploaded successfully!
$ bin/linuxkit run openstack -network c5d02c5f-c625-4539-8aed-1dab3aa85a0a -flavor dc1.1x1 LinuxKitImage
Server created, UUID is …
```
=> [OpenStack] Inherit env vars for push, and make run more consistent with other providers

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/vultr.yml, pkg/metadata/Dockerfile, pkg/metadata/main.go, pkg/metadata/provider_cdrom.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/swarmd/swarmd.yml
This checks if any CDROM in the system has metadata. Useful if
you boot off CDROM and also have a metadata CDROM.
Also switch the metadata container to read only, as it is only
writing to bind mounted in directories, and /tmp.
=> Support multiple CDROMS in metadata

examples/docker.yml, linuxkit.yml, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/shiftfs/shiftfs.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
It is not in any wa=y a required container, and now that arm64
and other architecture machines are widely available we should
start to deprecate it, as it has many issues, eg requires patches
to qemu for Go support, will mislabel images etc.
=> Remove binfmt from most examples

src/cmd/linuxkit/push_aws.go
The AWS push cannot work on machines with little amount of RAM (i.e. 4GB) if you want to push a 1GB image. We (me and @pyaillet) replaced the loading of image with only using file information. 
Replaced ioutil.readAll with file Stat
Push a 1GB image in a machine with 4GB of RAM or less.
Reduce amount of RAM used by AWS push
**- And of course, a picture of a cute animal**
=> Fix AWS push

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/packet.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/sysctl/etc/sysctl.d/00-linuxkit.conf, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/miragesdk/examples/fdd.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/okernel/examples/okernel_simple.yaml, projects/shiftfs/shiftfs.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/040_packages/003_containerd/test-containerd.yml, test/cases/040_packages/019_sysctl/test-sysctl.yml
This requires that users have `CAP_SYSLOG` in order to access `dmesg`.
This means that containers by default have no access to `dmesg` (which
can leak information about the host or other containers) unless they
have this capability added.
=> Enable sysctl kernel.dmesg_restrict

examples/docker.yml, examples/getty.yml, examples/minimal.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, linuxkit.yml, src/cmd/linuxkit/run_qemu.go
- When executing on aarch64, use it as the defaul arch
- When selecting aarch64 on a non aarch64 system set the
CPU flag to a default value (not 'host').
- On aarch64, rewrite ttyS0 to ttyAMA0. This is a bit skanky
but allows us to re-use execiting YAML files.
Can now boot a arm64 kernel on my mac with:
```
linuxkit run qemu -arch aarch64 linuxkit
```
=> cmd/qemu: Better handling of arch and console for aarch64

Makefile, blueprints/lcow.yml, docs/packages.md, pkg/init-lcow/Dockerfile
- PR to manifest-tool to get the length for notary has been merged. Use official version now and update docs that `go get` now also works
- Update `opengcs` to latest and then update the LCOW blueprint
=> Update to tip of manifest-tool and opengcs/LCOW

src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/run_gcp.go, src/cmd/linuxkit/util.go
This commit allows the GCP backend to use the familiar `-disk` behaviour
that the local hypervisors use. The `file` attribute is used as the disk
name in GCP. The size is converted to GB and is always > 1GB.
This has the benefit of allowing multiple disks to be used with GCP
instances.
=> linuxkit: Better GCP disk handling

scripts/cleanup-older-images.sh
Added a script to `./scripts/` that will clean up all images that start with a particular name (namespace, part of namespace, namespace+repo, namespace+part of repo all valid) and how many recent versions to keep.
Per discussion on slack channel with @rn might be useful here.
E.g.
```
./scripts/cleanup-older-images.sh linuxkit/ 3
```
Will remove all images starting with `linuxkit/` except for the 3 most recent of each full repo name.
It sort of is `system prune -a` except that it adds:
* ability to limit to a particular set of images by namespace, namespace+repo, or part
* ability to keep a certain number of most recent
shell script wrapping docker, awk, etc. And, yes, no bash :-) . …
=> Add script to clean up older images

Makefile, tools/mkimage-iso-efi/make-efi
In line with BIOS ISO changes previously.
Remove boot options, user can add if required, they made boot very slow.
=> Put full filesystem on EFI ISO

blueprints/docker-for-mac/base.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/getty/usr/bin/rungetty.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/memorizer/memorizer.yml, projects/miragesdk/examples/fdd.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, projects/swarmd/swarmd.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
test that a given tty is a character device before trying to open getty on it.
Closes #2362 
```sh
if [ ! -c /dev/$tty ]; then
echo "getty: cmdline has console=$tty but /dev/$tty is not a character device; not starting getty for $tty" | tee /dev/console
return
fi
```
Run it with a mixture of `console=` options that are and are not character devices and see that:
1. It starts for all char devices
2. It does _not_ start for missing or non-char devices
3. It puts an error message on console and in the log file that it is not starting it for that tty
Only start getty for valid char-device ttys
=> Test dev existence getty

projects/kubernetes/Makefile, projects/kubernetes/boot.sh
Because Kubernetes is 1.5GB, ISO makes sense as the files do not take up memory, so you can boot a 1GB machine rather than a 4GB one.
Also cherry pick a patch of Ian's, and de-bashify the script.
=> Use ISO for kubernetes

src/cmd/linuxkit/run_aws.go
Instances were being created in a different AZ to the one specified in
the zone variable. This could lead to situations where the disks and the
instance were in different AZs and would result in an error.
This commit adds placement information to the API call used to create
the instance.
Fixes: #2388
=> aws: Honour the zone variable when creating an instance

src/cmd/linuxkit/run_aws.go
When an AWS machine is stopped and there is no console output the CLI
panics due to a nil pointer dereference. This commit checks that the
console output is not null before attempting to decode it.
Fixes: #2389
=> aws: Fix panic when there is no console output

Makefile
=> Update moby commit

docs/platform-packet.md, log.txt, src/cmd/linuxkit/run_packet.go
Boots uncompressed kernels/initrds.
Networking is not working yet due to missing driver and tty spews out:
```
[  267.047741] ttyS ttyS0: tty_port_close_start: tty->count = 1 port count = 2
```
every ten seconds.
=> iPXE boot of arm64 on packet.net

src/cmd/linuxkit/run_qemu.go
Currently we depend on the qemu to detect the firmware file format
automatically, which is dangerous. This patch specify the 'raw'
format explicitly to remove the kind of restrictions.
specify the firmware file format explicitly
Using the qemu command line "-drive if=pflash,format=raw,file=/usr/share/ovmf/OVMF.fd" instead of "-pflash file=" 
After the patch applied, below warning message will be removed:
WARNING: Image format was not specified for '/usr/share/ovmf/OVMF.fd' and probing guessed raw.
Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
Specify the 'raw' format explicitly to remove the restrictions.
**- …
=> qemu: Specify the firmware file format explicitly

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/vultr.yml, pkg/metadata/main.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/swarmd/swarmd.yml
run with `cmd: ["metadata", "aws"]` to just check for AWS metadata for example.
=> Allow specifying a set of metadata providers

src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/packethost/packngo/devices.go, src/cmd/linuxkit/vendor/github.com/packethost/packngo/ip.go
The local changes were merged, so switching back to the original
repository. A minor change in API was needed.
=> cmd: Use the main packet.net API repo again

projects/kubernetes/image-cache/Makefile, projects/kubernetes/image-cache/Makefile.pkg, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/kubernetes/kubernetes/Dockerfile, projects/kubernetes/kubernetes/Makefile
- fix persistence/writeability of CNI paths, as the were bound to read only paths
- use standard LinuxKit base image now it has all the requirements
- update Weave yaml to k8s 1.7.x
- only build on amd64 - there are no prebuild arm64 images yet
- upgrade to 1.7.4
=> Kubernetes improvements

pkg/init/Dockerfile
Fixed the `metadata` package (as used by the `blueprints/docker-for-mac` example)
I ensured the directory `/etc/ssl/certs` exists by creating it in the `init` package. The [Dockerfile](https://github.com/linuxkit/linuxkit/blob/498d5a1966fdf5f03908cf96c39df9390ebc8c85/pkg/metadata/Dockerfile#L18) of the `metadata` package contains a `bind` for `/etc/ssl/certs`
Run the commands:
```
cd blueprints/docker-for-mac
moby build -name docker-for-mac base.yml docker-17.06-ce.yml
linuxkit run hyperkit -networking=vpnkit -vsock-ports=2376 -disk size=500M docker-for-mac
```
Without this fix the console will have an error:
```
Welcome to LinuxKit
/"""""""""""""""""\___/ ===
{                       /  ===-
\______ O           __/
\    \ …
```
=> init: mkdir /etc/ssl/certs as required by the metadata package

examples/wireguard.yml, pkg/ip/Dockerfile, test/cases/040_packages/023_wireguard/check.sh, test/cases/040_packages/023_wireguard/test-wireguard.yml, test/cases/040_packages/023_wireguard/test.sh
- fix version mismatch with current kernel
- change test to create two connected wireguard interfaces, one running nginx and one in the getty, so you can see the communication between them
- add a test based on the example
cc @zx2c4 @riyazdf
=> Improve wireguard example

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
Note when testing on Windows Build 16278 with todays docker master (server:`15b8d04`, client: `65202d6`) this will pull images but silently fails when running. This does **not** seem to be a regression with LinuxKit as the images from the previous update fail the same way (even when build with older `moby`). This is likely an issue with the Windows build and/or the docker master version used...
I suggest to merge this anyway as the OpenGCS changes picked up here contain a number of fixes.
=> Update LCOW to latest OpenGCS rev

AUTHORS
=> Update authors file with recent contributors

docs/kernels.md, test/cases/020_kernel/010_kmod_4.9.x/Dockerfile
It is no longer maintained and we should use the alpine base directly. This updates the test which used it and the documentation for compiling kernel modules
related to #2333
=> Remove user/references to linuxkit/kernel-compile

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
- openssl is for the okernel project (see #2465)
- attr-dev and libtirpc-dev are require to configure ZFS to build the kernel modules
/cc @t-koulouris
=> tools: Add openssl, attr-dev, and libtirpc-dev to the alpine base image

projects/okernel/Dockerfile.okernel
Updated okernel build dockerfile to pull openssl package from alpine base image (added in #2472).
=> okernel: build dockerfile now gets openssl package from alpine base image

blueprints/README.md, blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/docker-ce.yml, blueprints/docker-for-mac/metadata.json
Fixed a bug in `blueprints/docker-for-mac` which prevented the Docker daemon from starting if you follow the instructions in the `README.md`
The Docker daemon needs a `daemon.json` file. Previously a default trivial file was supplied by a `files` declaration in the `.yml` which wrote it to `/var/config/docker/daemon.json` -- a path which is really owned by the `metadata` package. This trick used to work but doesn't work any more -- the `/var/config` directory is empty and the daemon doesn't start. We may have been relying on undefined behaviour?
This patch tweaks the `README.md` to supply the `daemon.json` via the `metadata` package which is the mechanism a real deployment is expected to use. It also adds the `ca-certificates` package to make the …
=> docker-for-mac: supply the daemon.json via metadata

src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/hyperkit/go/hyperkit.go, src/cmd/linuxkit/vendor/github.com/moby/hyperkit/src/lib/pci_virtio_net_vpnkit.c
This adds support for the updated Hyperkit API, which is needed to
request a specific IP address in new versions of VPNKit / Docker for
Mac. IPs encoded in the UUID (the old method) will now be ignored by
VPNKit (from Docker for Mac 17.09-rc1 and later).
The protocol update in DfM also adds better error messages if Hyperkit fails to 
connect to VPNKit (e.g. if the IP or UUID is unavailable).
(more details in the commit message)
=> Update to latest Hyperkit API

docs/kernels.md, kernel/Dockerfile.zfs, kernel/Makefile
This adds support for building the ZFS kernel modules. The modules can be build as a separate package with tags matching the kernel build version. The modules can be added to a linuxkit image by adding the `zfs-kmod` package to the `init` section of a YAML file.
The `zfs-kmod` package also contains the standard kernel modules with `depmod` run over all of them so that `modprobe` should work.
The kernel modules do not compile for debug kernels due to CDDL incompatibility, apparently (the ZFS `./configure` script complains about `CONFIG_DEBUG_LOCK_ALLOC`)
Note, the `zfs-kmod` package is not build as the standard kernel build and is *not* hosted under the `linuxkit` Hub org due licensing uncertainty. Potential users will have to build the package themselves. `./docs/kernels.md` contains some …
=> Add support for building ZFS kernel modules

src/cmd/linuxkit/run_qemu.go
This picks the correct GIC version to be emulated.
Without it you get an error on Thunder-X (and possibly others):
KVM_SET_DEVICE_ATTR failed: No such device
See also https://bugzilla.redhat.com/show_bug.cgi?id=1375571#c6
Fixes #2360
=> cmd: On KVM/aarch64 add gic_version=host

kernel/Dockerfile
This follows an extensive discussion on the mailing list.
We store the destination IP of incoming packets as the source IP of
outgoing packets. When we send outgoing packets, we then ask the routing
table for which interface to use and which source address, given our
inputs of the destination address and a suggested source address. This
all is good and fine, since it means we'll successfully reply using the
correct source address, correlating with the destination address for
incoming packets. However, what happens when default routes change? Or
when interface IP addresses change?
Prior to this snapshot, after getting the response from the routing table
of the source address, destination address, and interface, we would then
make sure that the source address actually belonged to the …
=> wireguard: bump to new snapshot with better RTS semantics

src/cmd/linuxkit/run_qemu.go
If the state dir is preserved then the VM should come up with the same mac
address on subsequent reboots.
Fixes regression in #2498.
Rather than fixing the typo in the associated comments just remove them since
they don't really convey any useful information.
/cc @rn @arm64b
=> qemu: restore persistent mac address support

examples/wireguard.yml, pkg/getty/Dockerfile, pkg/ip/Dockerfile, pkg/ip/Makefile, test/cases/040_packages/023_wireguard/test-wireguard.yml
This makes things in general much cleaner. This is a reworking of #2457 from @justincormack , which avoids putting GPLd code directly in this repo, while also fixing up a few other small things.
Currently untested, but I wanted to get your feedback on the idea.
Note that downloading custom scripts and tarballs and whatnot via curl is already quite common throughout LinuxKit:
```
test/pkg/ltp/Dockerfile:RUN curl -fsSL -o ltp-full-${LTP_VERSION}.tar.xz ${LTP_SOURCE}
projects/clear-containers/kernel/Dockerfile:RUN curl -fsSL -o linux-${KERNEL_VERSION}.tar.xz ${KERNEL_SOURCE}
projects/selinux/kernel/Dockerfile:RUN curl -fsSL -o linux-${KERNEL_VERSION}.tar.xz ${KERNEL_SOURCE}
projects/landlock/kernel-landlock/Dockerfile:RUN curl -fsSL -o linux-${KERNEL_VERSION}.tar.xz ${KERNEL_SOURCE} …
```
=> wireguard: use custom wg-quick

docs/kernels.md, pkg/modprobe/Dockerfile, pkg/modprobe/Makefile
Created a minimal pkg/modprobe package which is based on scratch, with only the linuxkit/alpine /bin/busybox, and /bin/busybox -> /sbin/modprobe symlinked. This also includes the required capabilities and bind mounts for loading modules.
I followed the established pattern for the other included LinuxKit packages
1. Build Linuxkit packages, and use as follows -
```
- name: modprobe
image: linuxkit/modprobe:HASH
command: ["modprobe", "-a", "iscsi_tcp", "dm_multipath"]
```
(substituting the module you need to load in the above)
2. Create and boot your LinuxKit image
3. Run `lsmod` to verify the specified module has been installed
added minimal pkg/modprobe
**- A picture of a cute animal (not …
=> new pkg/modprobe from linuxkit/alpine base onto scratch

pkg/open-vm-tools/Dockerfile, pkg/open-vm-tools/scripts/poweroff-vm-default.d/poweroff.sh
I enabled hypervisor-initiated guest shut down in `pkg/open-vm-tools`
I added `poweroff-vm-default.d/poweroff.sh` to `/etc/vmware-tools/scripts`, which sends a `SIGTERM` to PID 1 (the LinuxKit init system) when a guest shut down event is received through `vmtoolsd`. The `poweroff.sh` script then returns exit code 0 through `vmtoolsd` to send success back to the hypervisor UX.
With a running LinuxKit OS in VMware vSphere, choose `Power` -> `Shut Down Guest` on the applicable VM. LinuxKit will shut down via the init system.
added support for guest shut down in pkg/open-vm-tools
=> added support for guest shut down in pkg/open-vm-tools

kernel/Dockerfile.zfs
Depmod in the zfs makefiles will never run as `/boot/` and relevant map files dont exist in our build environments.
Signed-off-by: Matt Johnson <matjohn2@cisco.com>
Depmod in the zfs makefiles will never run as the`/boot/` dir, system maps and relevant files don't exist in our build environments.
Running depmod on whatever is in the `/lib/modules` directory solves this issue.
Tested with local builds successfully.
If you can modprobe zfs once adding the image to `init:` it's working.
Depmod now runs correctly on the ZFS kernel module build.
=> Ensure depmod is run on ZFS module builds (fixes ZFS modprobe)

docs/platform-openstack.md, src/cmd/linuxkit/run_openstack.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/doc.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/requests.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/results.go, src/cmd/linuxkit/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/urls.go
Added an option to the run command for LinuxKit's OpenStack support which allows instances to be created with an SSH key pair associated.
This is part of additional work I'm doing to facilitate working instance metadata on OpenStack.
Leveraged client libraries to handle this being set and passed to the OpenStack APIs.
Launch an instance and then check for the `key_name` field to be set appropriately.
```
$ bin/linuxkit run openstack -network c5d02c5f-c625-4539-8aed-1dab3aa85a0a -flavor dc1.1x1 -keyname deadline_ed25519 linuxkit
Server created, UUID is 0a0d178f-42a7-43a5-9d95-e3ea9d3bad39
$ openstack server show 0a0d178f-42a7-43a5-9d95-e3ea9d3bad39 | grep key_name
| key_name                    | deadline_ed25519 …
```
=> [OpenStack] Support specifying an SSH key name when creating an instance

blueprints/README.md, blueprints/docker-for-mac/base.yml, pkg/swap/README.md
We always had 1G swap to work better with small memory setups, but this
was omitted in the update to LinuxKit.
cc @djs55 I noticed this on the desktop build, plus we didnt actually have a swap example.
=> Add swap to the Docker for Mac blueprint

src/cmd/linuxkit/run_qemu.go
Added a more descriptive error message when running qemu on macOS
Added an additional check if `runtime.GOOS == "darwin"`
Run it on macOS with `linuxkit run qemu ` both with and without `--fw <fw>`. It should give the more descriptive error message when `--fw` is not supplied.
More descriptive error message when firmware not supplied on macOS for qemu.
Fixes #2510
=> Better error message when running qemu on macOS when --fw not supplied

tools/mkimage-iso-efi/Dockerfile, tools/mkimage-iso-efi/Makefile, tools/mkimage-iso-efi/make-efi, tools/mkimage-iso-efi/patches/0001-TPM-build-issue-fixing.patch, tools/mkimage-iso-efi/patches/0002-video-Allow-to-set-pure-text-mode-in-case-of-EFI.patch
Current gummiboot tool can't work on arm64 platform, so this patch uses coreos grub2 to replace the nonfunctional gummiboot on arm64.
Coreos grub2 can work with Linux but not macOS on amd64, so we still use gummiboot tool as the boot media for those platforms.
This patch is evolved from PR #2454 , and used to adress the issue of #2359 , #2375 .
Thanks Avi Deitcher avi@deitcher.net for the contribution to build the GRUB2 from ubuntu 16.04 to alpine base image.
Support iso-efi format image generation
Build a grub2 core image in Alpine, then use that core image to construct the bootable iso image in `make-efi` script.
1. In tools/mkimage-iso-efi, build as you did, e.g. I do ORG=deitch …
=> mkimage: Support iso-efi generation for both arm64 and amd64

projects/kubernetes/kube.yml, projects/kubernetes/kubernetes/Dockerfile, projects/kubernetes/kubernetes/kubelet.sh
This builds the binaries for the kubernetes image from scratch rather than pulling unverified images of the Internet.
I also added openssl to the container since I found I needed it to sign my csr for RBAC purposes.
I had hoped to also bump cri-containerd here, but need to sort out a new build-time dependency on `libapparmor-dev` (which is only in Alpine edge/testing at the moment) so that will come later.
=> kubernetes: build kubelet from source & add openssl

blueprints/docker-for-mac/base.yml, examples/docker.yml, examples/swap.yml, pkg/mount/mountie.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/kubernetes/cri-containerd.yml, projects/kubernetes/cri-containerd/Dockerfile, projects/kubernetes/kube.yml, projects/kubernetes/ssh_into_kubelet.sh, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/000_ext4/test.yml, test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
This new version vendors containerd v1.0.0-beta.1 which is our current base.
It also fixes the build for seccomp support so this PR enables that at build time.
Lastly this new version requires `/dev/disk/by-uuid` so it can report the UUID of the container storage filesystem back to kubernetes, implement support for that and ensure `/dev` is bound into the cri containerd.
Note that kube 1.7 does not currently use `/dev/disk/by-uuid` directly itself, but code in the master branch does, so this is future proof for that too (the kubelet container already binds `/dev`).
Also a bonus fix to the `ssh_to_kubelet` script which wasn't using a unique exec id.
=> kubernetes: update to latest cri-containerd

projects/kubernetes/kube.yml, projects/kubernetes/kubernetes/kubelet.sh
If `kubelet.conf` already exits then don't try to redo `kubeadm`, no matter
what the metadata requests.
=> kubernetes: do not try to re-init the cluster on subsequent boots

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
On x86_64, the blkid package gets installed as a dependency, but
not on arm64. Explicitly add it as the new format package depends
on it.
=> tools/alpine: Explicitly add blkid

blueprints/docker-for-mac/base.yml, docs/external-disk.md, examples/docker.yml, examples/swap.yml, pkg/format/Dockerfile, pkg/format/format.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/kubernetes/kube.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/005_by_device_force/check.sh, test/cases/040_packages/006_format_mount/005_by_device_force/test.sh, test/cases/040_packages/006_format_mount/005_by_device_force/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
1) Added new argument -force to the format utility. This will force formatting of the specified single device if it exists and is a block device
2) By default, the format package will no longer format the specified single device if content exists on that device
3) Added new blkid-based check for content, in addition to the existing check for partitions on autoformat candidate devices.
4) Cleanup of old unused code.
5) Refactoring of block device verification.
6) Added test/cases/040_packages/006_format_mount/005_by_device_force
7) Added document of new arguments to /docs/external-disk.md. Also sorted the arguments in the doc alphabetically and added them as bullets so they do not run together on the page.
- By default, the format package will no longer …
=> format: blkid content check, format argument, and verbose argument

projects/kubernetes/boot.sh, projects/kubernetes/kube.yml, projects/kubernetes/kubernetes/kubeadm-init.sh, projects/kubernetes/kubernetes/kubelet.sh
The primary change here is to support triggering untainting the master node after `kubeadm init` via metadata, making it easier to quickly standup a usable single node dev VM. This involved a bit of reworking of how metadata is handled.
The secondary change is to aid debugging by dropping some stamp files around the init process, so it is possible to spot if it did not complete (e.g. because the VM was rebooted, which can easily happen since the init can need to do some largish pulls).
=> kubernetes: easier support for single master, plus slight robustness improvement

projects/kubernetes/kubernetes/kubeadm-init.sh
Allow more `kubeadm` options to be selected by supplying a `yaml` file. Unfortunately not all options are available via the CLI interface.
In the `kubeadm-init.sh` if the `/etc/kubeadm/kubeadm.yaml` file exists, then it uses it. Otherwise it falls back to the original behaviour.
Supply an `/etc/kubeadm/kubeadm.yaml` with some new options, and observe they take effect on a new cluster.
Allow custom `kubeadm` configuration files to be provided via `/etc/kubeadm/kubeadm.yaml`
=> kubernetes: add optional support for a kubeadm.yaml

kernel/Dockerfile
This is a simple version bump, which you can merge whenever is convenient for you. Now that we've moved to netlink, shipping this update requires no corresponding changes to the tools or any place else, which means you should be able to lazily just press "merge" without worrying about complex interactions or conflicts.
Release notes [from](https://lists.zx2c4.com/pipermail/wireguard/2017-October/001791.html) the mailing list:
```
* community: code welcomed
There's a small disorganized list of things to do, some of which are large
projects, and others are just little cleanups:
https://www.wireguard.com/todo/
If anybody is interested in working on something, please don't hesitate to
send an email to this list, team at wireguard.com, or me directly.
* tools: simmer down silly compilers
* …
```
=> kernel/wireguard: version bump

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/packet.yml, examples/vultr.yml, pkg/metadata/main.go, pkg/metadata/provider_aws.go, pkg/metadata/provider_openstack.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube.yml, projects/swarmd/swarmd.yml
Added support for retrieving basic metadata for instances deployed on OpenStack clouds.
Mostly by just copying the AWS metadata provider, as OpenStack strives to be largely compatible in this regard.
Build an image with networking support and the metadata package included and boot it up on an OpenStack installation.  Boot logs should confirm that the 'openstack' metadata probe succeeded, and things such as hostname are set appropriately. 
This commit adds basic support for retrieving instance metadata on OpenStack clouds.
Signed-off-by: Nick Jones <nick@dischord.org>
=> [OpenStack] Metadata service support

src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkg_push.go
Previously there would be a make "entering directory" hint in the logs, but
with the switch to `linuxkit pkg` that no longer occurs.
=> linuxkit pkg: Log before building or pushing.

src/cmd/linuxkit/pkg_push.go, src/cmd/linuxkit/pkglib/build.go
This overrides the default (which is to look for an exact git tag) and releases
just that.
/cc @eyz I can't easily test this without releasing something, are you able to test?
=> linuxkit pkg: Support --release option to pkg push.

blueprints/docker-for-mac/docker-ce.yml
Signed-off-by: dave <dprotaso@gmail.com>
`docker pull` was failing due to dns issues. We now bind the host's /etc/resolv.conf
From the machine running the VM (in my case a Mac)
```
docker -H unix://docker-for-mac-state/guest.00000948 pull hello-world
```
=> fix dns not working in the docker blueprint

kernel/Dockerfile
Routine version bump. Release notes [from the list](https://lists.zx2c4.com/pipermail/wireguard/2017-October/001815.html):
```
* receive: do not consider 0 jiffies as being set
This should fix some issues on 32-bit platforms with sending cookie reply
messages when they're not required.
* socket: compare while unlocked first
* socket: don't bother recomparing afterwards
* socket: gcc inlining makes this faster
We no longer take a lock when updating the endpoint, which should yield
some performance benefits.
* tools: try again if dump is interrupted
The tools will now try again to get information about a device if somebody
tries to modify the device while a dump is occurring.
* Makefile: quiet recursive make
Our makefile produces slightly slicker output now.
* qemu: bump stable kernel
Usual …
```
=> wireguard: bump version

tools/mkimage-raw-efi/Dockerfile, tools/mkimage-raw-efi/build.yml, tools/mkimage-raw-efi/make-efi, tools/mkimage-raw-efi/patches/0001-TPM-build-issue-fixing.patch, tools/mkimage-raw-efi/patches/0002-video-Allow-to-set-pure-text-mode-in-case-of-EFI.patch
UPDATE: removed `raw-bios` from this PR, separated to [2558](https://github.com/linuxkit/linuxkit/pull/2558)
Created a new `tools/` entry and therefore images:
* `tools/mkimage-raw-efi/`: create raw images that are bootable EFI
1. Created new directory
2. Created entrypoint for EFI that creates correct image given the `tar` input on stdin from moby
The intent, once this is merged, is to update moby build to add the output format `raw-efi`.
**Note:** There is some overlap between this raw format builder `raw-efi` and `iso-efi`. I would _like_ to extract common code to all, perhaps simplifying to just 1 docker image, but it was enough work to get this here and working fully. Let's merge it in first and get it …
=> Add support to make raw efi images

tools/mkimage-raw-bios/Dockerfile, tools/mkimage-raw-bios/build.yml, tools/mkimage-raw-bios/make-bios
Created a new `tools/` entry and therefore images:
* `tools/mkimage-raw-bios/`: create raw images that are bootable BIOS
The bios images are intended as a replacement for the `pkg/mkimage/`, but provides 2 advantages:
1. Much smaller builds (using `linuxkit.yml` gives ~64MB image vs 1.0GB)
2. Simpler builds: everything is done in a container, no need to spin up a VM in linuxkit to do filesystem manipulation
1. Created new directory
2. Created entrypoint that creates correct image given the `tar` input on stdin from moby
The intent, once merged, is to update moby build to remove the output format `raw` and replace it with `raw-bios`. We then can remove `pkg/mkimage` from the linuxkit repo entirely.
**Note:** …
=> Add support to make minimal raw bios images

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go
With the old package.mk arrangements we would only append -dirty and -$arch to
the hash if the user didn't specify a HASH= directly. So the following would
work
```
make ORG=ijc HASH=dev tag
```
and produce an image `ijc/«image»:dev`.
However the new equivalent:
```
linuxkit pkg build -org=ijc --hash-=dev
```
instead produces an image `ijc/«image»:dev-dirty-$arch`. Which is undesirable.
This commit refactors the code in two main ways:
Firstly directly append `-dirty` to the hash as we extract it from git (rather
than on use in the `Tag()` method), and only do this if the user has not
specified an explicit tag. Note that we still track dirtiness in the `Pkg`
object and so will not allow a push (or release) from a dirty tree (the
makefile version would have tried this with unpredictable …
=> linuxkit pkg: correct behaviour when user explictly specifies a hash.

projects/kubernetes/docker.yml
This makes `docker info` show the same OS as `kubectl get -o wide nodes`.
Followup for #2599
=> kubernetes: Mount /etc/os-release into docker cotainer too

examples/wireguard.yml
This must have had a merge error. Fixes version mismatch which
stops this working. The test was updated so is fine.
=> Fix kernel version in Wireguard example

scripts/update-component-sha.sh, test/hack/test-ltp.yml, test/pkg/ltp/build.yml, tools/mkimage-dynamic-vhd/build.yml, tools/mkimage-gcp/build.yml, tools/mkimage-iso-bios/build.yml, tools/mkimage-iso-efi/build.yml, tools/mkimage-vhd/build.yml, tools/mkimage-vmdk/build.yml
* linuxkit/test-ltp
* linuxkit/mkimage-dynamic-vhd
* linuxkit/mkimage-gcp
* linuxkit/mkimage-iso-bios
* linuxkit/mkimage-iso-efi
* linuxkit/mkimage-vhd
* linuxkit/mkimage-vmdk
Fixes #2580.
I also made what I thought would be a convenient extension to `./scripts/update-component-sha.sh` before I remembered that `linuxkit/mkimage-*` are used elsewhere and not in tree.
=> enable content trust for a bunch more repos

docs/packages.md, src/cmd/linuxkit/main.go, src/cmd/linuxkit/pkg.go
Could be e.g.:
```
pkg:
content-trust-passphrase-command: "lpass show <key> --password"
```
or
```
pkg:
content-trust-passphrase-command: "gpg -d ~/.notary/passphrase.gpg"
```
=> linuxkit: allow user to configure a content trust passphrase command

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
The device tree compiler is needed for some of the ongoing
arm64 work
=> tools: Add dtc to alpine base

kernel/Dockerfile
Simple version bump. Changes:
* noise: handshake constants can be read-only after init
* noise: no need to take the RCU lock if we're not dereferencing
* send: improve dead packet control flow
* receive: improve control flow
* socket: eliminate dead code
* device: our use of queues means this check is worthless
* device: no need to take lock for integer comparison
* blake2s: modernize API and have faster _final
* compat: support READ_ONCE
* compat: just make ro_after_init read_mostly
Assorted cleanups to the module, including nice things like marking our
precomputations as const.
* Makefile: even prettier output
* Makefile: do not clean before cloc
* selftest: better test index for rate limiter
* netns: disable accept_dad for all interfaces
Fixes in our testing and build infrastructure. …
=> wireguard: update to 0.0.20171017

projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml
Changed the compose example to insert files in `/etc/html` and `/etc/compose`  instead of `/var/html` and `/var/compose`, since `/var` now is mounted tmpfs and overrides it. See #2596 
/cc @justincormack @dprotaso 
changed the 2 yml files in `projects/compose/`
`moby build` and `linuxkit run`
Changes copy path for `files` to suit current tmpfs use of `/var`
=> Move mounted file from /var/html to /etc/html

src/cmd/linuxkit/gcp.go
Before:
```
$ ./bin/linuxkit push gcp -project ... -bucket ... ./broken.img.tar.gz
...
Creating image: broken
FATA[0013] Error creating Google Compute Image: error running operation: &{[0xc4203a71a0] [] []}
```
After:
```
FATA[0006] Error creating Google Compute Image: error running operation: &{[%!s(*compute.OperationErrorErrors=&{INVALID_IMAGE_TAR  The tar archive is not a valid image. [] []})] [] []}
```
Still not the best error, but at least it includes the relevant details now.
=> Fix GCP error printing

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/openstack.yml, examples/packet.yml, examples/vultr.yml, projects/kubernetes/kube.yml, projects/swarmd/swarmd.yml
Signed-off-by: Nick Jones <nick@dischord.org>
Updated tag references for the metadata image to one which includes fixes for OpenStack and AWS.
```shell
scripts/update-component-sha.sh --hash 4c588dba73ae7bec6f873130f715ba44082c4278 c385bb2dce56acf8b831bbf7fca3c8fc836ded66
```
Update tag ref for the metadata image across various examples.
=> Update metadata image tag references

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/git.go, src/cmd/linuxkit/pkglib/pkglib.go
Fixes #2613 (allowing building etc of packages not in git) but also fixes a more general issue where things wouldn't work if invoking `linuxkit pkg` from outside the git tree containing the package.
Previously:
```
$ cd /not/a/git/dir
$ git status
fatal: Not a git repository (or any of the parent directories): .git
$ linuxkit pkg build $GOPATH/github.com/linuxkit/linuxkit/pkg/swap/
fatal: Not a git repository (or any of the parent directories): .git
exit status 128
```
Even though `$GOPATH/github.com/linuxkit/linuxkit/` is a git clone/
This now works correctly. As does:
```
$ git status
fatal: Not a git repository (or any of the parent directories): .git
$ ls -A
build.yml  Dockerfile
$ cat build.yml 
image: dummy
$ cat Dockerfile 
FROM hello-world:latest
$ linuxkit pkg build .
Building …
```
=> Improve `linuxkit pkg` handling of git 

src/cmd/linuxkit/azure.go
Signed-off-by: Thomas Conte <thomas@conte.com>
Added support for Azure boot diagnostics so that the VM boot log can be read using the `az` command.
Added a DiagnosticsProfile section to the VirtualMachineProperties.
`linuxkit run azure`, and then (after a few seconds):
```
az vm boot-diagnostics get-boot-log -g LXKTEST -n linuxkitvmxxx
```
Added support for Azure boot diagnostics.
=> Add Azure boot diagnostics

src/cmd/linuxkit/push_openstack.go, src/cmd/linuxkit/run_openstack.go
I've added the image_id, server_id values to the command output, in addition to the log messages.
Just a couple of prints.
image_id=$(linuxkit push openstack ...)
server_id=$(linuxkit run openstack ...)
"run openstack" and "push openstack" now print image.id and server.id to stdout to avoid the need of parsing the command result in scripts.
=> Output image_id, server_id in stdout to ease automation

examples/wireguard.yml, test/cases/040_packages/023_wireguard/test.yml
- updated sha for `linuxkit/ip` to `linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506`
- `scripts/update-component-sha.sh linuxkit/ip:0d1d6d9810812bc23652556c3cbe7d2e87655278 linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506`
- I verified the linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506 image was pushed before this change
pkg/ip: updated sha tag in examples for #2605 
=> pkg/ip: updating linuxkit/ip sha to image built in #2605

docs/platform-openstack.md, src/cmd/linuxkit/run_openstack.go
Add support for -sec-groups with a list of comma-separated group names.
It mimics docker-machine. If the argument is not provided, the default group is assigned as usual.
OpenStack security groups are now supported with the `-sec-groups <group1>,<group2>...` flag.
=> support for OpenStack security groups

docs/security.md
**- What I did and how I did it**
I read the documentation and noticed dead links when clicking on them. Then I fixed it by updating the docs.
By reading the diff.
Fix documentation links to kspp and wireguard
=> docs: fix links to kspp and wireguard

tools/alpine/Dockerfile, tools/alpine/Makefile, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
https://github.com/docker-library/official-images/pull/3623
introduced alpine multi-arch images. Use it instead of
separate base images.
=> tools: Use alpine multi-arch image for linuxkit/alpine

test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test.yml, test/cases/040_packages/006_format_mount/003_btrfs/test.yml
=> test: Use the modprobe package instead of alpine:3.6

docs/platform-openstack.md, src/cmd/linuxkit/push_openstack.go, src/cmd/linuxkit/run_openstack.go
Signed-off-by: Marco Mariani <marco.mariani@alterway.fr>
I've added basic support for self-signed TLS authentication in the OpenStack commands.
Since the gophercloud package does not support passing a certificate, I override the HTTPClient instance of the ProviderClient.
Set OS_CACERT to a self-signed certificate, or pass it with --cacert.
To verify --insecure, set OS_AUTH_URL to the ip address instead of the hostname. It should fail unless the --insecure flag is set.
Added OS_CACERT and OS_INSECURE to "run openstack" and "push openstack".
=> add support for OS_CACERT, OS_INSECURE

tools/mkimage-raw-bios/make-bios, tools/mkimage-raw-efi/make-efi
Fix the raw image calculation. Because of the shell's integer calc, the image size in KB sometimes would return a size smaller than it should be. This ensures it always rounds **up** to the nearest whole KB, and then again **up** to the nearest multiple of 1024KB. Fixed in raw-efi and raw-bios.
Changed a line in each mkimage.
Build the image (or not, since I already pushed with latest hash), run it. Easiest is to run `moby build -format tar-kernel-initrd ...` and then `cat <output>.tar | docker run -i --rm -e DEBUG=true <image> > output.img`
For `<image>`, the following are available as pushed:
* `linuxkit/mkimage-raw-bios:eac4dcb78f837618e7e009060146977c2adabe19`
* …
=> Fix KB calculation for raw images

kernel/Dockerfile
Simple version bump. Changes:
* netns: use read built-in instead of ncat hack for dmesg
* netns: use time-based test instead of quantity-based
* qemu: allow for cross compilation
* qemu: work around ccache bugs
* qemu: test using four cores
* selftest: initialize mutex in routingtable selftest
We now cross compile and run in QEMU for x86_64, i686,
ARMv7, Aarch64, and MIPS. You can see the current build
status on: https://www.wireguard.com/build-status/
* stats: more robust accounting
* compat: fix up stat calculation for udp tunnel
The statistics from `ip link -stats` or from `wg show` are
now much more accurate.
* global: accept decent check_patch.pl suggestions
* global: infuriating kernel iterator style
* global: style nits
* global: use fewer BUG_ONs
* global: get rid of useless …
=> wireguard: update to 0.0.20171031

kernel/Dockerfile
20171031, the Halloween edition, had a show stopper bug, which was
neither security related, nor did it affect LinuxKit kernels, but
was important enough for me to bump the snapshot. This is the
corresponding LinuxKit bump. Changes:
* wg-quick: save all hooks on save
Tiny bug fix for 'wg-quick save'.
* timers: switch to kees' new timer_list functions
Shiny new things for Linux 4.14.
* compat: unbreak unloading on kernels 4.6 through 4.9
The real motivation for this extra snapshot bump. Before we would run into
some issues when unloading the module, which was not good.
=> wireguard: update to 0.0.20171101

projects/kubernetes/cri-containerd.yml, projects/kubernetes/cri-containerd/Dockerfile
Just bumps to the next cri-containerd release.
`socat` addition is due to #2639 and subsumes part of #2645.
=> kubernetes: Bump to cri-containerd v1.0.0-alpha.1 + add socat

src/cmd/linuxkit/pkglib/build.go
Pulling the arch suffixed version does not provide any assurance that a
previous build was actually completed.
Relates a little to the issue with failing to push the cache images I mentioned in #2667, since I discovered it while investigating, but I don't think it is a fix for that.
=> linuxkit pkg: pull the actual tag before build

src/cmd/linuxkit/azure.go, src/cmd/linuxkit/run_aws.go, src/cmd/linuxkit/run_gcp.go, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_hyperv.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/util.go
There is more to do on these, but clean up some unused variables,
missing args, stray `\n` etc.
=> Some linting improvements from gometalinter

src/cmd/linuxkit/run_vcenter.go
This fixes issue #2635 related to no network being passed during an
image upload as no network is required. However a hostname is still
required due to vCenter handing the upload to a vSphere server and it’s
DataStore.
Ensuring that the network is checked as a nil before looking at it's actual value
Tested in Lab env:
`./bin/linuxkit push vcenter -url https://dan:password@lab.test/sdk -datastore vSphereNFS -hostname lab01.fnnrn.me -path linuxkit linuxkit.iso`
In the Issue raised, the `-hostname <>` was missing, it is a requirement to upload images.
Fix for nil pointer reference in vSphere Push code.
Signed-off-by: Dan Finneran …
=> vSphere Panic Fix

src/cmd/linuxkit/run_qemu.go
On Linux the default is /dev/random which may block if there
is not enough entropy (and it determines lack of entropy
conservatively). /dev/urandom never blocks but is fed from
the same entropy source as /dev/random so this change should
not affect platforms which have hardware RNGs but helps to
prevent stalls on platforms, in particular some arm64 platforms,
where the hardware RNG is either not present or not enabled.
If you really care about proper entropy inside a VM do not use
'linuxkit run', it's mostly for testing and shouldn't be used
for production anyway.
fixes #2636
=> qemu: Use /dev/urandom on Linux for virtio-rng-pci

src/cmd/linuxkit/run_qemu.go
Removed the double invocation of `-device virtue-rng-pci`
Removed a single line
Build and run `linuxkit run qemu ...`
Remove double invocation of virtio-rng-pci
=> Remove double invocation of virtio-rng-pci

projects/kubernetes/kubernetes/kubelet.sh
For kubernetes integration in D4D, we need to be able to enable or disable the kubelet at startup in the linuxkit VM (to start it or not).
Currently, there is no way to do this properly with the `linuxkit/kubernetes` image. We could create a custom image for our needs, but it's possible that other uses of the `linuxkit/kubernetes` image get the same needs, so the original image is probably the place to do the improvement.
PR adds checks in the kubelet.sh script to be able to instantly exit the script if `/var/config/kubelet/disabled` file or `KUBELET_DISABLED` envvar is present. 
Default script behaviour is unaltered : if nothing is set, the kubelet script will execute normally.
=> Kubernetes : add capability not to start kubelet

src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/git.go
Log commands executed when '-v' is used on the commandline.
By default we do not dump the environment as this may contain
sensitive information, such as passwords and passphrases.
=> pkglib: Enable runtime debug output

src/cmd/linuxkit/pkglib/pkglib.go
The placement in #2679 can never have worked since we parse the yml over the
struct later on.
=> linuxkit pkg: Handle build --dev later

projects/kubernetes/.gitignore, projects/kubernetes/Makefile, projects/kubernetes/bridge.yml, projects/kubernetes/cri-containerd.yml, projects/kubernetes/cri-containerd/Dockerfile, projects/kubernetes/kube.yml, projects/kubernetes/kubernetes/kubeadm-init.sh, projects/kubernetes/weave.yml
Various updates:
* Add an option to do simple bridged networking. The way the files are injected is a bit hacky (alpine image doing echo) but will do for now, I'd like to figure out a way to do this with a kube yaml file (perhaps a `Job`) or some other way.
* Only build the images relevant to the build platform (but also make it configurable)
* Improvements to the handling of `/etc/kubeadm/kube-system.init/` with possibly invalid content.
* Bump to newer cri-containerd master, with vendoring updated to containerd beta3 and other fixes.
Individual commit messages have more info.
`make KUBE_FORMATS="iso-efi iso-bios" KUBE_RUNTIME=docker KUBE_NETWORK=bridge kube-master.iso`
and variants.
Support …
=> Kubernetes updates

projects/kubernetes/kubernetes/kubeadm-init.sh
This patch allows network policy to be supplied at runtime via the metadata directories:
- /var/config/cni/etc/net.d/
- /var/config/kube-system.init/
Previously the network policy had to be hard-coded in the image. 
The startup script in the `kubelet` container copies `/var/config/cni/etc/net.d` (if it exists) and it combines the contents of `/var/config/kube-system.init/` and `/etc/kubeadm/kube-system.init/` taking care to sort by filename correctly.
Add a file to the kubernetes image by extending kube.yml with
```
- path: /etc/kubeadm/kube-system.init/50-foo.yaml
contents: 'hello'
```
Create a metadata file:
```
$ cat > metadata.json <<EOT
{
"kube-system.init": {
"01-empty.yaml": {
"perm": "0755",
"content": "hello"
}, …
```
=> kubernetes: allow yaml, CNI configuration to be provided via metadata

docs/platform-packet.md
Spotted this while reviewing another commit, has been supported for a while.
=> Update Packet docs to say we support bonding

docs/platform-packet.md, examples/packet.arm64.yml, examples/packet.yml
- Add getty to get access to the serial console
- Add a arm64 example for baremetal type 2a
- Update documentation (and use example in documentation)
I've tested the PXE boot on arm64 and the bond interface gets
set up and seems usable.
=> examples: Update packet.net examples

pkg/node_exporter/Dockerfile
Updated the node_exporter package to the current version, had to change the argument names.
=> node_exporter 0.15.1; updated parameters

examples/packet.yml
without it sshd will not start
=> examples/packet: Add ssh keys to example

src/cmd/linuxkit/run_hyperkit.go
When running linuxkit targeting hyperkit we allow redirection of console input/output to a file
Hyperkit go bindings make this very straight forward and we just set a single property when a flag is enabled
After you start the VM with this new flag you should see the console-ring and tty in the state dir. Using `cat` and `screen`with the `console-ring` and `tty` behave as expected.
Allow `linuxkit hyperkit run` to redirect all console input & output to a file
=> allow hyperkit console input/output to be redirected

test/cases/020_kernel/006_config_4.14.x/test.yml, test/cases/020_kernel/110_namespace/006_kernel-4.14.x/common.yml
8c3140885cbe ("tests: Add 4.14 tests") and d88a1e591dfc
("Bump runc yml") overlapped so the runc version used in
the new files added by the first commit need updating.
=> tests: Update runc

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
Manually tested with latest master:
```
PS C:\Users\rneugeba\Desktop\docker> .\docker.exe version
Client:
Version:      master-dockerproject-2017-11-13
API version:  1.35
Go version:   go1.8.5
Git commit:   365c525
Built:        Mon Nov 13 23:49:13 2017
OS/Arch:      windows/amd64
Server:
Version:      master-dockerproject-2017-11-13
API version:  1.35 (minimum version 1.24)
Go version:   go1.8.5
Git commit:   aea31ab
Built:        Mon Nov 13 23:53:17 2017
OS/Arch:      windows/amd64
Experimental: true
```
and a alpine interactive container
=> LCOW: Update OpenGCS to latest

src/cmd/linuxkit/run_packet.go
This is not in most examples, but is in the Packet example, and
causes a duplicated console.
fix #2735
=> Only add in ttyS1 to kernel cmdline on Packet if not there already

kernel/Dockerfile
Routine version bump that also removes the necessity of carrying that extra patch. Changes:
```
* Kconfig: remove trailing whitespace
* allowedips: rename from routingtable
* tools: remove ioctl cruft
* global: revert checkpatch.pl changes
Cleanliness.
* device: please lockdep
* device: wait for all peers to be freed before destroying
These make the various checkers happy.
* netlink: plug memory leak
* qemu: check for memory leaks
There was a small memory leak on the netlink configuration layer that's now
been fixed.
* receive: hoist fpu outside of receive loop
Should be a small speedup on x86_64.
* qemu: more debugging
* qemu: bump kernel version
Significantly more debugging checkers have been turned on.
* wg-quick: stat the correct enclosing folder of config file
* wg-quick: allow for …
```
=> wireguard: update to 0.0.20171111

.circleci/config.yml
Currently one has to click down through a sequence of nested directories in the web UI:
```
↓ Container 0
↓ go/
↓ src/
↓ github.com/
↓ linuxkit/
↓ linuxkit/
↓ bin/
«actual binaries»
```
Which is super tedious.
=> Move CI build artifacts to top level

.gitattributes
github is marking a lot of ekrnel config files as "logos" again.
=> Improve language detection

Makefile, pkg/init/cmd/service/prepare.go
Implements https://github.com/moby/tool/pull/181
Design for things like Kubernetes setup that requires some cgroups to
exist when the service starts but it is not running in these, other
services are, so there would be a race if they are not created in each.
Essentially it is just a sugared `mkdir` in all the cgroup dirs.
=> Add support for creating cgroups in runtime section

tools/alpine/Makefile
Before the alpine image can be multi-arched and signed, the
DOCKER_CONTENT_TRUST=1 doesn't work on AArch64 based image build.
Now since we've used 'push_manifest.sh' to sign the multi-arch
supported alpine base image, we need to always enable
DOCKER_CONTENT_TRUST for the 'docker build' and DOCKER_CONTENT_PULL
for the 'docker pull' from the Perspective of security.
Remove the workaround of 'content trust build' issue when build AArch64 docker image with `--arg`
Remove the NOTRUST and always exported both DOCKER_CONTENT_TRUST and DOCKER_CONTENT_TRUST as 1.
Build the individual alpine image on both AArch64 and amd64 platform.
**- A picture of a cute …
=> alpine: Remove the 'content trust build' workaround

reports/2017-07-02.md, reports/2017-07-09.md
Signed-off-by: Damiano Donati <damiano.donati@gmail.com>
I've fixed some typos in the markdowns of the reports directory.
Trivial.
Trivial.
Fix some typos and no-break char in reports' markdowns.
=> Fix some typos and no-break char in reports markd

examples/node_exporter.yml, pkg/node_exporter/Dockerfile, pkg/node_exporter/build.yml, pkg/node_exporter/build.yml-skip
Built node-exporter from sources. Static, minimal image. Used 0.15.0 since the 0.15.1 tag exists only on dockerhub.
This aims to fix https://github.com/linuxkit/linuxkit/issues/2349 but the current PR does not pass the test-pr target. Any idea why? It's not clear to me from the logs.
=> Node exporter

src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/util.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/rn/iso9660wrap/iso9660wrap.go
Current if `-data ""` is used we treat it as a raw string and do not create any a metadata iso to pass to the VM. However if `-data` instead refers to an empty file we currently error out due to a check for empty files in the `iso9660wrap` package.
This PR:
* Vendors the latest `iso9660wrap` package, which allows zero sized files (and also drops the text of The Raven)
* Refactors the code which creates the ISO into a function common to Hyperkit and QEMU
* Causes that function to skip creating a file if the file is empty, as it already does if the argument is an empty string.
Related to https://github.com/linuxkit/kubernetes/issues/4
Per #2721 we should, IMHO, also separate the file vs raw string functionality of the `-data` argument, but I've not tackled that here.
=> Handle empty metadata file better (by ignoring)

docs/metadata.md
Replace `--data` with `-data`, add a hint for reading metadata from a file.
=> docs: minor fixes for use of `-data` 

kernel/Makefile
For 'build_perf_' and 'build_zfs_' targets in the Makefile,
since both of them are dependends on the build_$(2)$(3) target,
So, we pull the image with DCT as part of the dependency on build_$(2)$(3) and then build with DOCKER_CONTENT_TRUST explicitly set to 0
Fix `build_perf_` and `build_zfs_` target build issue
Remove the reduplicated ones
`make ORG=m1115 build_perf_4.13.x` to build a standalone one.
=> kernel: Fixing kernel_perf and kernel_zfs build issue

examples/cadvisor.yml, test/cases/000_build/100_examples/080_cadvisor/test.sh
`eamples/cadvisor` overlapped with a kernel update. This brings it up-to-date. Also add a build test for the example while at it
=> Update cadvisor and add build test

src/cmd/linuxkit/pkg_push.go, src/cmd/linuxkit/pkglib/build.go
If doing the build separately from pushing (as I am intending in
https://github.com/linuxkit/kubernetes/pull/8/) it is desirable to avoid a
second build when pushing.
=> linuxkit pkg: allow skipping build before push

blueprints/docker-for-mac/base.yml, docs/packages.md, examples/aws.yml, examples/azure.yml, examples/cadvisor.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/openstack.yml, examples/packet.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, examples/wireguard.yml, linuxkit.yml, pkg/sysctl/Dockerfile, pkg/sysctl/build.yml, projects/swarmd/swarmd.yml, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/config.go, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/019_sysctl/test.yml
~~**DO NOT MERGE:** Depends on https://github.com/moby/tool/pull/189. I will push `pkg/sysctl` image and crank yaml once that is merged and pulled in here.~~ https://github.com/moby/tool/pull/189 merged and folded in here.
This is a `moby.ImageConfig` struct which is marshalled into JSON and added as
the `org.mobyproject.config` label on the built image.
Convert `pkg/sysctl` as PoC.
=> linuxkit pkg: Add `config` field to `build.yml`

Makefile
Currently we will always create a temp tar file even the 'docker run'
failed for some reason,e.g, the docker daemon doesn't run. As a result,
we'll get the 2nd error even we've fixed 'docker run' failure.
Fix binaries generation failure
Add some interim target names to mitigate the `docker run` failure case. 
1. `systemctl stop docker` (Actually I happened to build the binaries in case of docker daemon is not running and get the error information)
2. `make bin/rtf`
3. The `docker run` will fail in this case, but it generate a invalid temp file `tmp_rtf_bin.tar` (size = 0)
4. `systemctl start docker`
5. `make bin/rtf`, since the invalid `tmp_rtf_bin.tar` target is already …
=> Makefile: Fix binaries generation issue when 'docker run' failed

src/cmd/linuxkit/push_aws.go
- ENA networking is what the very new (and bare metal) machines have
- sriov "simple" mode is Intel VF passthrough
I reflect the underlying APIs, which is bool for ENA and a string
for sriov even though there is currently only one valid sriov option...
=> Add support for newer AWS networking types

src/cmd/linuxkit/run_hyperkit.go
vpnkit mode has one or two arguments (eth socket and port control socket).
If splitting into only 2 then
vpnkit,vpnkit-state/eth.sock,vpnkit-state/port.sock
becomes
2: vpnkit
1: vpnkit-state/eth.sock,vpnkit-state/port.sock
rather than
0: vpnkit
1: vpnkit-state/eth.sock
2: vpnkit-state/port.sock
as desired.
=> hyperkit: split network option into 3

kernel/Dockerfile
This is a double bump.
Changes 0.0.20171122:
```
* chacha20poly1305: fast primitives from Andy Polyakov
Samuel Neves and I have spent considerable time and headaches porting,
reworking, and partially rewriting Andy's optimized implementations of
ChaCha20 and Poly1305. We now support the following:
On x86_64:
- Poly1305: integer unit
- ChaCha20: SSSE3
- HChaCha20: SSSE3
- Poly1305: AVX
- ChaCha20: AVX2
- Poly1305: AVX2
- ChaCha20: AVX512
- Poly1305: AVX512
On ARM:
- Poly1305: integer unit
- ChaCha20: NEON
- Poly1305: NEON
On ARM64:
- Poly1305: integer unit
- ChaCha20: NEON
- Poly1305: NEON
On MIPS64:
- Poly1305: integer unit
All others:
- ChaCha20: generic C
- Poly1305: generic C
This is a pretty substantial amount of new handrolled assembly. It will
perhaps MURDER KITTENS, so please tread …
```
=> wireguard: update to 0.0.20171122 to 0.0.20171127

Makefile, src/cmd/linuxkit/main.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/version/version.go
Since the tool can have some impact on the resulting image it seems like a good idea to track these so add `org.mobyproject.linuxkit.version` with the version and `org.mobyproject.linuxkit.revision` with the git commit.
Not sure if I should guard with `!= "unknown"` in both cases, I didn't but maybe it makes sense.
=> Include tool version info in package/image labels

docs/platform-vbox.md, src/cmd/linuxkit/run.go, src/cmd/linuxkit/run_vbox.go
You can use `linuxkit run vbox ...` to run using Oracle VirtualBox.
ISO or raw should be supported, and you can specify EFI.
Some more options may be useful in future.
=> Add VirtualBox support to linuxkit run

docs/packages.md, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/depends.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/pkglib/pkglib_test.go
This implements (close to) the second proposal in #2766. There are a couple of preparatory patches but the main work is in the final patch, so I reproduce that commit message here:
>    linuxkit: implement docker image dependencies for pkg build.
>    
>    This allows the `linuxkit/kubernetes` "image-cache" packages to use a standard
>    `linuxkit pkg build` based flow rather than requiring surrounding scaffolding.
>    
>    Fixes #2766. Compared with the original (actually, the second) proposal made in
>    issue #2766, the field is `docker-images` rather than `images` to allow for
>    future inclusion of e.g. `containerd-images`.
>    
>    Signed-off-by: Ian Campbell <ijc@docker.com>
I will shortly be raising a WIP PR against https://github.com/linuxkit/kubernetes which uses this …
=> Add dependent images to build.yml

pkg/containerd/etc/containerd/config.toml
containerd v1.0.0-rc.0 changed the subreaper config entry to the
negative given subreaper "on" is the default. However, linuxkit
does not need to change the default subreaper setting so removing
the now invalid config line.
Ref: containerd/containerd#1822
It looks like this missed the release notes :(
=> remove subreaper config item

kernel/patches-4.14.x/0001-NVDIMM-reducded-ND_MIN_NAMESPACE_SIZE-from-4MB-to-4K.patch
This change hasn't made it upstream but seems to be required
for LCOW to work. We carried it in the 4.11/4.12/4.13 kernels.
I haven't pushed new kernels yet as some testing with a local build revealed other LCOW issues, but the specific issue related to this (https://github.com/Microsoft/opengcs/issues/174) is fixed with this patch.
=> kernel: Add NVDIMM size patch to 4.14.x

projects/shiftfs/shiftfs.yml
No need to have a special containerd daemon config file; might have been
a vestige of earlier variants of LinuxKit? It is also out of date and
incorrect for current containerd version.
=> Remove containerd config from shiftfs.yaml

src/cmd/linuxkit/run_hyperkit.go
Ensure VPNKit process is properly killed when errors occur
We added an ExitHandler to logrus so that VPNKit will be shutdown
when log.Fatal* is invoked
1. Start LinuxKit (hyperkit backend) with VPNKit networking 
2. Send a KILL signal to hyperkit
3. Ensure vpnkit process exits
VPNKit process will exit when hyperkit fails to start or is terminated
=> Ensure VPNKit process is properly killed when errors occur

kernel/Dockerfile
```
* curve25519: explictly depend on AS_AVX
* curve25519: modularize dispatch
It's now much cleaner to see which implementation we're calling, and it will
be simpler to add more implementations in the future.
* compat: support RAP in assembly
This should fix PaX/Grsecurity support.
* device: do not clear keys during sleep on Android
While we want to clear keys when going to sleep on ordinary Linux, this
doesn't make sense in the Android world, where phones often sleep but are
woken up every few milliseconds by the radios to process packets.
* compat: fix 3.10 backport
Important compat fixes for non-x86.
* device: clear last handshake timer on ifdown
When bringing up an interface, we don't want the rate limiting to handshakes
to apply.
* netlink: rename symbol to avoid clashes
Allows …
```
=> wireguard: update to 0.0.20171211

Vagrantfile, scripts/Vagrantfile
Added Vagrant support (VMware Fusion, VMware Workstation, VirtualBox, and Hyper-V).
Added a `Vagrantfile`.
```bash
mbp:~ dave$ git clone -b vagrant https://github.com/Manouchehri/linuxkit
mbp:~ dave$ cd linuxkit/
mbp:linuxkit dave$ vagrant up # Wait for a few minutes and a couple hundred lines of output. 
mbp:linuxkit dave$ vagrant ssh 
vagrant@vagrant:~$ linuxkit build ./go/src/github.com/linuxkit/linuxkit/examples/minimal.yml
Extract kernel image: linuxkit/kernel:4.9.65
....
Create outputs:
minimal-kernel minimal-initrd.img minimal-cmdline
vagrant@vagrant:~$ ls -l minimal*
-rw-r--r-- 1 vagrant vagrant       42 Nov 30 02:43 minimal-cmdline
-rw-r--r-- 1 vagrant vagrant 41308847 Nov 30 02:43 minimal-initrd.img
-rw-r--r-- 1 vagrant …
```
=> Added initial Vagrant support.

README.md
Someone was asking about this on Slack and it's not all that obvious this is where to look now that we use `linuxkit build` and not `moby build`.
=> README: Add a pointer to the moby tool yml docs.

docs/vendoring.md, src/cmd/linuxkit/build.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/docker.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/image.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/linuxkit.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/output.go
https://github.com/moby/tool/compare/656bd87fd26b...d9d2a91780b3
d9d2a91 Merge pull request #193 from ijc/bugfix-191
307f13b Defer dockerRm until we are finished with the contents
ebd7228 Merge pull request #191 from ijc/reduce-memory-via-tempfiles
3045a80 Stream `docker export` directly to consumer
9f44acf Generate intermediate image into a temp file
9558740 Add cpu and mem profiling options
Reduces the memory usage substantially.
While here make some notes about the need to update src/cmd/linuxkit/build.go
where people might see them.
=> Bump moby tool to d9d2a91780b3

src/cmd/linuxkit/pkglib/git.go
When I tried to use `linuxkit pkg build` for the first time on a new package, it showed `Unable to parse ls-tree output: ""` error, which I could not parse before I looked at the code. Hopefully, this change would make it easier for people to use the tool for the first time on a new package.
=> Improve error message for new packages

docs/kernels.md, scripts/kernels/Dockerfile.deb, scripts/kernels/Dockerfile.rpm, scripts/kernels/README.md, scripts/kernels/centos.sh, scripts/kernels/debian.sh, scripts/kernels/fedora.sh, scripts/kernels/mainline.sh, scripts/kernels/ubuntu.sh
We used to periodically build linuxkit packages for kernels from other distributions. This was a manual process, so didn't happen very often. This PR abandons  this approach and instead rewrites the scripts so that users can build their own LinuxKit kernel packages from `centos`, `fedora`, `debian`, and `ubuntu` kernels.  There is also a script to re-package the mainline PPA kernels.
Once this gets merged, I'll remove the docker hub repos.
resolves #2763
=> Change support for foreign kernels

blueprints/README.md, docs/metadata.md, docs/platform-hyperkit.md, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/util.go
Split the `-data` option from `linuxkit run` - which can take either a path to a file or a raw string - into two options:
* `-data STRING`
* `-data-path PATH`
Also updated relevant documentation.
Closes #2721 and addresses the design raised in #2727 
Modify the options to `run_qemu.go` and `run_hyperkit.go`, and updated `CreateMetadataISO`. 
Run it.
Unfortunately, there do not appear to be any tests that exercise `-data`. Will try to add some, though unsure how to do so. 
Cleanly support metadata as both path and raw string.
=> Split linuxkit run -data options into string and file

blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/docker-ce.yml, docs/metadata.md, examples/aws.yml, examples/gcp.yml, examples/openstack.yml, examples/vultr.yml, pkg/metadata/main.go
Moved metadata (and userdata) to `/run/config` instead of `/var/config`. Closes #2829 
Two questions to be addressed:
1. Is `/run/config` the right path? I chose it to match `/var/config`, but wonder if something else might need the space? Should it be `/run/metadata`? I prefer `/run/config`, but want to raise the question.
2. Is there anything in the docker-for-mac blueprint that expects it to be in `/var/config`? In the `docker-ce.yml` I updated the mount of data from `/var/config/docker:/var/config/docker` to `/run/config/docker:/var/config/docker`, so it should provide the data to docker where it expects, but not sure if anything else builds on the base system.
* Changed the `ConfigPath` var in …
=> Move metadata to /run instead of /var

pkg/metadata/Dockerfile, pkg/metadata/build.yml
Fix the labeling and binds for `linuxkit/metadata`
Moved the label to the new `build.yml` config (with thanks to @justincormack for the help) and added mounts for `/run`
Run it. Now metadata shows up correctly.
Fix binds for metadata under `/run`.
=> Add /run to binds and use newer yml label format

docs/platform-packet.md, examples/packet.arm64.yml, examples/packet.yml, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/tool/src/initrd/initrd.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/build.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/config.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/linuxkit.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/output.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/schema.go
- vendor in `moby` with the changes to handle CPU microcode
- Update `packet.net` to include the Intel CPU microcode for amd64 and not for arm64
- Update docs
resolves #2843
=> Vendor latest moby and update packet.net examples to include CPU ucode

docs/platform-packet.md, examples/packet.arm64.yml, examples/packet.yml, pkg/firmware-all/Dockerfile, pkg/firmware-all/README.md, pkg/firmware-all/build.yml, pkg/firmware/Dockerfile, pkg/firmware/README.md, pkg/firmware/build.yml, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/tool/src/initrd/initrd.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/build.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/config.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/linuxkit.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/output.go, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/schema.go
This adds two new packages: `firmware` and `firmware-all`. The former only contains firmware blobs required by the driver modules included in a LinuxKit kernel (plus license files and the AMD CPU microde) while the latter contains a snapshot of the `linux-firmware` repository. `firmware` should be sufficient for use with LinuxKit kernels, while `firmware-all` may be used with custom or other distro's kernels.
Repositories are set up and packages pushed/signed. This should now be good for review.
resolves #2714
=> Add support for driver (and CPU) firmware

kernel/Dockerfile
* receive: treat packet checking as irrelevant for timers
Small simplification to the state machine, as discussed with Mathias
Hall-Andersen.
* socket: check for null socket before fishing out sport
* wg-quick: ifnames have max len of 15
* tools: plug memleak in config error path
Important bug fixes.
* external-tests: add python implementation
Piotr Lizonczyk has contributed a test vector written in Python.
* poly1305: remove indirect calls
From Samuel Neves, we now are in a better position to mitigate speculative
execution attacks.
* curve25519: modularize implementation
* curve25519: import 32-bit fiat-crypto implementation
* curve25519: import 64-bit hacl-star implementation
* curve25519: resolve symbol clash between fe types
* curve25519: wire up new impls and remove donna
* tools: …
=> wireguard: update to 0.0.20180118

MAINTAINERS
These are mostly taken from containerd and adjusted to LinuxKit and most of them seem like common sense to me. We specifically needed to clarify the role of the TSC, but I think it's also good to clarify the roles of maintainers etc.
While I don't think this is a surprising change or controversial it would be good to get approval from from @justincormack @deitch @ijc and @riyazdf 
resolves #2848
=> Add some rules to the MAINTAINERS file.

.github/CODE_OF_CONDUCT.md
See recommendations at https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
See also #2848
=> Add code of conduct link to Github recommended location

Makefile
To avoid confusion with master builds
=> build: Bump linuxkit version to v0.2+

src/cmd/linuxkit/main.go
=> Do not print git commit if empty

kernel/Dockerfile, kernel/ucode/intel-ucode-md5sums
Signed-off-by: Emily Casey <ecasey@pivotal.io>
Signed-off-by: Steve Hiehn <shiehn@pivotal.io>
I changed the downloaded version of microcode to 20171117 because the link to download version 20180108 was returning a 404. 20180108 must have been made unavailable because the intel site currently reports 20171117 as the latest version https://downloadcenter.intel.com/download/27337?v=t.
I Changed the UCODE_URL to point at the microcode-20171117.tgz and changed the expected md5.
`docker build` the kernel image
Downgraded to Intel microcode version 20171117
=> Use microcode-20171117 in kernel build as microcode-20180108 is no longer available

kernel/Dockerfile
```
== Changes ==
* curve25519-fiat32: uninline certain functions
This results in much smaller code size and significanat speed gains on smaller
hardware.
* poly1305: add poly-specific self-tests
Poly is easy to get wrong, so we've added quite a few tests that examine
certain edge cases and places where other implementations of historically
failed.
* tools: dedup secret normalization
* tools: share curve25519 implementations with kernel
* contrib: keygen-html: share curve25519 implementation with kernel
There is now only one place where we ship 25519 code.
* qemu: disable PIE for compilation
* qemu: disable AVX-512 in userland
* qemu: update base versions
Test suite enhancements.
* device: let udev know what kind of device we are
This enables folks to query the device type via udev, which …
```
=> wireguard: update to 0.0.20180202

src/cmd/linuxkit/run_qemu.go
There are more acceleration backend in the pipeline for qemu. Allow to select the qemu binary being used (makes it easier to select master builds) and the acceleration option.
For example:
```
linuxkit run qemu -qemu ~/src/repos/virt/qemu/x86_64-softmmu/qemu-system-x86_64 -accel hvf minimal
```
boots with a qemu master build on macOS with Hypervisor Framework Acceleration.
Note this also changes the `LINUXKIT_QEMU_KVM` env variable to `LINUXKIT_QEMU_ACCEL`
=> Allow choice of qemu binary and acceleration

kernel/Dockerfile, kernel/Dockerfile.kconfig, kernel/Makefile, kernel/config-4.14.x-aarch64, kernel/config-4.14.x-x86_64, kernel/config-4.15.x-aarch64, kernel/config-4.15.x-x86_64, kernel/patches-4.14.x/0001-NVDIMM-reducded-ND_MIN_NAMESPACE_SIZE-from-4MB-to-4K.patch, test/cases/020_kernel/006_config_4.14.x/test.yml, test/cases/020_kernel/007_config_4.15.x/test.yml, test/cases/020_kernel/016_kmod_4.14.x/Dockerfile, test/cases/020_kernel/016_kmod_4.14.x/test.yml, test/cases/020_kernel/017_kmod_4.15.x/Dockerfile, test/cases/020_kernel/017_kmod_4.15.x/test.yml, test/cases/020_kernel/110_namespace/006_kernel-4.14.x/common.yml
These kernels include significant changes to spectre mitigation but may require a micro-code update which has not yet been released.
Also improve the application of kernel patches to disable fuzzing (resolves #2906)
x86 kernels already build, arm64 kernels still building
=> Update kernels to 4.15.2/4.14.18

test/cases/020_kernel/000_config_4.4.x/test.yml, test/cases/020_kernel/001_config_4.9.x/test.yml, test/cases/020_kernel/006_config_4.14.x/test.yml, test/cases/020_kernel/007_config_4.15.x/test.yml, test/hack/test.yml, test/pkg/kernel-config/check-kernel-config.sh
This commit adds tests for KPTI, retpoline, bpf_jit_always_on, and
disabled scsi proc fs configs.
Closes #2890
Signed-off-by: Craig Ingram <cingram@heroku.com>
The test.yml's will need to be updated with a new build of the linuxkit/test-kernel-config image, which (I think) I need someone else to build/push first. 
I reviewed the checks added to the kernel configs for the past few months, in particular focusing on the Meltdown/Spectre mitigation checks, and added them to the `check-kernel-config.sh` script. 
Followed the pattern for other checks, and then ran the tests with the latest kernels using a local version of the `test-kernel-config` image to verify everything passed.
* I had to build a local version of the …
=> Extend kernel config test

Makefile, README.md, docs/testing.md, test/Makefile
Pulls in a bumper crop of updates from last year and some recent improvements:
$ git log --oneline 3e8ed35ca934..f2409214ca3b | cat
f240921 Merge pull request #38 from ijc/timestamp-precision
f626ffe Preserve full precision in nanoseconds part of log timestamp
29c89e8 Merge pull request #37 from rn/ps1
600ea59 Update documentation with new powershell features
9fed685 Add powershell test and group templates and a stub library
3ada6bd Don't use '#!/bin/sh' in tests or group initialisers
dd187b4 Add test cases for powershell scripts
4892754 Add support for writing tests in powershell (on Windows)
00cdd1f Add the ability to execute powershell scripts
00906da Add TestFilePath to the Test struct
e6fdcb7 Add GroupFilePath to the Group struct
c590dbc Make group member names for Pre/Post test …
=> Bump rtf to f2409214ca3b719567aa15bb7b363f24876a4d98

kernel/Dockerfile
```
* keygen-html: fix up copyright
Copy and paste errors.
* tools: do not collide types with libc clashes
* tools: FreeBSD doesn't have EAI_NODATA
* tools: fixup errno handling
* tools: endian.h is not portable
Fixes compilation and correctness several places.
* tools: allow in-line comments
You can now put a # comment anywhere in a line, in which case, it extends
until the end of the line.
* wg-quick: match from beginning rather than shift right
This raises the proper error when providing interface names that are too long.
* qemu: add support for powerpc
Now that we have known PPC users, it's probably a good thing to ensure we
don't introduce bugs, so PPC has been added to our CI on build.wireguard.com.
* poly1305: fix up selftest counter
Make sure we're using the right array length in …
```
=> wireguard: update to 0.0.20180218

src/cmd/linuxkit/run_qemu.go
This PR adds the functionality to allow the user to run the qemu container detached via a flag `-detached`  under `linuxkit run qemu`. I have added this flag as we are building tooling around Linuxkit and want to have the option for the container to not have a tty
I added the detached to the qemuconfig struct that gets passed to down to the docker args
I have run all the tests included in the readme and have been able to run the container in the background successfully
This PR adds the functionality to allow the user to run the qemu container detached via a flag `-detached`  under `linuxkit run qemu`
=> This commit adds the functionality to run the qemu container detached

examples/influxdb-os.yml
I tried to to build an OS with all the TICK stack
(https://www.influxdata.com/time-series-platform/): InfluxDB,
Chronograf, Kapacitor, Telegraf.
Very easy but I was curious to try it out after few months just reading
about linuxkit.
You can build the image with:
```
linuxkit build --format iso-bios examples/influxdb-os
```
And you can run it:
```
linuxkit run qemu -iso influxdb-os.iso -publish 8888:8888/tcp -publish
8086:8086/tcp
```
After that you can open your browser on `localhost:8888` to see
Chronograf (the dashboard up and running).
All the services are configurated to talk with each other.
=> Added InfluxDB OS an example

src/cmd/linuxkit/run_vbox.go
Starting a virtualbox vm in bridged networking mode requires the host's
network interface to attach to the bridge being specified. This commit
adds command line option '--bridgeadapter iface' to 'linuxkit vbox run',
where 'iface' is the host's network interface to use in bridged mode.
Fixes: #2929
Signed-off-by: Olaf Bergner <olaf.bergner@gmx.de>
Added command line option `--bridgeadapter` taking the name of a host network interface to use for bridged networking to `linuxkit run vbox`.
Added flag `bridgeadapter` to `run_vbox.go`.
Run e.g. on Mac
```
linuxkit run vbox --iso --networking bridged --bridgeadapter en0 docker.iso
```
and observe in VirtualBox GUI that VM `docker` is started in bridged mode, **not** NAT mode.
**- …
=> Add cli option '--bridgeadapter' to 'linuxkit vbox run'

examples/docker-for-mac.md
Signed-off-by: functor <meehow@gmail.com>
Just a minor update to the docker-for-mac example documentation that makes it work and be self-contained. Might save some time for people who are just experimenting and don't know yet about the metadata functionality etc.
=> A minor update/hint to the docker-for-mac example documentation.

scripts/push-manifest.sh, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/manifest_push_script.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/run_qemu.go
This PR adds the basic support for s390 architecture on linuxkit
command.
Signed-off-by: Alice Frosi <alice@linux.vnet.ibm.com>
Add basic support for s390 systems:
- s390-specific flags to run qemu on s390 architecture
Update qemu flag in `src/cmd/linuxkit/`.
=> Add s390x support for Linuxkit binary and tools

tools/alpine/Makefile, tools/alpine/packages, tools/alpine/packages.aarch64, tools/alpine/packages.s390x, tools/alpine/packages.x86_64, tools/alpine/push-manifest.sh
Add support for s390 architecture for linuxkit/alpine and the
other docker images in tools and pkg.
Signed-off-by: Alice Frosi <alice@linux.vnet.ibm.com>
I updated `tools` to be able to build and push linuxkit/alpine docker image for s390 architecture
=> Add s390x support for linuxkit docker images

tools/mkimage-qcow2-efi/Dockerfile, tools/mkimage-qcow2-efi/build.yml, tools/mkimage-qcow2-efi/make-efi
Signed-off-by: Garth Bushell <garth.bushell@oracle.com>
Add mkimage-qcow2-efi
Copied existing efi and wrapped it in a qcow2
linuxkit build -format tar -o - | docker run -i mynewformat > out.img
file out.img `out.img: QEMU QCOW Image (v3), 70254592 bytes`
Adds support for a qcow2 EFI image format
=> Adds support for building a qcow2 EFI image

src/cmd/linuxkit/run_hyperkit.go
Signed-off-by: Emily Casey <ecasey@pivotal.io>
I added support for port forwarding when running hyperkit with an existing vpnkit instance
I set Sockets9P and VSockPorts on the hyperkit instance when starting with an existing vpnkit process
Start vpnkit kit. `linuxkit run hyperkit` with the `-neworking vpnkit[,eth-socket-path[,port-socket-path]]` flag. In the guest use `vpnkit-expose-port` to configure a forwarded port. From the host send traffic to the configured host port and observe that it is forwarded to the guest port.
Supports port forwarding when running hyperkit with an existing vpnkit image
=> Configure guest with 9P mount and vsock port when using existing VPNKit instance

kernel/Dockerfile
```
* queueing: skb_reset: mark as xnet
This allows cgroups to classify packets.
* contrib: embedded-wg-library: add ability to add and del interfaces
* contrib: embedded-wg-library: add key generation functions
The embeddable library gains a few extra tricks, for people implementing
plugins for various network managers.
* crypto: read only after init
* allowedips: fix comment style
* messages: MESSAGE_TOTAL is unused
* global: in gnu code, use un-underscored asm
* noise: fix function prototype
Small cleanups.
* compat: workaround netlink refcount bug
An upstream refcounting bug meant that in certain situations it became
impossible to unload the module. So, we work around it in the compat code. The
problem has been fixed in 4.16.
* contrib: keygen-html: rewrite in pure javascript
* Revert …
```
=> wireguard: update to 0.0.20180304

pkg/tss/README.md
Without the privileged flag, the tcsd daemon does not have
access to the mounted host device files, especially the tpm
device file.
=> Update README to include privileged flag

examples/cadvisor.yml, examples/docker.yml, examples/getty.yml, examples/hostmount-writeable-overlay.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml
On z platform, the kernel console is ttysclp0
Signed-off-by: Alice Frosi <alice@linux.vnet.ibm.com>
I added the s390 console to `examples`
=> Add s390 console to examples

src/cmd/linuxkit/serve.go
Fixes "serve" sub-command to parse command line arguments.
=> Subcommand serve should parse flags.

docs/packages.md
Updated docs to indicate the CI dependency on packages building.
Helps prevent the issue raised [here](https://github.com/linuxkit/linuxkit/pull/2951#issuecomment-371283872) by @rn 
Typing a few paragraphs in markdown.
Read it.
Include detail on CI packages dependency.
=> Add CI info and dependency to packages doc

kernel/Makefile
The non-existent target "check" is marked phony, this looks like a typo. 
The typo is mostly harmless, even without this change the "fetch" target is still created and it's prerequisites are added correctly.
Removes ".PHONY" on non-existent target.
=> Non-existent target check is marked phony

docs/kernels.md
The name of the file with additional kernel options must include 
the kernel series name. Otherwise the script in [kernel/Dockerfile](https://github.com/linuxkit/linuxkit/blob/master/kernel/Dockerfile#L99)
will not apply it. So the example file name should be
`config-4.9.x-x86_64-foo` instead of `config-foo`.
=> A minor docs correction in 'Building and using custom kernels' section.

test/cases/020_kernel/000_config_4.4.x/test.sh, test/cases/020_kernel/001_config_4.9.x/test.sh, test/cases/020_kernel/006_config_4.14.x/test.sh, test/cases/020_kernel/007_config_4.15.x/test.sh, test/pkg/kernel-config/check-kernel-config.sh
Fixes #2807 
Expands the check-kernel-config.sh script to handle `x86_64` specific configs, and (unfortunately) some cases where configs existed in `x86_64` kernels before `arm64`, which complicated things a bit. Let me know if there's a different way you'd prefer to handle the conditions here please!
* Looked at what was failing in #2807, plus new tests added in #2908
* Added conditional blocks in the script for `x86_64` specific checks, and some that were either architecture dependent or kernel version dependent (e.g. `CONFIG_RANDOMIZE_BASE` which is in `x86_64` 4.4 but not in `arm64` until 4.6)
* Also found/fixed an issue with `oprofilefs` failing on the `arm64` kernel checks
- I performed these steps on both my local `x86_64` …
=> Fix support for arm kernel config tests

test/cases/020_kernel/000_config_4.4.x/test.yml, test/cases/020_kernel/001_config_4.9.x/test.yml, test/cases/020_kernel/006_config_4.14.x/test.yml, test/cases/020_kernel/007_config_4.15.x/test.yml, test/hack/test.yml, test/pkg/kernel-config/Dockerfile, test/pkg/kernel-config/build.yml
https://github.com/linuxkit/linuxkit/pull/2976 fixed the kernel config test for arm64. This PR updates the test to use the new package.
While at it also update it to the latest alpine abse image and restrict the build of the package to arm64 and amd64 (as these currently are the only arches which are supported)
=> Update kernel config test

scripts/push-manifest.sh, src/cmd/linuxkit/pkglib/manifest_push_script.go
`notary` 0.6.0 allows passing credentials via the `NOTARY_AUTH` env variable. Previously we had jump through hoops via an expect script to feed the credentials to `notary`.
=> Use NOTARY_AUTH instead of the expect gymnastics 

src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/tool/src/moby/config.go
This only includes https://github.com/moby/tool/pull/210 which
makes bind mounts into containers rshared not rprivate by default,
which makes debug easier as you can see them from the host.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Update moby tool vendoring

README.md, docs/packages.md, docs/platform-qemu.md
- Add notes on `s390x` to qemu and packages docs (resolves #2968)
- Clarify supported architectures in top level README
- Add more sub-projects to the list in the top-level README
- Remove security note from top-level README. We had spectre/meltdown fixed kernels for quite some time now.
=> Clarify s390x support in docs plus others small changes

kernel/Makefile
Looks like commit 9a88a5e98601 ("Upgrade -rt patches to
v4.14.29-rt25") accidentally added compiling -rt kernels
for s390x. Remove it.
=> kernel: Don't compile -rt kernels on s390x

src/cmd/linuxkit/pkglib/build.go
If you happen to be exactly on a tag then:
$ linuxkit pkg build --dev pkg/init
Building "ijc/init:dev"
Cannot release "v0.3" if not pushing
Do not try and infer a release if not pushing so this is possible again.
The subsequent check for `bo.release != "" && !bo.push` remains since the
caller could have used `WithRelease` but not `WithPush`. Our CLI never does
this, but a hypothetical other user of the library might.
=> pkg: build: do not infer a release if not pushing

pkg/init/etc/init.d/000-issue
$ git diff linuxkit.yml
diff --git a/linuxkit.yml b/linuxkit.yml
index e2ec829db..21b84e4ad 100644
--- a/linuxkit.yml
+++ b/linuxkit.yml
@@ -1,6 +1,6 @@
kernel:
image: linuxkit/kernel:4.14.32
-  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
+  cmdline: "console=ttyS0 console=foobar"
init:
- linuxkit/init:v0.3
- linuxkit/runc:v0.3
$ linuxkit  build linuxkit.yml
[...]
$ linuxkit run linuxkit
[...]
getty: cmdline has console=foobar but /dev/foobar is not a character device; not starting getty for foobar
linuxkit-2ae2c420a11c login: root (automatic login)
Welcome to LinuxKit!
NOTE: This system is namespaced.
The namespace you are currently in may not be the root.
(ns: getty) linuxkit-2ae2c420a11c:~# ls -l /proc/1/root/dev/foobar
-rw-r--r--    1 root     root           311 Apr  9 13:19 …
=> Avoid writing to tty devices which don't actually exist.

kernel/Dockerfile
For example kernel module signatures if you do not provide a key. So add
to the dependencies for kernel builds.
=> Some kernel builds need openssl binary for key generation

tools/alpine/packages
I am doing some upstream `runc` work with kernel keys and have
various other uses. No urgency so not updating the package
builds yet.
=> Add keyutils to packages

kernel/Dockerfile
```
* wg-quick: account for specified fwmark in auto routing mode
If we're doing automatic routing with default routes, but the config has
also specified an explicit fwmark, then use that explicit fwmark, even
if it's conflicting, since the administrator has explicitly opted into
using it. Also, when shutting down the interface, we only now remove the
fancy rules if we're in automatic routing mode with default routes.
* send: account for route-based MTU
It might be that a particular route has a different MTU than the
interface, via `ip route add ... dev wg0 mtu 1281`, for example. In this
case, it's important that we don't accidently pad beyond the end of the
MTU. We accomplish that in this patch by carrying forward the MTU from
the dst if it exists. We also add a unit test for this …
```
=> wireguard: upgrade to 0.0.20180420

kernel/Dockerfile, kernel/Makefile, kernel/config-4.9.x-x86_64, kernel/patches-4.9.x/0001-tools-build-Add-test-for-sched_getcpu.patch, kernel/patches-4.9.x/0002-perf-jit-Avoid-returning-garbage-for-a-ret-variable.patch, kernel/patches-4.9.x/0003-hv_sock-introduce-Hyper-V-Sockets.patch, kernel/patches-4.9.x/0004-vmbus-Don-t-spam-the-logs-with-unknown-GUIDs.patch, kernel/patches-4.9.x/0005-Drivers-hv-utils-Fix-the-mapping-between-host-versio.patch, kernel/patches-4.9.x/0006-Drivers-hv-vss-Improve-log-messages.patch, kernel/patches-4.9.x/0007-Drivers-hv-vss-Operation-timeouts-should-match-host-.patch, kernel/patches-4.9.x/0008-Drivers-hv-vmbus-Use-all-supported-IC-versions-to-ne.patch, kernel/patches-4.9.x/0009-Drivers-hv-Log-the-negotiated-IC-versions.patch, kernel/patches-4.9.x/0010-vmbus-fix-missed-ring-events-on-boot.patch, kernel/patches-4.9.x/0011-vmbus-remove-goto-error_clean_msglist-in-vmbus_open.patch, kernel/patches-4.9.x/0012-vmbus-dynamically-enqueue-dequeue-the-channel-on-vmb.patch, test/cases/020_kernel/001_config_4.9.x/test.yml, test/cases/020_kernel/011_kmod_4.9.x/Dockerfile, test/cases/020_kernel/011_kmod_4.9.x/test.sh, test/cases/020_kernel/011_kmod_4.9.x/test.yml
I've also recompiled arm64 and all x86_64 kernels to pick up the `-rt` kernels from https://github.com/linuxkit/linuxkit/pull/3010 and the WireGuard update from https://github.com/linuxkit/linuxkit/pull/3011. For s390x I plan to pick up the wireguard update with the next 4.14.x/4.16.x kernel update.
=> Update kernel to 4.9.95

linuxkit.yml
It is very out of date and misleading. It was mainly there to
show Prometheus metrics.
=> Remove the containerd config from the example

kernel/Dockerfile
```
* keygen-html: add zip file example
The alpha Android app now supports importing from .zip files, so the example
contrib code has been updated to show people how to trivially generate .zip
files from ... javascript. That's right, the WireGuard repo now contains some
more demo javascript.
* qemu: retry on 404 in wget for kernel.org race
Simple fix for build.wireguard.com's handling of new kernels.
* embeddable-wg-library: zero attribute padding
This imports 37c876b55a2c00424ccda5a300ab5fdec1d88b22 from upstream libmnl.
* allowedips: add selftest for allowedips_walk_by_peer
* allowedips: use native endian on lookup
* allowedips: produce better assembly with unsigned arithmetic
* allowedips: simplify arithmetic
A series of bitmath improvements make allowedips lookups sleeker and faster. …
```
=> wireguard: upgrade to 0.0.20180513

kernel/Dockerfile
```
* chacha20poly1305: add mips32 implementation
"The OpenWRT Commit" - this significantly speeds up performance on cheap
plastic MIPS routers, and presumably the remaining MIPS32r2 super computers
out there.
* timers: reinitialize state on init
* timers: round up instead of down in slack_time
* timers: remove slack_time
* timers: clear send_keepalive timer on sending handshake response
* timers: no need to clear keepalive in persistent keepalive
Andrew He and I have helped simplify the timers and remove some old warts,
making the whole system a bit easier to analyze.
* tools: fix errno propagation and messages
Error messages are now more coherent.
* wg-quick: use invoking shell in auto rooting
Rather than letting sudo use bash from PATH, we now have it use whatever bash
is currently …
```
=> wireguard: upgrade to 0.0.20180519

kernel/Dockerfile
```
* allowedips: set pointer to null before freeing
* ncat-client-server: do not always call sudo and use env bash
* qemu: bump default kernel for gcc 8.1
* compat: work around qcom 4.9 backports
The usual fixes.
* tools: fix OpenBSD build
* tools: always pass -v as first argument to install
Portability changes.
* wg-quick: darwin: rename namefile environment variable
* wg-quick: darwin: do not remove routes when no real interface
* wg-quick: freebsd: add new implementation
* wg-quick: openbsd: add new implementation
* wg-quick: support FreeBSD/Darwin search path
* wg-quick: better bash completion for non-renaming OSes
* wg-quick: allow enumeration of socket files
We now support OpenBSD and FreeBSD, in addition to macOS.
```
=> wireguard: upgrade to 0.0.20180524

kernel/Dockerfile
```
* compat: don't clash with get_random_u32 backports
This should allow running on recent Qualcomm msm8998 kernels.
* wg-quick: determine IPs when saving interface
* wg-quick: darwin: add multiple IP addresses
* wg-quick: freebsd: configure as p2p link
* wg-quick: darwin: set DNS servers after delay on route change
Usual set of wg-quick changes, since the recent cross platform additions.
* curve25519: x86_64: satisfy sparse
* curve25519: x86_64: make symbol static
* crypto: consistent constification
Small cleanups in the crypto primitives.
* chacha20poly1305: split up into separate files
* chacha20poly1305: combine stack variables into union
* chacha20poly1305: test scattergather functions too
* chacha20poly1305: test for authtag failure
We've reorganized our chapoly implementation and …
```
=> wireguard: upgrade to 0.0.20180531

test/cases/040_packages/023_wireguard/check.sh
The proposed change in https://github.com/linuxkit/linuxkit/pull/3030
seems to timeout on the wireguard test. Try 'poweroff -f' instead
of 'halt' to stop the test VM.
=> tests: Use poweroff instead of halt for wireguard test

projects/memorizer/memorizer.yml
Originally, Memorizer kernel fed inputs to add boot printouts from a debug tool, however, it creates unnecessary output. Remove the kernel boot option parameter.
Modify line in memorizer.yml
Rebuild and launch with 16+GB of ram using Qemu.
Remove poison parameter in Memorizer configuration
=> Memorizer: remove kasan poison on boot

src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/run_gcp.go
This was missing in the linuxkit CLI, even though we support it in the
metadata package.
Also add support to set a name different from the image name, so you can run multiple machines from one image easily.
Image from [Hippos Poop So Much That Sometimes All the Fish Die](https://www.theatlantic.com/science/archive/2018/05/hippos-poop-so-much-that-sometimes-all-the-fish-die/560486/)
=> Add support for userdata on GCP plus custom name

kernel/Dockerfile
The main commit is:
```
While we can re-create the kernel source code we don't have it
handily available in one place. This commit stashes the kernel
and the WireGuard source as /src/linux.tar.xz and
/src/wireguard.tar.xz in the kernel package.
This increases the size of the hub image by around 100MB.
```
In addition, I also added `-f` to the `curl` invocations which were missing it.
=> Stash kernel source and WireGuard source in the package

test/cases/040_packages/023_wireguard/check.sh
With PR #3030 the behaviour of poweroff/halt is changed. This
test relies on on-shutdown containers to be executed to display
the test result (service containers have their stdout redirected).
Use 'poweroff' (note, no '-f') to ensure that:
- the machine actually powers off
- the on-shutdown container is executed
Note, there are subtle differences between 'poweroff' and 'halt'
between hypervisors. With HyperKit, 'halt' actually works, but with
qemu/kvm, with 'halt' the process does not exit.
=> tests: Fix wireguard test shutdown

kernel/Dockerfile
```
* wg-quick: android: change name of intent
* wg-quick: android: delay setting users until end
`ndc users add` eventually invokes SOCK_DESTROY on user sockets, causing
them to reconnect. By delaying this until after routes are set, we
ensure that the sockets reconnect using the tunnel, rather than the old
route. This fixes push notifications on Android.
* chacha20: add missing include to header
Fixes a compile error on some kernels.
* tools: encoding: add missing static array constraints
Makes static analyzers happier.
* tools: support getentropy(3)
This lets us take advantage of both recent glibc calls as well as the long
standing getentropy functions on the BSDs.
* chacha20poly1305: use slow crypto on -rt kernels
In rt kernels, spinlocks call schedule(), which means preemption can't …
```
=> wireguard: upgrade to 0.0.20180613

examples/docker-for-mac.yml, pkg/binfmt/Dockerfile, pkg/binfmt/build.yml, pkg/binfmt/main.go, test/cases/040_packages/002_binfmt/test.yml
Rather than bind mounting binfmt_misc filesystem, mount a copy.
For some reason, bind mounting does not always seem to work,
sometimes the filesystem is empty. Mounting a fresh copy seems
a better solution, and simplifies things. The container does
need `CAP_SYS_ADMIN` but only on boot.
also cherry pick #3071 to use Debian for qemu as Alpine currently broken for networking.
fix #2710
=> Binfmt fixes

kernel/Dockerfile
```
* receive: don't toggle bh
The last snapshot caused a big performance regression, which we partially
revert here. This general matter, though, will be revisited in the future,
perhaps by switching to NAPI.
* main: test poly1305 before chacha20poly1305
* poly1305: give linker the correct constant data section size
While the default bfd linker did the right thing, gold would sometimes merge
section incorrectly because of an incorrect section length field, resulting in
wrong calculations.
* simd: add missing header
Fixes a compile error on a few odd kernels.
* global: fix a few typos
* manpages: eliminate whitespace at the end of the line
* tools: fix misspelling of strchrnul in comment
Cosmetic fixups.
* global: use ktime boottime instead of jiffies
* global: use fast boottime instead …
```
=> wireguard: upgrade to 0.0.20180625

tools/alpine/Dockerfile
fixes #3079 
Changed references to `uname -m` in the context of an apk command to `apk --print-arch`
Build tools/alpine with `make` on different architectures
When dealing with apk, `uname -m` doesn't always match the architecture
name that apk uses. Instead `apk --print-arch` is used.
=> Use apk --print-arch to discover architecture

Makefile
fixes https://github.com/linuxkit/linuxkit/issues/1863
Fixed the `Makefile` for Windows by:
* setting `GOOS` to `windows` on Windows
* appending `.exe` to binaries on Windows
Running `make` on Windows now succeeds, although it still requires a unixy shell (cygwin, msys, …).
=> Fix windows build

docs/faq.md, pkg/getty/etc/motd, pkg/sshd/etc/motd
fixes #3087 
I fixed the `getty` and `sshd` `motd` to report the correct `ctr` command usage, as the indicated namespace is incorrect.
I also added two new FAQ entries adding a bit more information that I gathered while troubleshooting my issue in #3087. I think this could help other users as not everybody knows exactly how `linuxkit` or `containerd` works.
With my hands, my brain and a text editor :)
I'm not a native English speaker, so you probably should proof-read what I wrote :)
Fixed incorrect namespace in motd
Enhanced FAQ with troubleshooting advices
Thanks !
=> Some FAQ and motd update

kernel/Dockerfile
```
* device: print daddr not saddr in missing peer error
* receive: style
Debug messages now make sense again.
* selftest: ratelimiter: improve chance of success via retry
* qemu: bump default kernel version
* qemu: decide debug kernel based on KERNEL_VERSION
Some improvements to our testing infrastructure.
* receive: use NAPI on the receive path
This is a big change that should both improve preemption latency (by not
disabling it unconditionally) and vastly improve rx performance on most
systems by using NAPI. The main purpose of this snapshot is to test out this
technique.
```
=> wireguard: upgrade to 0.0.20180708

docs/logging.md, examples/logging.yml, pkg/kmsg/Dockerfile, pkg/kmsg/build.yml, pkg/kmsg/main.go, pkg/kmsg/vendor.conf, pkg/kmsg/vendor/github.com/euank/go-kmsg-parser/LICENSE, pkg/kmsg/vendor/github.com/euank/go-kmsg-parser/README.md, pkg/kmsg/vendor/github.com/euank/go-kmsg-parser/kmsgparser/kmsgparser.go, pkg/kmsg/vendor/github.com/euank/go-kmsg-parser/kmsgparser/log.go, pkg/logwrite/Dockerfile, pkg/logwrite/build.yml, pkg/logwrite/logwrite.go, test/cases/040_packages/030_logwrite/check.sh, test/cases/040_packages/030_logwrite/test.sh, test/cases/040_packages/030_logwrite/test.yml, test/cases/040_packages/031_kmsg/check.sh, test/cases/040_packages/031_kmsg/test.sh, test/cases/040_packages/031_kmsg/test.yml
- added `pkg/logwrite` which can connect to `memlogd` and stream logs to files in `/var/log`, with log rotation (Fixes #3072)
- added `pkg/kmsg` which connects to `/dev/kmsg` and logs the kernel log
This builds on top of the infrastructure proposed in #3085 (note I rebased this PR on top of that branch but only the last few patches are different)
First build and run the logging example:
```
cd examples
linuxkit build -disable-content-trust logging.yml
linuxkit run logging
```
Then execute `watch ls -l /var/log` in the terminal. After a while it should look like:
```
total 72
-rw-r--r--    1 root     root           405 Jul  6 16:59 getty.out
-rw-r--r--    1 root     root           969 Jul  6 16:59 kmsg.out
-rw-r--r--    1 root …
```
=> Support log rotation and logging of /dev/kmsg

examples/logging.yml, pkg/logwrite/logwrite.go, test/cases/040_packages/030_logwrite/check.sh, test/cases/040_packages/030_logwrite/test.yml, test/cases/040_packages/031_kmsg/check.sh, test/cases/040_packages/031_kmsg/test.yml
Without this change, logfiles just use the log name provided by init, typically `<name>.err` and `name.out`. This PR adds `.log` as generic extension to all log files.
While at it, I also simplified the logwrite code a tiny bit and fixed up the test and example.
/cc @djs55
=> Add '.log' as file extension to 'pkg/logwrite' files

tools/alpine/packages, tools/alpine/packages.aarch64, tools/alpine/packages.x86_64, tools/alpine/versions.aarch64, tools/alpine/versions.s390x, tools/alpine/versions.x86_64
This adds most of the packages needed to add the iovisor/bcc tools to LinuxKit as per #3106.
`python` and `iperf` were omitted as I don't think they are essential. Also `luajit-dev` is not avail on s390x so the build of bcc might need to take that into account (/cc @
kmjohansen).
The new package is: `linuxkit/alpine:cbf183a92cb4800c4129c2b9bb6e4d3eb3226330` and the size increased by about 140MB to about 600MB on x86.
=> Add packages needed for iovisor/bcc

docs/releasing.md, test/cases/020_kernel/010_kmod_4.4.x/Dockerfile, test/cases/020_kernel/011_kmod_4.9.x/Dockerfile, test/cases/020_kernel/016_kmod_4.14.x/Dockerfile, test/cases/020_kernel/019_kmod_4.17.x/Dockerfile
For the past releases I've missed that we also use `linuxkit/alpine` in some of the test cases. Update to the alpine base for test cases and also add the instructions to the release doc. While at it also improve some of the commit messages.
=> Update linuxkit/alpine for test cases

examples/aws.yml, examples/docker-for-mac.yml, examples/gcp.yml, examples/openstack.yml, examples/packet.yml, examples/scaleway.yml, examples/vultr.yml, pkg/metadata/provider_gcp.go
Tried to SSH on a linuxkit VM on GCP.
Got the following message on the serial console:
```
2018/07/14 23:19:48 GCP: Probe succeeded
2018/07/14 23:19:48 GCP: Failed to get ssh data: Failed to get sshKeys: GCP: Status not ok: 404
2018/07/14 23:19:48 GCP: Failed to get user-data: GCP: Status not ok: 404
```
```
$ gcloud compute ssh myinstance
```
According to the [GCP doc](https://cloud.google.com/compute/docs/storing-retrieving-metadata) the URL is not `sshKeys` but `ssh-keys` now.
=> Change GCP metadata SSH keys URL

kernel/Dockerfile
```
* tools: only error on wg show if all interfaces fail
wg(8) now has a more reasonable error code semantic.
* receive: account for zero or negative budget
A correctness fix that no other drivers implement but that we really should
be doing anyway.
* recieve: disable NAPI busy polling
This avoids adding one reference per peer to the napi_hash hashtable, as
normally done by netif_napi_add(). Since we potentially could have up to
2^20 peers this would make busy polling very slow globally. This approach is
preferable to having only a single napi struct because we get one gro_list
per peer, which means packets can be combined nicely even if we have a large
number of peers. This is also done by gro_cells_init() in net/core/gro_cells.c.
* receive: use gro call instead of plain call
This …
```
=> wireguard: upgrade to 0.0.20180718

examples/logging.yml, pkg/memlogd/cmd/logwrite/main.go, test/cases/040_packages/030_logwrite/test.yml, test/cases/040_packages/031_kmsg/test.yml
Note there is a confusing name clash between the `pkg/logwrite` package which writes logs to disk and the command-line wrapper program `cmd/logwrite` (part of the `memlogd` package) modified here.
In e8786d73bb5665b4d548781949e318af6967be03 the logwrite package will automatically append .log to every log filename.
In 5201049f2ccb92d3933ab39f1a1a498c09dda669 the init package will send stderr of a service `s` to a log named `s` and the stdout to `s.out`. Therefore the files we create on disk are `s.log` and `s.out.log`.
This patch modifies the memlogd `logwrite` command-line wrapper to use the same convention.
```
/ # ./pkg/memlogd/cmd/logwrite/logwrite -n hello ls /fooo
/ # ls -1 /var/log
...
hello.log
...
/ # cat /var/log/hello.log …
```
=> memlogd/logwrite: use the same naming convention as init

src/cmd/linuxkit/moby/output.go, tools/mkimage-iso-bios/Dockerfile, tools/mkimage-iso-efi/Dockerfile, tools/mkimage-qcow2-efi/Dockerfile, tools/mkimage-raw-bios/Dockerfile, tools/mkimage-raw-efi/Dockerfile, tools/mkimage-squashfs/Dockerfile
Quite a few of the `mkimage-` images were not build from `scratch` and thus included the entire alpine base, making them rather large. Fix it.
=> Fix mkimage- builds

src/cmd/linuxkit/moby/output.go, test/cases/000_build/000_formats/004_aws/test.sh, test/cases/000_build/000_formats/008_raw_bios/test.sh, test/cases/000_build/000_formats/009_raw_efi/test.sh, test/cases/000_build/000_formats/011_kernel+squashfs/test.sh, test/cases/000_build/000_formats/012_kernel+iso/test.sh, tools/mkimage-iso/Dockerfile, tools/mkimage-iso/build.yml, tools/mkimage-iso/make-iso
We already have kernel+squashfs and kernel+initrd. Booting a kernel with a read-only ISO might also be useful.
resolves #3133
=> Add kernel+iso output

docs/packages.md, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go
This adds adds a new `sources` field to the `build.yml` where one can specify additional source directories for the package build outside the package directory. This is useful for sharing files, such as vendored go code, between packages.
If `sources` are specified, the package hash is calculated as the `sha1` of the strings of the git tree hashes of all the externals sources and the package directory. Therefore, `sources` need to be under git revision control.
`sources` are specified as a `src:dst` pair, where `src` can be a relative path the package directory and `dst` is the destination with the docker build context.
The `sources` features is implemented by `tar`ing up (and rewriting the paths) of the sources and pipe them to `stdin` of the `docker` process used to build the package. …
=> Allow external directories for 'linuxkit pkg build'

src/cmd/linuxkit/moby/image.go
fixes #3091 
While processing the content of a tar image, linuxkit's moby tool was
blindly reusing the original tar format.
Moreover it locates the file under a new prefix, so if the original
file was stored as USTAR in the original archive, the filename length
and new prefix could be greater than the USTAR limit leading
to a fatal error.
The fix is to always enforce PAX format on all copied files from the
original image archive.
Use the following minimal yaml:
~~~yaml
kernel:
image: linuxkit/kernel:4.9.87
cmdline: "console=ttyS0"
init:
- linuxkit/init:6061875ba11fd9c563fda6234b103ed9997ff782
- linuxkit/runc:52ecfdef1ae051e7fd5ac5f1d0b7dd859adff015
- linuxkit/containerd:13f62c61f0465fb07766d88b317cabb960261cbb
onboot:
- name: …
=> Fix #3091 enforce all outgoing tar files to use PAX

docs/platform-vbox.md, src/cmd/linuxkit/run_vbox.go
fixes #3140
For an internal project where I needed to produce a VirtualBox based vagrant box, I started running a linuxkit VM with the `run vbox` command.
This specific VM requires to have an additional disk and two network adapter.
Unfortunately, adding an additional disk produces a VirtualBox error because there's no port 2 on IDE Controller (only port 0 and 1). Also adding more than one additional disk couldn't work because all would have used port 2, and IDE controllers only allow for 4 devices (one 
And `run vbox` only supports one network adapter.
I modified the `run vbox` code to use a SATA controller for any additional disks instead of the IDE controller, because it can host much more drives.
I also changed the code to allow to specify more than one `-networking` …
=> Enhance `run vbox` to support multiple disks and network adapters

kernel/Dockerfile
```
* receive: check against proper return value type
Ensure error counters are correct in the receive path.
* embeddable-wg-library: do not left shift negative numbers
Avoids implementation-defined C behavior and also improves performance.
* wg-quick: android: allow package to be overridden
* wg-quick: android: remove compat code
Small android fixes.
* qemu: show log if process crashes
* qemu: update musl and kernel
The usual QEMU suite bump.
* curve25519-x86_64: tighten the x25519 assembly
Small performance optimization from Samuel.
The wide multiplication by 38 in mul_a24_eltfp25519_1w is redundant:
(2^256-1) * 121666 / 2^256 is at most 121665, and therefore a 64-bit
multiplication can never overflow.
* curve25519-x86_64: tighten reductions modulo 2^256-38
Small performance …
```
=> wireguard: upgrade to 0.0.20180802

kernel/Dockerfile
```
* send: switch handshake stamp to an atomic
Rather than abusing the handshake lock, we're much better off just using
a boring atomic64 for this. It's simpler and performs better. Also, while
we're at it, we set the handshake stamp both before and after the
calculations, in case the calculations block for a really long time waiting
for the RNG to initialize. 
* compat: better atomic acquire/release backport
This should fix compilation and correctness on several platforms.
* crypto: move simd context to specific type
This was a suggestion from Andy Lutomirski on LKML.
* chacha20poly1305: selftest: use arrays for test vectors
We no longer have lines so long that they're rejected by SMTP servers.
* qemu: add easy git harness
This makes it a bit easier to use our qemu harness for testing …
```
=> wireguard: upgrade to 0.0.20180809

projects/compose/Makefile, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/compose/image/load-images-and-compose.sh
Updated the compose project as follows:
* remove `rm` of pre-loaded tar files in static as they are in a read-only filesystem
* Updated docker version to `18.06`
* Bumped memory for static in Makefile's `run-static` target to handle the larger file
* Added `getty` to the compose examples
* Removed static list of images from `Makefile` and just looked for them dynamically in the compose file
Changed the `linuxprojects/compose` image, updated and pushed, then changed the `Makefile` and the two linuxkit ymls
For both static and dynamic, build the `lkt` images, run them, check the output:
1. build: `make static` or `make dynamic`
2. run: `make run-static` or `make run-dynamic`
3. Wait for the console to come up
4. Check the logs in …
=> Update and fix compose project

examples/docker-for-mac.md
Updated the socket name in the documentation file `examples/docker-for-mac.md`
=> Fix typo in examples/docker-for-mac.md

kernel/Dockerfile
```
* wg-quick: darwin: prefer system paths for tools
The only things wg-quick(8) needs from Homebrew are bash(1) and wg(8).
Other than that, it's explicitly coded against the native system
utilities. Since wg-quick(8) and bash(1) are invoked in auto_su by their
full absolute path (via $SELF and $BASH, respectively), we can simply
set the $PATH to be prefixed by the default system binary paths. This
way, if users install tools that conflict with system tools -- such as
GNU coreutils -- we won't accidently call those.
* wg-quick: check correct variable for route deduplication
This should avoid adding duplicate routes when adding the allowed IPs as
interface routes automatically.
* Kconfig: use new-style help marker
* global: run through clang-format
* uapi: reformat
* global: satisfy …
```
=> wireguard: upgrade to 0.0.20180904

src/cmd/linuxkit/pkglib/build.go
Fixed `linuxkit pkg build …` on Windows.
Using `filepath` primitives instead of manipulating file paths manually takes care of platform specific formats.
Before
```
$ linuxkit.exe pkg build -disable-cache -hash current -org docker desktop-host-tools
Building "docker/desktop-host-tools:current"
you are not authorized to perform this operation: server returned 401.
No image pulled, continuing with build
Sending build context to Docker daemon  50.56MB
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
exit status 1
```
After
```
$ linuxkit.exe pkg build -disable-cache -hash current -org docker desktop-host-tools
Building "docker/desktop-host-tools:current"
you are not authorized to perform this operation: …
```
=> Fix relative path under Windows

src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/image.go
Sorry for opening a PR per fix, It's just I'm so glad I'm making progress every time. 😋 
Fixed more file path handling on Windows.
On Windows `os.PathSeparator` is `\` but here it's all unix file paths being manipulated.
And not really related but `byte('/')` is really just `'/'`.
Before
```
../bin/linuxkit build  -format iso-efi -name docker-for-mac -dir build image.yml image-mac.yml
…
Create outputs:
build\docker-for-mac-efi.iso
[31mFATA[0m[0096] Error writing outputs: Error writing iso-efi output: docker run linuxkit/mkimage-iso-efi:248673cd3784eb3664d0f80b5bd31829465ca784 failed: exit status 1 output:
```
(errors right away with no output, no logs, no clue …)
Now
```
../bin/linuxkit build  -format iso-efi -name …
```
=> Fix path separator on Windows

kernel/Dockerfile
```
* blake2s-x86_64: fix whitespace errors
* crypto: do not use compound literals in selftests
* crypto: make sure UML is properly disabled
* kconfig: make NEON depend on CPU_V7
* poly1305: rename finish to final
* chacha20: add constant for words in block
* curve25519-x86_64: remove useless define
* poly1305: precompute 5*r in init instead of blocks
* chacha20-arm: swap scalar and neon functions
* simd: add __must_check annotation
* poly1305: do not require simd context for arch
* chacha20-x86_64: cascade down implementations
* crypto: pass simd by reference
* chacha20-x86_64: don't activate simd for small blocks
* poly1305-x86_64: don't activate simd for small blocks
* crypto: do not use -include trick
* crypto: turn Zinc into individual modules
* chacha20poly1305: relax simd between …
```
=> wireguard: upgrade to 0.0.20180918

kernel/Dockerfile
```
* poly1305: better module description
* blake2s: simplify final function
* poly1305: no need to trick gcc 8.1
* chacha20: prefer crypto_xor_cpy to avoid memmove
* poly1305: account for simd being toggled off midway
* crypto: do not waste space on selftest items
* poly1305-mips32r2: remove all reorder directives
* chacha20-mips32r2: fix typo to allow reorder again
* chacha20-mips32r2: remove reorder directives
* chacha20-arm: go with Ard's version to optimize for Cortex-A7
* chacha20-mips32r2: use simpler calling convention
* chacha20-mips32r2: reduce jumptable entry size and stack usage
* chacha20: add chunked selftest and test sliding alignments and hchacha20
* crypto-arm: rework KERNEL_MODE_NEON handling
* chacha20-arm: use new scalar implementation
* curve25519-fiat32: work around …
```
=> wireguard: upgrade to 0.0.20181006

src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/push_gcp.go, src/cmd/linuxkit/run_gcp.go
Signed-off-by: Eric Briand <eric.briand@gmail.com>
Validate that there is the project name given when using run and push in gcp.
Had the check of projetName in GCP client creation
linuxkit run or linuxkit push without giving projectname should result to the output : 
```
FATA[0000] Unable to connect to GCP: the project name is not specified
```
GCP client - Notify when project is not set
=> GCP: validate project name

kernel/Dockerfile
```
* compat: don't output for grep errors
* compat: look in Kbuild and Makefile since they differ based on arch
* create-patch: blacklist instead of whitelist
This should solve the last of the compat issues introduced with the revamped
build system and upstream changes.
* qemu: kill after 20 minutes
Our test suite now accounts for hangs.
* global: prefix functions used in callbacks with wg_
* global: rename struct wireguard_ to struct wg_
* global: more nits
* timers: avoid using control statements in macro
* allowedips: remove control statement from macro by rewriting
* device: use textual error labels always
* global: give if statements brackets and other cleanups
* main: change module description
* main: get rid of unloaded debug message
Stylistic cleanups from upstream.
* netlink: do …
```
=> wireguard: upgrade to 0.0.20181018

kernel/Dockerfile
```
* Zinc no longer ships generated assembly code. Rather, we now
bundle in the original perlasm generator for it. The primary purpose
of this snapshot is to get testing of this.
* Clarify the peer removal logic and make lifetimes more precise.
* Use READ_ONCE for is_valid and is_dead.
* No need to use atomic when the recounter is mutex protected.
* Fix up macros and annotations in allowedips.
* Increment drop counter when staged packets are dropped.
* Use static constants instead of enums for 64-bit values in selftest.
* Mark large constants as ULL in poly1305-donna64.
* Fix sparse warnings in allowedips debugging code.
* Do not use wg_peer_get_maybe_zero in timer callbacks, since we now can
carefully control the lifetime of these functions and ensure they never
execute after dropping …
```
=> wireguard: upgrade to 0.0.20181115

kernel/Dockerfile
```
* chacha20,poly1305: fix up for win64
* poly1305: only export neon symbols when in use
* poly1305: cleanup leftover debugging changes
* crypto: resolve target prefix on buggy kernels
* chacha20,poly1305: don't do compiler testing in generator and remove xor helper
* crypto: better path resolution and more specific generated .S
* poly1305: make frame pointers for auxiliary calls
* chacha20,poly1305: do not use xlate
This should fix up the various build errors, warnings, and insertion errors
introduced by the previous snapshot, where we added some significant
refactoring. In short, we're trying to port to using Andy Polyakov's original
perlasm files, and this means quite a lot of work to re-do that had stableized
in our old .S.
```
=> wireguard: upgrade to 0.0.20181119

contrib/crosvm/Dockerfile, contrib/crosvm/README.md, src/cmd/linuxkit/build.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/linuxkit.go
This restructures the `linuxkit build` subcommand to:
- stash the kernel image in an internal buffer
- add a new `-vmlinux` build option to decompress the kernel
- decompress the kernel into an internal buffer
It also updates `crosvm` to the latest commit and updates the instructions to use the `-vmlinux` build option.
The resulting vmlinux image is binary identical to using the `extract-vmlinux` script from the Lnux kernel `./script` directory. The resulting kernel boots fine on `crosvm` but there is no interactive console (same as with manually extracting the kernel).
The support is experimental in the sense that it assume the fist gzip header found in the vmlinux image is the kernel image and that we do not check the resulting vminux image.
resolves #3215
=> Add experimental support for building uncompressed kernels

pkg/bpftrace/Dockerfile, pkg/bpftrace/build.yml, test/cases/040_packages/002_bpftrace/check.sh, test/cases/040_packages/002_bpftrace/test.sh, test/cases/040_packages/002_bpftrace/test.yml
This PR adds [bpftrace](https://github.com/iovisor/bpftrace) as a package to linuxkit. It includes all the necessary components and directory structures in order to build a bpftrace inside of a docker container.
Addresses: https://github.com/linuxkit/linuxkit/issues/3201
I started off by looking at existing packages for a reference model of how to structure a package in linuxkit. I also read the https://github.com/linuxkit/linuxkit/blob/master/docs/packages.md doc.
You can build it locally to test it out using the following command:
```linuxkit pkg build -org=<orgname> -disable-content-trust <path/to/bpftrace>```
This commit adds bpftrace to linuxkit packages and addresses the issue: …
=> pkg/bpftrace: Add bpftrace as a core pkg

kernel/Dockerfile
```
* jerry-rig: replace S_shipped with pl
This fixes our jerry rig script, so that people can patch WireGuard into
arbitrary kernel trees, instead of building as a standalone module.
* chacha20,poly1305: simplify perlasm fanciness
Numerous cleanups and correctness fixes in the assembly generators.
* compat: don't undef BUILD_BUG_ON for Clang >=8
The clang bug was finally fixed upstream, so we remove the workaround, while
retaining the hack in our compat layer.
* embeddable-wg-library: do not warn on unrecognized netlink attributes
This brings behavior into parity with wg(8), and also allows more graceful
addition of netlink attributes.
* chacha20: do not define unused asm function
This not only decreases code size, but also makes PaX's RAP happier.
* compat: account for Clang CFI
It …
```
=> wireguard: upgrade to 0.0.20181218

tools/qemu/Dockerfile
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> Missing s390x in the switch for qemu Dockerfile

projects/clear-containers/kernel/kernel_config
This PR should fix issue #3172 by enabling CAN network module for `clear-containers` within kernel flag config. This feature works for Linux Kernel 4.12 and above. 
By enabling kernel flag `CONFIG_CAN` to load this module. This namespace is introduced in [linux/linux-kernel@4.12](/torvalds/linux/tree/v4.12/drivers/net/can). After extension is loaded, we may bring up new `vcan` devices in container environment.
Built against 4.12, or higher version supported within linuxkit kernel. Once built, we may either force or set bootable module. No patch for previous kernels, given the feature is proposed for upstream. Not implemented or tested in landlock since KSPP. Host machine using Kernel 4.12. **Not tested on MacOS nor equivalent …
=> Enable CAN networking subsystem

README.md
Signed-off-by: Ben Allen <bsallen@alcf.anl.gov>
Quick change to fix broken link in README.md to ADOPTERS.md
Fix broken link in README.md to ADOPTERS.md
=> Fix link to ADOPTERS.md

kernel/Dockerfile.zfs
This change makes `make -C kernel build_zfs_4.14.x` succeed.
Closes #2950.
=> Use latest stable release of ZFS

kernel/Dockerfile
* tools: curve25519: handle unaligned loads/stores safely
This should fix sporadic crashes with `wg pubkey` on certain architectures.
* netlink: auth socket changes against namespace of socket
In WireGuard, the underlying UDP socket lives in the namespace where the
interface was created and doesn't move if the interface is moved. This
allows one to create the interface in some privileged place that has
Internet access, and then move it into a container namespace that only
has the WireGuard interface for egress. Consider the following
situation:
1. Interface created in namespace A. Socket therefore lives in namespace A.
2. Interface moved to namespace B. Socket remains in namespace A.
3. Namespace B now has access to the interface and changes the listen
port and/or fwmark of socket. Change …
=> wireguard: upgrade to 0.0.20190123

kernel/Dockerfile
```
* wg-quick: freebsd: allow loopback to work
FreeBSD adds a route for point-to-point destination addresses. We don't
really want to specify any destination address, but unfortunately we
have to. Before we tried to cheat by giving our own address as the
destination, but this had the unfortunate effect of preventing
loopback from working on our local ip address. We work around this with
yet another kludge: we set the destination address to 127.0.0.1. Since
127.0.0.1 is already assigned to an interface, this has the same effect
of not specifying a destination address, and therefore we accomplish the
intended behavior. Note that the bad behavior is still present in Darwin,
where such workaround does not exist.
* tools: remove unused check phony declaration
* highlighter: when subtracting …
```
=> wireguard: upgrade to 0.0.20190227

src/cmd/linuxkit/moby/output.go, tools/mkimage-rpi3/Dockerfile
Update commit hash to include updated RPi firmware
Attempt to boot a RPi and expect the power LED to remain on, and ACT to not flash with a debug code.  If successful, expect uboot to log to both serial consol and HDMI.
Vendor RPi firmware blob license
Update RPi3 firmware to fix startup on newer kit
---
This is a potential fix for #3324, however the fix will be when the new image is updated in `src/cmd/linuxkit/moby/output.go`.  I assume this must merge before an image is produced that can provide an updated hash for `src/cmd/linuxkit/moby/output.go`?
=> Update RPi firmware

src/cmd/linuxkit/moby/output.go, tools/mkimage-rpi3/Dockerfile
Update Raspberry Pi firmware used in mkimage-rpi3 to the latest stable
version to support newer hardware models such as the 3B+
Signed-off-by: Richard Connon <richard@connon.me.uk>
Updated the version of the raspberry pi firmware used by mkimage-rpi3
Modified the commit sha referenced in the Dockerfile
Build an image using mkimage-rpi3 and test it on newer hardware such as a raspberry pi 3B+
Update referenced Raspberry Pi firmware to 1.20190517
13.jpg)
=> Update referenced Raspberry Pi firmware

pkg/runc/Dockerfile
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>
Update opencontainers/runc to v1.0.0-rc8
Updated the commit hash based on the releases page here: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc8
Build the linuxkit/runc Dockerfile
Updated the opencontainers/runc Dockerfile to the latest v1.0.0-rc8 version.
=> Update opencontainers/runc to v1.0.0-rc8

src/cmd/linuxkit/moby/docker.go
This stops the output from also being copied to logs if the user
has a log driver configured.
=> Do not use a log driver while running containers

src/cmd/linuxkit/moby/output.go, tools/mkimage-rpi3/Dockerfile, tools/mkimage-rpi3/boot.script, tools/mkimage-rpi3/make-rpi3
Support selecting devicetree for raspberry pi 3B vs 3B+ dynamically
Updated UBoot to a version which can detect the raspberry pi 3B+ correctly.
Install both device tree binaries.
Select the correct binary using the fdtfile variable populated by UBoot.
Boot a raspberry pi 3B+ and run
`cat /proc/device-tree/model`
Should output correct model information.
Support selecting devicetree for raspberry pi 3B vs 3B+ dynamically
=> Support for dynamic selection of Raspberry Pi DTB

examples/aws.yml, examples/azure.yml, examples/cadvisor.yml, examples/dm-crypt-loop.yml, examples/dm-crypt.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/hostmount-writeable-overlay.yml, examples/node_exporter.yml, examples/openstack.yml, examples/packet.yml, examples/rt-for-vmware.yml, examples/scaleway.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, examples/wireguard.yml, linuxkit.yml, pkg/rngd/cmd/rngd/main.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/ima-namespace/ima-namespace.yml, projects/miragesdk/examples/fdd.yml, projects/shiftfs/shiftfs.yml, test/cases/030_security/000_docker-bench/test.yml
Linux has documented but somewhat unusual behavior around
SIGSTOP/SIGCONT and certain syscalls, of which epoll_wait(2) is one.  In
this particular case, rngd exited unexpectedly after getting ptrace'd
mid-epoll_wait.  Fix this by handling EINTR from this syscall, and
continuing to add entropy and wait.
Signed-off-by: Krister Johansen <krister.johansen@oracle.com>
Changed rngd so that it will no longer exit 1 upon being ptrace'd.
This change requires that the error handling around the `epoll_wait(2)` in rngd be modified so that it can cope with receiving an EINTR (or any temporary error) and continue instead of exiting.
I validated this by running `strace(1)` against `rngd`.  Prior to the fix it would exit moments after the tracer …
=> rngd exits after being stopped and resumed

kernel/Dockerfile
Kernel series 5.1.x requires openssl headers to compile scripts/extract-cert.c.
Added openssl-dev headers to the kernel/Dockerfle
Edited the Dockerfile.
cd kernel && make build_5.1.x
Added openssl-dev dependency to kernel compilation Dockerfile.
=> Update kernel Dockerfile with openssl-dev dep

kernel/Dockerfile.zfs
Updated ZFS to 0.8.1 to be able to use its native encryption (added in 0.8.0)
Updated kernel/Dockerfile.zfs and tested with kernel 4.19.49
Tested on docker-for-mac with this zfs.yml
```
kernel:
image: test/kernel:<tag-from-make-command>
cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
- test/zfs-kmod:<tag-from-make-command>
- linuxkit/init:v0.7
- linuxkit/runc:v0.7
- linuxkit/containerd:v0.7
- linuxkit/ca-certificates:v0.7
onboot:
- name: sysctl
image: linuxkit/sysctl:v0.7
- name: modprobe
image: linuxkit/modprobe:v0.7
command: ["modprobe", "-a", "zfs"]
services:
- name: getty
image: linuxkit/getty:v0.7
env:
- INSECURE=true
- name: rngd
image: linuxkit/rngd:v0.7
- name: dhcpcd
image: …
```
=> Update zfs to 0.8.1

examples/docker-for-mac.yml, examples/swap.yml, pkg/swap/swap.sh
Speed up swap onboot container.
`swapon || (dd && mkswap)`  instead of `dd && mkswap && swapon`. 
Without this PR, container log always show dd output. With the PR, it appears only once.
pkg/swap: create swap file only if absent.
=> Create swap file only if absent

kernel/Dockerfile.kconfig
`make kconfig` was broken, I fixed the issues by updating 
the urls used to download linux kernel images from kernel.org
Updated kernel/Dockerfile.kconfig
run `make kconfig`
=> Fixed urls used to download kernel images from kernel.org in kernel/Dockerfile.kconfig, used by make kconfig

examples/packet.yml, pkg/firmware-all/Dockerfile, pkg/firmware/Dockerfile
The `linuxkit/firmware` package stored firmware in `/lib/firmware/<driver>/<fw-image>/<fw-image>` when it should have stored it in `/lib/firmware/<driver>/<fw-image>`.
This fixes https://github.com/linuxkit/linuxkit/issues/3392
While at it, also use a newer kernel to figure out which modules to install and update to the latest firmware images.
=> Fix path in firmware image (and update while at it)

docs/packages.md, src/cmd/linuxkit/pkglib/docker.go
Also accepts upper-case `FTP_PROXY` or `ALL_PROXY`
We already support `http_proxy`/`HTTP_PROXY`, `https_proxy`/`HTTPS_PROXY`, `no_proxy`/`NO_PROXY` env vars to add build args. This does:
1. Adds support for `ftp_proxy` docker standard build-arg
2. Adds support for non-docker standard but socks standard `all_proxy`/`ALL_PROXY`
3. Adds documentation about using proxies when building
4. Fixes bug in building args wherein if build args are present, has them twice and overrides existing args.
Changed `src/cmd/linuxkit/pkglib/docker.go` and `docs/packages.md`
Run `lkt pkg build` with the env vars set and `-v` to see the output
Fixes bug in package …
=> Add docker-standard ftp_proxy + socks-standard all_proxy env vars

pkg/getty/usr/bin/rungetty.sh
Added deduplication logic to `linuxkit/getty` so that if the same line appears twice as `console=`, it will only start each once.
Also logs what it is doing.
Fixed [2741](https://github.com/linuxkit/linuxkit/issues/2741)
Updated `/usr/bin/rungetty.sh`
1. Run a linuxkit `.yml` file with duplicate `console=` lines
```yml
cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttyS0 console=tty0"
```
2. `moby build`
3. `linuxkit run`
4. Log in, see that `/var/log/getty.out.log` shows it starting only once. Also verify with `ps -ef` if you want.
Prevent `getty` from starting getty twice for same tty
**- A picture of a cute animal (not mandatory but …
=> Keep track of processed ttys and only start same one once

kernel/Dockerfile
Make Intel microcode available for static build in the kernel using `CONFIG_EXTRA_FIRMWARE`
Move the code downloading Intel microcode in `kernel/Dockerfile` earlier in the process, and copy it to `/lib/firmware` where Linux build system will look for it.
It is still copied in the `out/` directory and so that it is still available for addition in a 'ucode:' section in linuxkit.yml
Build a kernel with, for instance: 
```
CONFIG_EXTRA_FIRMWARE="intel-ucode/06-03-02"
```
and verify that it doesn't complain.
Move microcode download earlier in Dockerfile so it's available to `CONFIG_EXTRA_FIRMWARE`.
=> Move microcode download earlier in Dockerfile

src/cmd/linuxkit/build.go, src/cmd/linuxkit/moby/output.go
`dockerRun` method was called with trust=true only. `linuxkit build` didn't respect the `-disable-content-trust` parameter in the output phase.
Hopefully it will fix this error (even if a previous docker pull succeeded, even with content trust disabled):
`time="2019-08-07T18:01:02Z" level=fatal msg="Error writing outputs: Error writing kernel+iso output: docker pull linuxkit/mkimage-iso:3d81e29b28ddf739becf10758eb6077b198d26d8 failed: exit status 1 output:\n"`
We have it once a day on the Docker Desktop CI.
Pass the trust parameter.
`linuxkit -v build` with and without parameter `-disable-content-trust`. A log will appear when creating output.
**- A picture of a cute animal (not mandatory but …
=> Add trust parameter for docker pull in moby.Formats

examples/cadvisor.yml, examples/dm-crypt-loop.yml, examples/dm-crypt.yml, examples/docker-for-mac.yml, examples/docker.yml, examples/swap.yml, pkg/format/format.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/005_by_device_force/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
I changed the `-l` flag to `-L` because in the current version (`v.0.7`) of `LinuxKit/format` the `mkfs.btrfs` `-l` flag means 'leafsize'. The `-L` flag means label
n/a
Verified the fix on a local build.
Fix label argument mkfs.btrfs
=> Fix label argument mkfs.btrfs

src/cmd/linuxkit/moby/config.go
Short references without domains will now fail parsing on recent versions
of Go as net/url parser is more strict.
replace #3419 as this is a proper fix.
=> Expand all image references before passing to containerd reference.Parse

docs/metadata.md, examples/hetzner.yml, pkg/metadata/main.go, pkg/metadata/provider_hetzner.go
The title of the PR is pretty self-explanatory 😜
I copied the AWS provider file and removed a few lines that get metadata that's not available on Hetzner and updated the function `handleSSH` to parse the JSON array of ssh keys Hetzner provides and for each key write it to the authorized_keys file on a new line.
I'm not a Go developer so I might have missed something obvious, etc. so please do a proper review before merging 😄
=> Add Hetzner provider in the metadata package

kernel/Makefile
KCONFIG_TAG variable can be used to set a custom kconfig tag.
If KCONFIG_TAG is not set, the the image is tagged as linuxkit/kconfig:latest
This is useful for projects requiring to build multiple kernels that have
different patches.
When trying to edit an unpatched kernel config after working on a patched
kernel config (same kernel version), one had to rerun make kconfig first
in order to edit the config of an unpatched kernel.
Now it is possible to generate a tegged kconfig image and then, get the wanted
config by selecting the corresponding linuxkit/kexec:tag.
Signed-off-by: Gabriel Chabot <gabriel.chabot@qarnot-computing.com>
Allow to choose a custom tag to linuxkit/kconfig image when making kconfig target in kernel
Edited kernel/Makefile:
- Added an …
=> Add the possibility to tag linuxkit/kconfig with a custom tag

MAINTAINERS
I'd like to formally step down as a maintainer, as I haven't been as involved as of late -- exciting to see all of the progress :) 
Signed-off-by: Riyaz Faizullabhoy <riyazdf@berkeley.edu>
=> Remove riyazdf from MAINTAINERS

pkg/swap/swap.sh
Sped up the swapfile creation.
If the swap disk is larger than 1MiB, then use a 1MiB blocksize in `dd`
On my machine using a large block size speeds up swap file creation:
```
/ # time dd if=/dev/zero of=output bs=1024 count=1048576
1048576+0 records in
1048576+0 records out
real    0m 4.61s
user    0m 0.79s
sys     0m 3.77s
/ # time dd if=/dev/zero of=output bs=1048576 count=1024
1024+0 records in
1024+0 records out
real    0m 1.06s
user    0m 0.00s
sys     0m 1.04s
```
I added a debug print to display the `dd` command-line
1. small sizes are created correctly, 2048 is written as 2 blocks of 1024:
```
$ docker run -it -v $(pwd):/foo -w /foo alpine sh
/foo # ls
Dockerfile  README.md   build.yml   swap.sh
/foo # ./swap.sh --path …
```
=> swap: speed up by preferring a 1MiB blocksize

pkg/metadata/provider_hetzner.go
There were some mistakes made in the initial code where writes didn't work, this PR fixes that.
I've tested these changes properly on Hetzner using the `metadata` package in a custom build of k3os.
=> Fix the Hetzner provider in the metadata package

pkg/metadata/provider_scaleway.go
Currently the Scaleway provider in the `metadata` package isn't working as expected, at least for me in k3os, which is using that package.
This will update the provider to use the endpoint `.../user_data/cloud-init` where the cloud-init data is served if it was provided. This is also the endpoint the python cloud-init scaleway provider is using from what I could tell. If no cloud-init data was provided this request will return a 404 and check for that in this fix so that we don't get an error if there is no cloud-init data.
This will also remove some code that stripped away the `ssh-rsa`/`ssh-dsa` part in the SSH keys, as no other provider code does that and a complete ssh key should include that part, as least to my knowledge.
=> Fix the Scaleway provider in the metadata package

pkg/metadata/provider_scaleway.go
Remove the `sendBootSignal`.
Removed the lines of code :sweat_smile: 
It's now not needed to send a boot signal when booting an instance on
Scaleway, thus the method is not needed anymore.
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> remove sendBootSignal in scaleway metadata package

pkg/metadata/provider_gcp.go, src/cmd/linuxkit/gcp.go
Updates the userdata key to the more common and documented `user-data` instead of `userdata`.
https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#using_cloud-init
Checks to see if the /run/config/ssh directory exists; this allows new ssh keys to be fetched on reboot.
Signed-off-by: Preston Holmes <preston@ptone.com>
=> Update GCP metadata provider

tools/mkimage-gcp/make-gcp
Removed size arg from the tools/mkimage-gcp/make-gcp.sh script virt-make-fs command as this fixed size was failing with larger images.
delete key
We have a large file included in our 'files:' directive, so this is where we found this issue. When making a large (>1GB) image with the old make-gcp script you'd get a "failed: exit code 1". We no longer get this error with the included change.
Removed size arg from mkimage-gcp script.
=> Removed fixed size arg from mkimage-gcp script.

pkg/metadata/main.go, pkg/metadata/provider_file.go
This adds a new configuration provider that just reads a file.
This is needed for Docker Desktop, where we will run a LinuxKit distro in an isolated namespace within WSL 2.
In this scenario, the config will be accessible trough the WSL2 built-in 9p mount of the Windows filesystem.
If no provider match the first command line argument, and there is an actual file at this location, it directly read the json payload from it
- Create a LinuxKit image with a static config file in it
- Add an onboot metadata service passing the path to this file as an argument
- Check that /run/config is correctly populated
Machine configuration can now be read directly from a file
**- A picture of a cute animal (not …
=> Metadata: add support for loading from a file

kernel/Dockerfile
This new snapshot comes from the brand new linux-compat repo, which
follows the recent upstreaming into net-next. When Linux 5.6 lands in
LinuxKit, we'll be able to remove the module entirely.
=> wireguard: update to 0.0.20191226

contrib/open-vm-tools/README.md, contrib/open-vm-tools/open-vm-tools-ds.yaml
This should allow end-users to gracefully reboot or shutdown Kubernetes
nodes (incuding control planes) running on vSphere Hypervisor
There are several use cases when cluster administrators are not able to
install extra packages onto the host OS
Fixes #3462
Create DaemonSet which runs on all Kubernetes node.
`kubectl apply -f contrib/open-vm-tools/open-vm-tools-ds.yaml`
Add kubernetes manifest for open-vm-tools
=> contrib: Add kubernetes manifest for open-vm-tools

kernel/Dockerfile
Tiny fix for a small workaround that is no longer required
=> libunwind-dev workaround on x86 is no longer required

.github/workflows/ci.yml, Makefile, src/cmd/linuxkit/gcp.go
Since the move to alpine:3.11, our go-compile runs 1.13.4; this bumps our CI to use the same.
change ci.yml
Let CI run
Use go1.13.4 in CI
=> match go version in CI to version in go-compile

examples/aws.yml, examples/docker-for-mac.yml, examples/gcp.yml, examples/hetzner.yml, examples/openstack.yml, examples/packet.yml, examples/scaleway.yml, examples/vultr.yml, pkg/metadata/provider_cdrom.go
Fixes #3501 
Read metadata for cdrom provider from `/user-data` per the spec (see #3501), falling back to `/config`
Read `/user-data` first, then `/config`
Run it, CI.
Support userdata from standard location
Note: I only added metadata support. It _reads_ the metadata from the standard location if it exists, but does not write it out to file. That will be in a future stage
=> read cdrom userdata from spec location

docs/external-disk.md, examples/cadvisor.yml, examples/dm-crypt-loop.yml, examples/dm-crypt.yml, examples/docker-for-mac.yml, examples/docker.yml, examples/swap.yml, pkg/format/format.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/005_by_device_force/test.yml, test/cases/040_packages/006_format_mount/006_gpt/check.sh, test/cases/040_packages/006_format_mount/006_gpt/test.sh, test/cases/040_packages/006_format_mount/006_gpt/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
I've added GUID Partition Table (GPT) support to the `format` package in order to support partitions greater than 2 TiB.
I've added an *optional* `--partition` input parameter to the `format` command-line that can be used to select one of the supported partition table modes:
- `dos`: **(default)** master boot record (MBR), DOS partition table;
- `gpt`: GUID partition table (GPT).
Note: an error is triggered (w/t early termination) if an invalid partition table mode is supplied.
Note: it defaults to the "legacy" MBR/DOS behavior.
GUID Partition Table (GPT) support has been implemented by prepending `g\n` to the `fdisk` standard input string reader.
- use `format` as an on-boot package;
- attach an empty disk > 2 TiB (e.g. …
=> Add GUID Partition Table (GPT) support to the `format` package

pkg/metadata/main.go, pkg/metadata/provider_digitalocean.go
Add support for fetching metadata and user data from the DigitalOcean metadata service.
Copied an existing metadata provider (Vultr) and changed the URLs and paths to match those in the DigitalOcean documentation: https://www.digitalocean.com/docs/droplets/resources/metadata/
1. Create a DigitalOcean droplet with [custom image](https://www.digitalocean.com/docs/images/custom-images/) using this linuxkit.yaml and `-format raw-bios`:
```
kernel:
image: linuxkit/kernel:5.4.30
cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
- linuxkit/init:v0.7
- linuxkit/runc:v0.7
- linuxkit/containerd:v0.7
- linuxkit/ca-certificates:v0.7
onboot:
- name: sysctl
image: linuxkit/sysctl:v0.7
- name: dhcpcd
image: …
```
=> metadata: add support for digitalocean

docs/packages.md, src/cmd/linuxkit/pkg_push.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go
Split `pkg push` into 2 distinct stages, but can be executed as one:
1. Push the image from your local arch (e.g. amd64, arm64, etc.)
1. Create and push the manifest and sign it
The `docs/packages.md` has been updated to reflect how to do it. Short form:
1. Go to each arch and do 
```
lkt pkg push --manifest=false path/to/pkg
```
1. Go to wherever you have your signing keys and do
```
DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=<whatever> lkt pkg push --image=false path/to/pkg
```
You can disable signing as well by doing `--sign=false`
The default remains the current behaviour 
Split up the code in `src/cmd/linuxkit/pkg_push.go`
Create a package, test it.
**- Description for the …
=> options to split image steps and manifest steps

src/cmd/linuxkit/pkg_build.go
Fixed `pkg build` command not actually building anything. Think the problem originates from changes in https://github.com/linuxkit/linuxkit/commit/ea18be414eb85888f9990a7821608cdd505a2fe2.
Added `WithBuildImage` to opts in `pkg_build`.
Running for example `linuxkit pkg build -org=example -disable-content-trust pkg/sshd` should result in a built image.
Fixed `pkg build` command not building the image.
=> Make `pkg build` build the image

CHANGELOG.md, Makefile
- Bump version to v0.8+
- Update changelog (closes https://github.com/linuxkit/linuxkit/pull/3528)
=> Post v0.8 cleanup

contrib/open-vm-tools/open-vm-tools-ds.yaml
Extended list of tolerations with `node-role.kubernetes.io/master=true:NoSchedule`; kept the previous tolerations
Fixes #3549
- Added new toleration into the list of tolerations
1) Taint a node with `node-role.kubernetes.io/master=true:NoSchedule`
2) Execute `kubectl apply -f contrib/open-vm-tools/open-vm-tools-ds.yaml`
3) Check that the `open-vm-tools` Pod started on the tainted node  from Step 1
Extend list of tolerations for open-vm-tools
=> contrib: extend list of tolerations for open-vm-tools

examples/aws.yml, examples/azure.yml, examples/gcp.yml, examples/hetzner.yml, examples/openstack.yml, examples/packet.yml, examples/sshd.yml, examples/vpnkit-forwarder.yml, examples/vultr.yml, pkg/sshd/Dockerfile, projects/miragesdk/examples/mirage-dhcp.yml
Added the `openssh-client` package to `linuxkit/sshd`. This enables people to ssh _from_ being on the host (as opposed to ssh to, which you already can do), as well as scp from it and to it.
1. Added the `openssh-client` apk package from the linuxkit/alpine cache
1. built and pushed `pkg/sshd` on all platforms, and signed the manifest
1. ran `update-components-sha.sh`, which updated `projects/` and `examples/`
CI
ssh client tools in linuxkit/sshd
=> include openssh-client in sshd pkg

docs/packages.md
Expanded the `packages.md` doc to describe how to sign a tag manually. I needed this once in a while, so it is good to know how it works under the covers.
Writing markdown.
Read it. 
Describe how tag signing works.
=> describe how to sign tags manually

.github/workflows/ci.yml
fix the GitHub Actions [set-env deprecation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) that was causing CI to fail
Replaced `set-env` in our `ci.yaml` with a new step, per the GitHub recommendation
CI runs
update CI per GitHub set-env deprecation
=> fix deprecation of set-env

Makefile
I removed the extraneous "/" at the end of the `PREFIX` variable in the main `Makefile`. 
That way, instead of using `/usr/local//bin`, we use the correct `/usr/local/bin` path.
`vi Makefile`
`make && sudo make install`
I removed the extraneous "/" at the end of the `PREFIX` variable in the main `Makefile`.
=> Removed extraneous "/" at end of PREFIX in Makefile

contrib/open-vm-tools/open-vm-tools-ds.yaml
Added `"node-role.kubernetes.io/control-plane"` key as `toleration` for `open-vm-tools`
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
- Extended the array of `tolerations`
From Kubernetes v1.20.0 Release notes:
The label applied to control-plane nodes "node-role.kubernetes.io/master"
is now deprecated and will be removed in a future release after a GA
deprecation period.
Introduce a new label "node-role.kubernetes.io/control-plane" that will
be applied in parallel to "node-role.kubernetes.io/master" until the
removal of the "node-role.kubernetes.io/master" label.
xref: https://kubernetes.io/docs/setup/release/notes/#no-really-you-must-read-this-before-you-upgrade
contrib: add …
=> contrib: add control-plane toleration for open-vm-tools

Makefile
Replaced the arg to `ineffassign` from a list of individual `.go` files to `./src/cmd/linuxkit/...`
The latest ineffassign doesn't accept individual files that are in different directories, so have to switch to `/...`
See [here](https://github.com/gordonklaus/ineffassign/commit/8eed68eb605f2ddf507412accb8dd7a595b5c114)
Replaced a single line in Makefile
1. Change a few files to introduce the error
2. Run `ineffassign`
3. See that it catches them
Support latest ineffassign args
cc @giggsoff
=> provide wildcards to ineffassign

examples/aws.yml, examples/docker-for-mac.yml, examples/gcp.yml, examples/hetzner.yml, examples/openstack.yml, examples/packet.yml, examples/scaleway.yml, examples/vultr.yml, pkg/metadata/main.go, pkg/metadata/provider_metaldata.go, test/cases/040_packages/008_metadata/000_cidata/test.yml
Signed-off-by: Michael Aldridge <aldridge.mac@gmail.com>
I added a new metadata provider that supports the metaldata API provided by ResinStack MetalData.  This provider uses a DNS name which greatly simplifies the network topology by allowing the remote network to resolve a DNS name, optionally after canonicalizing it against a search domain.
I copied components of existing providers (AWS and Vultr) and modifying them to suit the API handled by MetalData.
Get a metaldata server spun up (or don't, the API can be satisfied with a carefully laid out folder structure on disk) and configure your DNS to handle a request for 'metaldata' to point back to wherever this webserver is.  Once you've done this you can boot a machine and …
=> Support metaldata metadata provider

kernel/Dockerfile
Signed-off-by: Yoann Ricordel <yoann.ricordel@qarnot-computing.com>
Bump the version of the pulled Intel microcode from `20191115` to `20210216`
Changed the checked out tag in `kernel/Dockerfile`
I guess by trusting that the change is trivial (look at the diff) and just check that a kernel it still builds.
Bump Intel microcode from `20191115` to `20210216`
=> Bump Intel microcode version to 20210216

Makefile, docs/vendoring.md, tools/go-compile/compile.sh
Use `-mod=vendor` in the go-compile package when using go modules.
Fixes https://github.com/linuxkit/linuxkit/issues/3599
=> Fix go-compile for go.mod

.github/workflows/ci.yml
Currently the CI is just building Linux images and all the artefacts are identical. This PR changes the CI to invoke `make` with the right GOARCH/GOOS setting to cross compile for the targeted architectures/OS.
It also removes the cache for artefacts and downloads them from the first stage upload. The cache had issue and I couldn't get it to work reliably.
Downloaded the artefacts and I now get:
```
% for f in linuxkit-*; do file $f; done
linuxkit-amd64-darwin: Mach-O 64-bit executable x86_64
linuxkit-amd64-linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=bpg0BD4QnkF9sJqtKOY9/fHwLGn8E2euvrVY7D11s/8yeynCmEnS2RvUhMUnZf/UFc7fvn-2R0aKycEiSFG, not stripped
linuxkit-amd64-windows.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS …
```
=> ci: Enable linuxkit cross compile

README.md
`go get -u` will try to update modules dependencies
`go get` (no `-u`) incorrectly resolves dependencies
we should instead advise users to `go install`
Closes: #3608
=> README: Don't go get

examples/docker-for-mac.yml, pkg/trim-after-delete/main.go
Extended `trim-after-delete` to run the command after a container destroy and volume destroy.
We already watch for events, so it's a simple matter to handle the additional container and volume events.
I run
```
trim-after-delete -- /sbin/fstrim /var/lib/docker
```
and then `docker rm` a container. I see the following output:
```
2020/07/24 13:08:10 A container has been deleted: will run the action at least once more
2020/07/24 13:08:20 Running /sbin/fstrim /var/lib/docker
```
If I `docker image rm` an image I see the following output:
```
2020/07/24 13:08:41 An image has been deleted: will run the action at least once more
2020/07/24 13:08:51 Running /sbin/fstrim /var/lib/docker
```
If I `docker volume rm` a volume I see the …
=> trim-after-delete: handle containers and volumes as well as images

src/cmd/linuxkit/cache/push.go
Fixed how manifests are created with `linuxkit pkg push`
Passed the name of the manifest, rather than the name of the arch-specific image, to `ManifestPush()`
Run it. I just did, it works.
Also, CI is a nice thing.
Fix pushing of packages
=> use correct manifest name when pushing

docs/developer-setup.md
Created a doc to track how maintainers can manage their build platforms. Also includes directions for getting modern Docker on s390x.
Markdown.
Read it
Maintainer build server logs
=> docs to hold maintainer build platforms

MAINTAINERS
Dave Scott works on the Docker Desktop team, and maintains LinuxKit changes internally for that. I think Dave would make a good addition to the list of maintainers to help out. :)
=> Add another Dave as maintainer

src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/main.go, src/cmd/linuxkit/moby/images.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
* Add check if an image exists locally before building with `lkt pkg build`. Beforehand, it had just looked on the registry; now it checks both, and validates the local image if found (all components exist, hashes valid, diffids valid). As before, can be overridden by `--force`.
* Add pull/push logging to `lkt pkg` activities via the underlying library, using the existing streams and config
* when calling `cache.ImagePull()`, have an option to `alwaysPull` and, if false, check locally and validate if found before going to remote and, eventually, build/
* Tied the logging to the container registry libraries to our own logging setup in `main.go
CI …
=> handle image already in cache

AUTHORS, MAINTAINERS
I noticed we don't have a Alumni section in the MAINTAINERS file and while adding it also updated the constributors
=> Add Alumni to MAINTAINERS and update Authors

Makefile, docs/vendoring.md, tools/go-compile/compile.sh
When upgrading to go1.16 and gcc10.x, we ran into issue of conflict with `-buildmode=pie` creating dynamic linux binaries rather than static, since it uses go's new built-in linker, which creates dynamically-linked linux binaries. The solution is to put `-linkmode=external`, which causes it to use the external linker.
What we did worked, but it set `-linkmode=external` for _all_ builds, not just for linux. gcc handles most of those fine... except for Darwin arm64 (macOS M1). 
In truth, `-linkmode=external` really should only be used for the scenario when all of the above is true:
* building for linux
* `-buildmode=pie`
The only affected area is `tools/go-compile` and its dependencies, since everything that uses …
=> pass linkmode=external only for Linux

Makefile, docs/vendoring.md
For some reason #3643 had the wrong hash in `Makefile` and `docs/vendoring.md`. This fixes it.
Redid `lkt pkg push tools/go-compile` and then reran `./scripts/update-component-sha.sh --image $(lkt pkg show-tag ./tools/go-compile/)`
CI run, run it manually
Proper go-compile hash on dependencies
Thanks to @dave-tucker for finding this
=> Update to proper go-compile hash

.github/workflows/ci.yml, Makefile, src/cmd/linuxkit/Makefile
Go can be weird about tools having to run in a directory with
go.mod. This commit moves the linuxkit makefile to the same
directory as the code. To fix it.
Note: I've put off fixing the in-container builds until we can bump the alpine/go versions.
=> make: Fix for local builds outside of GOPATH

src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/util/reference.go
Ensure that all image names in the lkt cache are canonicalized, to avoid issues where it will not recognize `foo/bar:abc` and `docker.io/foo/bar:abc` as the same, or `alpine:3` and `docker.io/library/alpine:3` as the same
Fixes #3634 
1. Extracted `Moby.referenceExpand()` to `util.ReferenceExpand()`, had everything point to it
2. Create `Pkg.FullTag()` which gives the expanded tag
3. Use `p.FullTag()` instead of `p.Tag()` whenever creating references to use in the cache
Try building. It works.
CI too.
Handle image names universally canonicalized
=> always use canonical names in the linuxkit cache

.github/workflows/ci.yml
Added the default linuxkit cache directory to the GitHub Actions cache.
This will ensure that we don't pull images that already exist in the cache, or build them if we've already done so. 
It should speed up CI.
Editied the ci.yml file
Output from the CI run should show the cache directory being cached
=> ci: Cache Package Builds

docs/packages.md, src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/pkglib.go
Fixed a bug to ensure to that `--platforms` **always** overrides build.yml whether or not the platform is declared as supported or not.
Fixed a missing comment on `FullTag` which was upsetting the linter.
Fixed a messy import from being named `v1` to being named `registry`.
Added a `--skip-platforms` flag to `lkt pkg build`. This allows for use cases where you want to build only supported combinations from a list of packages. For example, in CI we wish to skip s390x emulation as it's buggy, so we'd like to do `lkt pkg build --skip-platforms=linux/s390x ...`
Edited `pkg_build.go` and other files in `pkglib` and added documentation
Before, attempting to force `pkg/bpftrace` to build on amd64 would fail:
```
$ linuxkit pkg build …
```
=> pkg_build: Allow skipping unsupported platforms

tools/alpine/Dockerfile, tools/alpine/Makefile
Small change: have linuxkit/alpine calculate and carry its own hash, and use it from makefile, rather than calculating it in the Makefile. As a nice side effect, it allows us to be working inside any linuxkit/alpine image and know precisely what tag ran it.
Also, `docker build` sets `TARGETARCH` for us, which gets rid of a few lines in the `Makefile`
Finally, if we ever change how we calculate it, that change will be inherent inside the image build itself 
Move some logic from `tools/alpine/Makefile` to `tools/alpine/Dockerfile`, and then change `Makefile` to consume it. 
Run it.
linuxkit/alpine carries its own calculated hash tag with it.
=> alpine carry its own hash

tools/alpine/Dockerfile, tools/alpine/Makefile
In PR #3650 we moved the logic for calculating the hash for an arch-specific alpine image from inside `tools/alpine/Makefile` to inside `tools/alpine/Dockerfile` and then consumed it. This was a good idea, but the implementation had two issues:
* The actual usage of `TARGETARCH` did so in a way that left it as a literal `${TARGETARCH}` rather than interpolated correctly by the Dockerfile
* The file was named `/etc/alpine-hash`, which implied that it was the generic, multi-arch index, when really it is just the arch-specific one
This PR corrects both of the above. It ensures that `TARGETARCH` is interpolated by the Dockerfile, and it saves the file as `/etc/alpine-hash-arch`.
This does not resolve the question of having an …
=> correctly use target-arch

tools/alpine/packages.x86_64, tools/alpine/versions.aarch64, tools/alpine/versions.s390x, tools/alpine/versions.x86_64
In alpine version 3.12, the open-vm-tools package got split into new
smaller sub-packages. The implication of this is that features such as
reporting of hostname and ip address to vCenter stopped working.
relates to #3662
part of #3663
=> Include open-vm-tools packages

pkg/trim-after-delete/build.yml
Limit `trim-after-delete` to non-`s390x`
By modifying the `build.yml` :)
`linuxkit pkg build pkg/trim-after-delete`
- Only build `trim-after-delete` on `arm64` and `amd64`
🐱
=> trim-after-delete: avoid building on s390x

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go
This is inspired by EVE OS's port to riscv64 https://github.com/lf-edge/eve/pull/2083 
added linux/riscv64 as a recognizable architecture
just followed the breadcrumbs of what already is being done for `linux/s390x`
one can try building EVE packages along the lines of https://github.com/lf-edge/eve/pull/2083 but until the Docker qemu-user bug for Mac OS is fixed -- this will require either workarounds on Docker Desktop side OR running it on Linux and Windows.
Adding linux/riscv64 as a recognizable architecture
=> Allowing linuxkit to recongnize linux/riscv64 arch

docs/releasing.md, tools/alpine/Makefile, tools/alpine/push-manifest.sh
Changed the calculation of `linuxkit/alpine` tag from "let's just use whatever is in x86_64" to "let's reuse `lkt pkg show-tag`, which calculates it based on the git tree.
This has 2 advantages:
1. It ensures we capture any changes - all of the hashes of per-arch ones already are checked in in `versions.<arch>`; this ensures that if we change, e.g. arm64 but not amd64 that we capture the change.
2. Keeps it consistent across the packages
This doesn't quite bring us to being able to do `lkt pkg build tools/alpine` - we may never get there - but it at least reuses some of the logic while doing a better job capturing changes.
Added  `tools/alpine/build.yml` (necessary for `show-tag` to work), then changed …
=> calculate manifest using same method as lkt pkg push via git ls-tree

docs/testing.md, kernel/Dockerfile, kernel/Dockerfile.bcc, kernel/Dockerfile.kconfig, kernel/Dockerfile.perf, kernel/Dockerfile.zfs, kernel/Makefile, test/cases/020_kernel/111_kmod_5.4.x/Dockerfile, test/cases/020_kernel/113_kmod_5.10.x/Dockerfile, test/cases/020_kernel/114_kmod_5.11.x/Dockerfile, test/cases/020_kernel/211_tags_5.4.x/test.sh, test/cases/020_kernel/213_tags_5.10.x/test.sh, test/cases/020_kernel/214_tags_5.11.x/test.sh, test/cases/020_kernel/tags.sh
A few things in `kernel/`:
* some simplifications in `Makefile` to eliminate redundant code (mainly so it was easier for me to grasp)
* removed all references to `linuxkit/alpine:<hash>` in all of the kernel Dockerfiles, replaced with an `ARG`, which is passed by `docker build` (which already had some `--build-arg`) from the `Makefile`
* save the name of the builder image in the final kernel image as `/kernel-builder`
* save the name of the builder image in the final kernel image as a label `org.mobyproject.linuxkit.kernel.builder ${BUILDER}`
The purpose is to have the image carry its matched builder in the appropriate location, so you can get it, whether you are already inside the container (from the file) or outside (from …
=> tag kernel with builder version; simplify Makefile

src/cmd/linuxkit/cache.go, src/cmd/linuxkit/cache_export.go
Added support to export an image from cache via `lkt cache export`
Leveraged the `V1TarExport` from #3668 to add a new sub-command.
Run it and export. It works.
Export images from cache
=> Add support for cache export

src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/registry/manifest.go
* ensured that tags for arch-specific pkg images exist. We used to have `linuxkit/foo:abc-amd64`, `linuxkit/foo:abc-arm64`, etc., in addition to the multi-arch index `linuxkit/foo:abc`. With the move to linuxkit cache, we stopped pushing those tags out. They turn out to be rather useful, so this pushes the tags out again.
* always rebuilds the multi-arch index (after pushing) from every known architecture in the registry. We used to do that when we had to build and push on each arch. Now that we don't _have_ to, it would just push whatever was local. However, if you _wanted_ to - or even just pushed out on one arch - it would replace the index that was there with one that pointed just to that arch. Oops. With this change, …
=> Push arch-specific tags, always build index from registry

src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
Fixes #3694 
Two changes:
1. When pulling an image or index to the cache, don't assume it fulfills the requested architecture. It might have pulled an index with other arches. Explicitly check for the requested architecture.
2. When pushing from cache to registry, don't look by `<imageName>-<arch>`, as it might not be there, as the root might just be an index with descriptors per architecture. Instead, look in the index manifests for the right descriptor and push that. This is more accurate anyways.
Changes to `src/cmd/linuxkit/cache/`
* CI
* I am running tests
More reliable cache pull/push
=> check for arch when pulling to cache, push by descriptor

.github/workflows/ci.yml, src/cmd/linuxkit/go.mod, src/cmd/linuxkit/moby/images.yaml, src/cmd/linuxkit/moby/output.go
Extract the hard-coded image builders out of `moby/output.go` and into an `images.yaml` file, which is go-embedded.
Also required bumping go to 1.16, but we all use it anyways.
Create the new file, use go embedding
Let CI run. I ran manually, both to build an image and to debug step through to make sure it gets created correctly. I might have missed a case (don't think so, but that is what CI is there for).
Extract hard-coded builder images from go file
=> extract hard-coded default image builders into file

src/cmd/linuxkit/moby/linuxkit.go, src/cmd/linuxkit/moby/mkimage.yaml
Continuing #3727 , this extracts one more chunk of hard-coded yaml out of a `.go` file and places it in a yaml that is pulled in using go embed.
Extract and go embed.
Ran manually, ran via debugger to see that it was populated, let CI run.
Last hard-coding out of go files.
=> extract more hard-coded yaml

scripts/update-component-sha.sh
Restrict `update-component-sha.sh` to only change files that end in `yml`/`yaml`/`yml.in`/`yaml.in`, as discussed [here](https://github.com/linuxkit/linuxkit/pull/3723#discussion_r739785144) with @djs55 and @rn 
By the way, this is not _strictly_ necessary. It would continue to work without this. But it seems to make sense.
Modified the single script.
Run it. It works. I did. 
update-component-sha.sh only affects yaml files
**Note:** I found one other place where we have the hashes embedded in a `.go` file, PR for that should go in first #3729
=> restrict update to just yaml files

examples/logging.yml, pkg/memlogd/cmd/memlogd/main.go, test/cases/040_packages/011_kmsg/test.yml, test/cases/040_packages/012_logwrite/test.yml
Signed-off-by: Emmanuel Briney <emmanuel.briney@docker.com>
I changed time precision to use `RFC3339Nano` intead of `RFC3339` in memlogd messages because one second resolution is too low when you want to compare timestamp from two differents sources
I changed the `message.String()` func
```
go test -v ./...
?       memlogd/cmd/logread     [no test files]
?       memlogd/cmd/logwrite    [no test files]
=== RUN   TestNonblock
2021-11-26T16:48:21.384944+01:00,memlogd;hello TestNonblock
2021-11-26T16:48:21.385035+01:00,memlogd;hello TestNonblock
2021-11-26T16:48:21.385194+01:00,memlogd;hello TestNonblock
2021-11-26T16:48:21.385196+01:00,memlogd;hello TestNonblock
2021-11-26T16:48:21.385204+01:00,memlogd;hello TestNonblock …
```
=> Use RFC3339Nano for timestamps

examples/docker-for-mac.yml, pkg/acpid/build.yml, test/cases/010_platforms/010_hyperkit/010_acpi/test.yml
I fixed the bug #3738 by adding missing "devices" field on the acpid `build.yml`
By typing on my keyboard
I checked the fix manually on real hardware, I can cleanly shutdown the machine by pressing the power button shortly.
I also checked the acpid logs, and verified that there was no errors
Add missing "devices" field on the acpid service to allow input devices
=> Fix acpid devices

examples/cadvisor.yml, examples/docker-for-mac.yml, examples/docker.yml, pkg/openntpd/Dockerfile, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml
Removed the "-s" flag in the ntpd command-line because the flag is obsolete and generate some error messages in the ntpd logs
Typed the backspace key
Check the CI
Removed the "-s" flag in openntpd package, because this flag is obsolete
https://cdn.radiofrance.fr/s3/cruiser-production/2014/03/ea065e11-ac5b-11e3-907f-782bcb6744eb/640_marmotte-cc-benjamine92.jpg
=> openntpd: the "-s" flag is obsolete, this generates some error messages in the ntpd logs

src/cmd/linuxkit/moby/docker.go
Fixed `docker run` error printing so it is easier troubleshoot problematic docker images.
Try build iso-bios from https://github.com/rancher/os/blob/master/scripts/moby/rancheros.yml with command `linuxkit build -format iso-bios rancheros.yml`
Without this change error message looks like this:
```
FATA[0006] Error writing outputs: Error writing iso-bios output: docker run linuxkit/mkimage-iso-bios:2fb7eea032a8f8ec76d9ca69592046875c50683c failed: exit status 1 output: 
```
and after this change like this:
```
FATA[0024] Error writing outputs: Error writing iso-bios output: docker run linuxkit/mkimage-iso-bios:2fb7eea032a8f8ec76d9ca69592046875c50683c failed: exit status 1 output:
dist: Can't replace existing directory with non-directory
bsdtar: Error …
```
=> Print docker run stderr in-case of error

src/cmd/linuxkit/build.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/moby/linuxkit.go
Fixed #3750 
`type Moby` contained a field `Architecture` to pass around what arch we are building for. However, that does not correctly reflect the yaml file, which should be usable across architectures. It only was added as a convenience, to avoid passing another parameter to several functions.
This removes that non-yaml property and passes it around explicitly where needed.
Removed the field, added it as arg to several functions.
CI is your friend.
Align Moby type with yaml by moving extraneous fields out and passing explicitly.
=> pass target architecture explicitly

src/cmd/linuxkit/build.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/image.go, src/cmd/linuxkit/moby/linuxkit.go, src/cmd/linuxkit/moby/opts.go
Replaced the signature of `Moby.Build(lots, of args, here, and, keep, changing)` with an `BuiltOpts struct`
Replace, test
CI
Simpler `moby.Build` signature
**- Notes for maintainers**
I am not sure how much this buys. We never really intended `moby.Build()` to be used by the public, but it is; implicit API and all that.
This does clean it up at least somewhat, by giving it a signature of:
```go
func Build(m Moby, w io.Writer, opts BuildOpts) error {
```
That strikes me as better and easier to understand.
However, once inside `moby.Build`, we call `ImageTar()` once and `outputImage()` 3 times, each of which just takes lots of those parameters.
The …
=> replace Build many args with opts struct

docs/packages.md, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/pkglib.go, test/cases/000_build/030_build_args/Dockerfile, test/cases/000_build/030_build_args/build.yml, test/cases/000_build/030_build_args/test.sh
Related to #3394
This allows multiple build flavors for a single codebase, without
sacrificing reproducible builds. The build-args are set in build.yml,
which is typically under the source control (if it is not, then no
reproducible builds are possible anyways). Meaning that mutating
build-args would result in setting “dirty” flag.
Intended use of this commit is to switch between build flavors by
specifying a different yaml file (presumably also under the version
control)  by  `-build-yml` option.
Allow forwarding build-args to Dockerfiles 
By adding parsing of buildArgs in build.yml
Add a section in the Dockerfile:
```
ARG FOO=bar
RUN echo "FOO=$FOO"
```
and to `build.yml`:
```
buildArgs:
- FOO=xxx
```
Run `linuxkit pkg build …
=> Declare build-args in build.yml

.github/workflows/publish.yaml, docs/packages.md
Removed the need for maintainers to push out packages.
2 changes:
1. On PR, it already did `lkt pkg build`, which forces it to download the image to lkt cache or, if not there, build it (or fail). Here we just need to tell maintainers "do NOT push it", which this does. Eventually, we should remove manual pushing capability.
2. Added a new GH actions workflow file that, when the build ci.yaml is done, and we are on `master` or `main` branch, pushes out every package. Since only changed ones will not already be in registry, this will push out only the changed ones.
Requires a new PR that changes a package, have no one push it out, see that it works. …
=> remove need for maintainers to build packages

.github/workflows/publish.yaml
Fix the cross-workflow download of artifact
Replace the standard GitHub `actions/download-artifact` (which does not support cross-workflow downloads) with an explicit `actions/github-script` which does.
CI will not change. We will need to merge into `master` to know that it works.
=> download artifact from other workflow

kernel/Dockerfile
Signed-off-by: Gabriel Chabot <gabriel.chabot@qarnot-computing.com>
Add openssl to the kernel-build image.
It is required when building a kernel with module signing enabled (for kernels 3.7 and higher).
apk add openssl with the other packages in the kernel-build image in `kernel/Dockerfile`
Build a kernel with CONFIG_MODULE_SIG enabled in it's kconfig
Add openssl to the kernel-build
=> Add openssl to the kernel-build

src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/pkg_build.go
1. If there are no platforms at all to build, then do not even try to build or push. We use blank `arches:` in one or two places to indicate, "do not build this". However, that sometimes can cause an error when it tries to build or push and finds no arches or an index with no manifests. This ensures that it works correctly.
1. When doing `lkt pkg push`, check if the manifest/index tag you are pushing already exists on the registry, and if it does, skip the push if the digest is identical.
Changes to `src/cmd/linuxkit`.
I tested the first part by trying to build and push bpftrace, which has blank `arches` and therefore disabled, and then with sysfs, which does not.
I tested the second part by trying to push sysfs, whose local …
=> Skip build if no platforms

src/cmd/linuxkit/pkg_build.go
#3787 skips a build if it has no archs. Which is good. Except instead of continuing to the next package, it exits.
This fixes it.
Change `return` for `continue`
CI, and I ran it manually
Continue for all packages after skipping packages with no architectures
=> when no archs for pkg to build, should continue rather than return

pkg/Makefile, pkg/dummy/Dockerfile, pkg/dummy/build.yml, pkg/dummy/infile, test/cases/040_packages/001_dummy/test.sh, test/cases/040_packages/001_dummy/test.yml
Just a test of the build system. Will let CI run, tests should pass, and then will merge to PR, should push out new `linuxkit/dummy` image.
Once it is done, I will open a PR to delete `pkg/dummy` and manually delete the image.
=> test pkg/dummy

pkg/sysctl/build.yml
With linux kernel 5.15+ change of /proc/sys/net/ipv4/ip_forward require
CAP_NET_ADMIN (https://github.com/torvalds/linux/commit/8292d7f6). We do
not use ip_forward now, but we should be ready for future changes of
conf files.
=> Add CAP_NET_ADMIN capability to sysctl

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go
We do not allow to load into docker images that are targets another
platform differ from current arch. Assume this is because of no support
of manifest. But we can keep all images in place by adding arch suffix
and using tag without arch suffix to point onto current system arch. It
will help to use images from docker for another arch.
=> Allow store to docker multiarch builds

pkg/memlogd/cmd/logread/main.go, pkg/memlogd/cmd/memlogd/main.go, pkg/memlogd/cmd/memlogd/main_test.go
This is the first step in supporting structured success/error data in `memlogd` log files.
Those log files are currently made of semicolon separated fields and, for each line, the list of fields is the same.
We would like to support multiple kinds of entries. Application logs, like we do already, but also structured success/error data. Those entries would have some fields in common and some based on the type of entry. 
Switching from semicolon separated fields to json gives us this flexibility without much added complexity. In fact, it even removes a constraint we currently have on `Source` field not containing a semicolon.
=> Write log entries as json

src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/pkglib/build.go
We pull all arches for the image which is suboptimal in terms of storage
consumption. Let's pull only required platforms.
=> Do not pull another arch and index cleanup

src/cmd/linuxkit/pkglib/git.go, src/cmd/linuxkit/pkglib/pkglib.go
To be able to identify successive file changes without commit, we should use their hash in tag alongside with dirty flag ([ls-tree]-dirty-[content hash]).
Fixes #3817
=> Append dirty tag with content hash

src/cmd/linuxkit/cache/source.go, src/cmd/linuxkit/cache_export.go, src/cmd/linuxkit/docker/source.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/image.go
We already support `docker cache export <image>`, which creates a tar file export of the image and its config, layers, etc. This is consumable by `docker load` as well.
Whatever the `<image>` is, that is what it is called inside the tar file, and what `docker load` uses to name the image.
However, if you want to save it under a different name, you are stuck. When using `docker save` it is fine, since you can do `docker tag <image> ><newName>` and then `docker save <newName>`, but lkt cache doesn't have it.
This adds an option to override the name as saved in the tar file.
Changes to `docker cache export`.
CI and run manually.
Option to override …
=> add option to override tag name when exporting

docs/platform-virtualization-framework.md, src/cmd/linuxkit/Makefile, src/cmd/linuxkit/run_virtualizationframework_darwin_cgo_disabled.go, src/cmd/linuxkit/run_virtualizationframework_darwin_cgo_enabled.go
It is not easy to use cross-platform build with CGO enabled so lets allow build without cgo for darwin and use virtualization framework only if we built with CGO.
=> Allow build for darwin without CGO

src/cmd/linuxkit/go.mod, src/cmd/linuxkit/vendor/modules.txt
I can see 
```
pkg_build.go:10:2: package github.com/linuxkit/linuxkit/src/cmd/linuxkit/pkglib imports github.com/docker/go-units from implicitly required module; to add missing requirements, run:
go get github.com/docker/go-units@v0.4.0
```
after #3823 merged.
Let's fix this.
=> Fix github.com/docker/go-units import

src/cmd/linuxkit/build.go, src/cmd/linuxkit/cache_clean.go, src/cmd/linuxkit/cache_export.go, src/cmd/linuxkit/cache_ls.go, src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/util.go
We already can set the location of the linuxkit cache via `--cache`; this just adds the env var `LINUXKIT_CACHE`. The order of priority is the usual sane one: CLI flag >> env var >> default (`$HOME/.linuxkit/cache`)
1. Created a struct that knows about env vars and can handle the order of priority
2. Used that as `FlagSet.Var()` instead of `FlagSet.String()`
I could have replaced several others - I think env vars should be widely available - but the right approach probably is to replace everything with spf13/cobra or similar. That was too much for this one PR.
CI and manual. I did manual.
Support for LINUXKIT_CACHE env var to set cache dir.
=> allow setting cache dir via env var

.github/workflows/ci.yml
Related to https://github.com/linuxkit/linuxkit/issues/3833
=> Add a GHA target for darwin/arm64

src/cmd/linuxkit/docker/cmd.go, src/cmd/linuxkit/vendor/github.com/docker/cli/cli/connhelper/connhelper.go, src/cmd/linuxkit/vendor/github.com/docker/cli/cli/connhelper/ssh/ssh.go, src/cmd/linuxkit/vendor/modules.txt
I've got a remote docker daemon that I connect to over ssh.
Something like `DOCKER_HOST=ssh://docker-remote docker ps` works well
When I use linuxkit, with `DOCKER_HOST` set to `ssh://docker-remote` it'll silently fail to connect.
This introduced the support for a remote docker over ssh.
=> Support remote docker over ssh

.github/workflows/release.yml, Makefile
This adds a GitHub Actions workflow that should trigger on each tag creation, 
if the tag starts with the letter `v`.
It'll build linuxkit for all os/arch targets, create a checksum file and create a draft release on GitHub.
I couldn't test the very last part because I'm not authorised to create a release.
We should try and create a v0.9.0 tag or something.
See https://github.com/linuxkit/linuxkit/issues/3833
=> Add an automated release workflow

pkg/init/cmd/service/logging.go
=> Fix comments

pkg/binfmt/main.go, pkg/init/cmd/rc.init/main.go, pkg/init/cmd/service/prepare.go, pkg/init/cmd/service/runc.go, pkg/init/cmd/service/system_init.go, pkg/metadata/main.go, pkg/metadata/main_test.go, pkg/metadata/provider_aws.go, pkg/metadata/provider_cdrom.go, pkg/metadata/provider_digitalocean.go, pkg/metadata/provider_file.go, pkg/metadata/provider_gcp.go, pkg/metadata/provider_hetzner.go, pkg/metadata/provider_metaldata.go, pkg/metadata/provider_openstack.go, pkg/metadata/provider_packet.go, pkg/metadata/provider_scaleway.go, pkg/metadata/provider_vultr.go, pkg/mount/mountie.go, pkg/sysctl/main.go, pkg/sysfs/main.go
=> Remove 99% of deprecated ioutil usage (packages)

src/cmd/linuxkit/build.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/initrd/initrd.go, src/cmd/linuxkit/main.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/image.go, src/cmd/linuxkit/moby/linuxkit.go, src/cmd/linuxkit/moby/output.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/pkglib/pkglib_test.go, src/cmd/linuxkit/push_packet.go, src/cmd/linuxkit/run_aws.go, src/cmd/linuxkit/run_gcp.go, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/run_virtualizationframework_darwin_cgo_enabled.go, src/cmd/linuxkit/run_vmware.go, src/cmd/linuxkit/scaleway.go, src/cmd/linuxkit/util.go
=> Remove 99% of deprecated ioutil usage (src/cmd/linuxkit)

pkg/init/cmd/rc.init/main.go, pkg/init/cmd/service/system_init.go, pkg/metadata/provider_cdrom.go, pkg/mount/mountie.go
=> Prefer nil empty slices (packages)

pkg/host-timesync-daemon/main.go, pkg/init/cmd/service/cmd.go, pkg/init/cmd/service/prepare.go, pkg/memlogd/cmd/memlogd/main.go, pkg/metadata/main_test.go, pkg/metadata/provider_aws.go, pkg/metadata/provider_digitalocean.go, pkg/metadata/provider_gcp.go, pkg/metadata/provider_hetzner.go, pkg/metadata/provider_metaldata.go, pkg/metadata/provider_openstack.go, pkg/metadata/provider_vultr.go
=> Remove dead or redundant code (packages)

src/cmd/linuxkit/docker/cmd.go, src/cmd/linuxkit/docker/source.go
Creating the container without a network takes 50 to 80ms less.
=> Faster image export

.github/workflows/ci.yml, Makefile, test/Makefile
* eliminated unused gcp artifact hack in `test/Makefile`
* added support for specifying test suites in `make test`
* replaced all direct calls to `rtf` in GHA workflows with `make test` calls
This is worth it on its own. Once it is done, I will use matrix to create parallel packages tests, which should speed up CI.
Changes to the two Makefiles in `ci.yaml`
CI. If it works, then nothing has broken.
rtf call refactor
=> move rtf commands from GHA into make test; remove unused artifacts

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go
Since the transition to direct buildkit, `linuxkit pkg build` was ignoring the `network` setting in `build.yml` and always letting it be enabled. This fixes it.
Changes to `FrontendAttr`.
CI
Proper configuration of network mode in package build.
=> fix network build modes

src/cmd/linuxkit/pkglib/build.go
When reading the descriptors from the cache, sometimes we get a descriptor missing a platform. This causes all sort of other things to break downstream, including causing some SIGSEGV due to dereferencing the null pointer. 
This adds a check when using the descriptor that it contains a platform and, if not, returns an error that includes the descriptor in its entirety.
Added `if` statement to check for `desc.Platform`
CI
Safer handling of descriptors missing platform.
=> catch error with descriptor missing platform

.github/workflows/ci.yml, Makefile, test/Makefile
Added sharding of packages tests, to try and get it from 90 mins serial to up to 10 parallel shards in ~9 mins each.
1. Updated rtf to support shards
2. Updated to latest rtf version
3. Add shard support to `Makefile` and `tests/Makefile`
4. Add matrix to GHA under packages tests so that it has 10 shards
Run CI and then see if the results are as expected
Sharding support for much faster tests
=> add sharding option

src/cmd/linuxkit/pkg_showtag.go
Add option `lkt pkg show-tag --canonical`, which, instead of the simple image name, e.g. `linuxkit/getty:abc`, provides the canonical name `docker.io/linuxkit/getty:abc`.
Added an option to a single file.
Run it. It works.
Option to show canonical tag.
=> option to show canonical tag

src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
The current `lkt pkg build` process is treated as:
1. See if the pkg is in the cache
2. If it is not, try to pull it from the registry
3. If not in the registry, build it
That is not quite as efficient as it could be. There is no reason to pull it from registry to local cache unless you really want it. Much of the time, `pkg build` really is just saying, "I want to build it if it doesn't exist anywhere", not "I also need it in my cache." This tends to bloat the cache unnecessarily.
The change now does the following:
1. See if the pkg is in the cache
2. It it is not, see if it it is in the registry (unless overridden with `--pull`, in which case pull too)
3. If not in the registry, build it
You still can get the current behaviour with `lkt pkg build --pull`, but now …
=> Rationalize build pull

src/cmd/linuxkit/cache.go, src/cmd/linuxkit/cache/image.go, src/cmd/linuxkit/cache/remove.go, src/cmd/linuxkit/cache/resolvabledescriptor.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/cache_clean.go, src/cmd/linuxkit/cache_ls.go, src/cmd/linuxkit/cache_rm.go
Extended `lkt cache` by adding some options:
* `cache clean --published-only` will delete all images in the cache that are available on the registry. This is a nice way of saying, "remove anything from my cache that is publicly available"
* `cache rm a b c` will delete specific images a, b, c
* `cache rm --published-only a b c` will delete specific images a, b, c but only if they are published to the registry
Extending the commands.
CI as usual, plus ran it locally with multiple setups.
More fine-grained control over cache cleanup.
=> add options to clean only part of the cache

docs/metadata.md, examples/openstack.yml, examples/platform-aws.yml, examples/platform-azure.yml, examples/platform-gcp.yml, examples/platform-hetzner.yml, examples/platform-packet.yml, examples/platform-vultr.yml, examples/sshd.yml, examples/vpnkit-forwarder.yml, pkg/sshd/build.yml
Signed-off-by: Michael Aldridge <aldridge.mac@gmail.com>
Removed the default bind mount of `/root/.ssh` in the sshd package.  When using the metadata package to summon keys, the ssh directory will not be present in root's home folder on the host filesystem because the keys are summoned dynamically.  However, its not possible to just add the new bind for the `authorized_keys` file because the bind to the nonexistent directory prevents sshd from being able to start.  This change removes the default bind since it can be trivially added back using `binds.add` for anyone who wishes to statically provide an `authorized_keys` file at build time.
A single elegant emacs command.
Observe the diff, see that the bind mount is no longer …
=> pkg/sshd: Remove default bind of /root/.ssh

src/cmd/linuxkit/pkg_build.go
I checked and compared linuxkit-builder startup time for current and upstream versions of buildkit.
- I cleaned `linuxkit-builder` (buildkit) container with `docker rm -f --volumes linuxkit-builder`
- I filled the volume of `linuxkit-builder` (buildkit) with the artifacts from [EVE-OS](https://github.com/lf-edge/eve) (`make pkg/alpine pkg/acrn pkg/acrn-kernel pkg/fw pkg/pillar eve`) to have lots of data inside (16G as du indicates).
- I stopped the linuxkit-builder builder using docker commands and start it again.
- I measured the time difference before starting of `linuxkit-builder` container and the line `running server on /run/buildkit/buildkitd.sock` in `docker logs linuxkit-builder`.
For current version I get about 20 seconds to start.
For upstream …
=> Update buildkit version to speed up start time

src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
We have distinct manifest option which is not used. Let's implement different behavior.
=> Propagate manifest option into push

src/cmd/linuxkit/pkglib/git.go
`pkg show-tag` reports if a directory tree is dirty, but it misses new untracked files. If a file is in the directory, and is not tracked and also is not in `.gitignore`, we should treat that is dirty.
Added `ls-files` with appropriate options.
I tested it on various scenarios:
* new file in dir - catches it
* new file not in dir - ignores it
* new file in dir but also in `gitignore` - ignores it
`show-tag` treats untracked and unignored files as a dirty package.
=> catch new untracked and unignored files

src/cmd/linuxkit/pkglib/build.go
With the earlier PR #3863 , for `pkg build`, if the image exists in the remote registry we don't bother pulling it unless they explicitly requested `--pull`. This is much more efficient.
However, this might break `pkg push` in the following scenario:
1. `lkt pkg push pkg/foo`
2. The image is not in cache at all, but is entirely in registry
3. Nothing gets built (correctly), nothing gets pulled (correctly)
4. It now tries to push from cache and finds nothing there.
5. This fixes it so that it does not try to push if it did not build anything or find anything local
Added logic to check if we built anything or found anything locally.
I would add that there might be a cleaner way to do this, specifically just …
=> if nothing to build, do not push

src/cmd/linuxkit/pkg_showtag.go
Allow more than one packages to `lkt pkg show-tag`. It used to do that, a previous PR accidentally limited it back to 1. This fixes it.
Change one file
Run it. I did.
Multiple packages to show-tag
=> allow multiple packages for show-tag

examples/platform-aws.yml
add dhcpcd as a service as well in order to have the instance not invariably become unreachable after the lease expires
1. Follow the instructions in the docs to create an AMI
2. create an instance from the AMI
3. wait 3600 seconds (or however long the lease is in your case)
4. observe how the instance loses connectivity _at the very second_ after the lease expires
5. now create another AMI, but with this fix and observe how the instance stays up (I have one instance that hasn't become unreachable, with an up time of over 22 hours)
=> Fix examples/platform-aws.yml: add dhcpcd service to keep instance reachable after lease

docs/alpine-base-update.md
Fixed a few misleading lines on the alpine base update doc
markdown
Read it
update docs
=> fix alpine base update docs

.github/workflows/ci.yml, test/pkg/Makefile
* simplified `test/pkg/Makefile` (actually makes it very similar to `pkg/Makefile`)
* ensured `pkg/` packages are built and cached before all downstream stages in CI
* ensured `test/pkg/` packages also are built and cached before all downstream stages in CI
Changes to those files
CI, either it works or it does not
simplified test/pkg/Makefile, more robust CI pkg builds
=> Test pkgs ci makefile

pkg/swap/swap.sh
Fixes #3896
The script used to compare “10M” with “10” as if they were both integers.
We now convert the left value into an integer before comparing it to the block size.
=> Fix swap.sh

src/cmd/linuxkit/pkglib/build.go
Fixed a bug. See [this action](https://github.com/linuxkit/linuxkit/actions/runs/3844861114/jobs/6548351414) which should have pushed everything out and skipped everything.
The way `lkt pkg push` works is, it checks before pushing if there is anything to push. The logic for that says, "if I built something, try and push it; if not, look in local cache and then, if found, try and push it."
When you `put pkg push --nobuild`, it explicitly does not build. But it also skips checking the cache. This means that `--nobuild` actually means "do not build or push", when you really meant, "do not build, but if something already is in the cache, go ahead and push it." 
This fixes it so that the meaning is as expected. …
=> ensure push when already found image locally

Makefile, src/cmd/linuxkit/Makefile, tools/go-compile/Dockerfile, tools/go-compile/build.yml, tools/go-compile/compile.sh
Fixes #3885 
Updates the Makefiles to use the latest `linuxkit/go-compile`. While at it, replaces the internal linting from `golint` (deprecated) to `golangci-lint` (which we use in CI anyways).
1. Update `tools/go-compile`
2. Update `Makefile` and `src/cmd/linuxkit/Makefile`
I ran builds, let CI run as well
Update go-compile
=> use latest go-compile

examples/docker-for-mac.yml, examples/swap.yml, src/cmd/linuxkit/pkglib/pkglib.go
As discussed on https://github.com/linuxkit/linuxkit/issues/3909
Also see https://github.com/linuxkit/linuxkit/issues/3676 for an older discussionl. We may want to do more clean up and remove more references to s390x, possibly starting with the CI
=> cmd: Remove s390x as a default arch

pkg/containerd/Dockerfile, pkg/init/Dockerfile, pkg/memlogd/Dockerfile, pkg/modprobe/Dockerfile, pkg/runc/Dockerfile, pkg/sysctl/Dockerfile
This allows SBOM tools to look at /lib/apk/db/installed to determine which package versions are included in the container. This should probably be applied across all of the linuxkit containers.
Preserve /etc/apk and /lib/apk by copying it to the container
Inspect the produced containers to check that they have /lib/apk/db/installed
Retain /lib/apk/db for SBOM tools
=> Retain /lib/apk/db for SBOM tools

kernel/Makefile
Make sure those git commands run only once and not 254 times in total.
*Before:*
```
$ make -C kernel -n SHELL="/bin/bash -x" build_5.15.x
+ git rev-parse --show-toplevel
+ uname -m
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git …
```
=> Avoid running git command 254 times

kernel/Dockerfile, kernel/Dockerfile.kconfigx, kernel/Makefile, linuxkit.yml
this pr contains various improvements
* Add a target that uses buildx to generate a multiarch images. buildx enables remote builders to build multiarch images.
* Upgrade the kernel used in the sample linuxkit image
* Parallelize compression of the kernel source archive. That saves several minutes.
Add a new target in the makefile
`ORG=yourorg IMAGE=yourimage PLATFORMS=linux/arm64,linux/amd64 make -C kernel buildx_5.10.x`
kernel: Add a target for building kernel with buildx
=> Add a target for building kernel with buildx

docs/packages.md, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/git.go, test/cases/000_build/031_fixed_build_args/Dockerfile, test/cases/000_build/031_fixed_build_args/build.yml, test/cases/000_build/031_fixed_build_args/test.sh
Added some fixed default build-args that `linuxkit pkg build` passes to the docker build. These are
* `SOURCE`
* `REVISION`
* `GOPKGVERSION`
They are in the docs as well. 
These are set **only** if the user does not override them in `build.yaml`.
Also added a test, of course.
Note that I picked build-args that are tied to the filesystem and commit. Thus, they do not interfere with reproducible builds.
I did consider adding the username and host that built, but wasn't sure if that violated our "reproducible always" requirement.
Changes to `git.go` and `build.go`
CI. I added tests. And I tested manually.
Pass build-context information to package builds via `--builg-arg`
**- Note**
I have a follow …
=> include source repo, revision and go package version as build-args

src/cmd/linuxkit/build.go
When calling `lkt build`, if you do not provide `--name`, it calculates it. But later it checks if you provided `--output` and, if so, and you also have `name` set, it errors out.
It should calculate `name` if and only if `outputFile` also is not set.
Fixes a single file.
CI
Fix conflicts among CLI flags
=> handle conflict with name and output

pkg/memlogd/cmd/logread/main.go
`logread` (in `pkg/memlogd`) has an option to `-f` and follow. If not, then it reads until the end of the stream and exits.
Except it does _not_ exit, it `panic()`, even if it is getting an `EOF`.
This changes it to exit sanely if it receives an `EOF`
Changed lines in `pkg/memlogd/cmd/logread/main.go`
CI, and I did some manual testing. Beforehand, I got:
```
panic: EOF
goroutine 1 [running]:
main.main()
/go/src/memlogd/cmd/logread/main.go:69 +0x426
```
After, it just exits cleanly
Exit cleanly for logread when EOF
=> logread should not panic on an EOF, instead exiting gracefully

docs/kernels.md
Arguably the long term fix is to introduce a check for links in the documentation with tools like markdown-link-check.
=> Fix broken links in the documentation.

pkg/memlogd/cmd/logread/main.go, pkg/memlogd/cmd/startmemlogd/main.go
when we switched about a year ago from memlogd's socket having a few fields separated by ; to a json struct, it opened up possibilities, but broke some users downstream. Now they have to do all of the json parsing, etc., that we already do in logread.
This takes logread's work, puts it in a func, and exposes it, letting others consume it.
It also fixes some linting issues in memlogd.
=> expose logread function

src/cmd/linuxkit/pkglib/docker.go
When we restart a builder runner, we forgot to add the context, so docker gets confused and tries to run it locally, which can fail in odd ways.
Add 2 args to the docker runner line
CI. Plus I ran it manually.
Ensure pass docker context when restarting remote runner
=> ensure passing context when creating builder runner

pkg/init/cmd/service/logging.go
- What I did
Fix https://github.com/linuxkit/linuxkit/issues/3918
- How I did it
Updated the init pkg to remove the file at the fifo log location if it exists. This replicates the behavior of os.Create for local log files which truncates the file if it exists.
- How to verify it
Update the init container to the version of this PR and use it in `logging.yml` as specified in the issue https://github.com/linuxkit/linuxkit/issues/3918
- Description for the changelog
Allow service restarts when using memlogd
=> Allow service restarts when using memlogd

src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache/source.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/registry/manifest.go, src/cmd/linuxkit/util/index.go
This is a follow-up to #3954 ; that added sbom support to `lkt pkg build` and `lkt build`, but missed it for `lkt pkg push`. When it rebuilds and validates the index in the remote registry, it forgets to ensure that it holds onto existing attestations, as well as pushing ones from local cache.
This fixes it
Changes to `PushManifest()` and `Build()` to ensure it keeps them.
While I was at it, made the index merging much more robust, by validating each one on the remote, as well as attestations.
CI does fine, and I tested manually as well on remote registry.
push sboms
=> push sboms as well

src/cmd/linuxkit/registry/manifest.go, src/cmd/linuxkit/util/index.go
The previous sbom work fixed `pkg build` and `pkg push`, but not `pkg manifest`. This fixes `pkg manifest`. And of course tested to not break the previous.
Updated the index merging.
CI
linuxkit pkg manifest now respects existing sboms
=> fix merging indexes in pkg manifest command

src/cmd/linuxkit/cache/errors.go, src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/images.go
Fixes #3961
`validate.Image()` does not handle layers that are not actual tar+gzip, so in-toto attestations break it. Needed a workaround. Also makes it a lot simpler.
Changed source.
CI is enough.
Handle attestations on pulls better.
=> Fix image pull with attestations

src/cmd/linuxkit/cache/write.go
When looking for a ref and specific arch in the cache, if it is missing entirely or incomplete for the target platform, it does an `ImagePull()`. If that finds an index, it pulls it and, if successfully pulls, returns OK... without first checking if that index contains the target arch. So the caller thinks it found it locally, when it really didn't.
This fixes it.
Added a check post-index-pull.
CI and I checked manually.
Handle pull image is missing target architecture
=> when pulling image to cache, if it is missing target arch, indicate an error

pkg/memlogd/cmd/logread/main.go
only close socket once reading is finished
Fix bug where `logread` does not return anything
Closing socket only after reading from socket is finished.
Run `logread` in eve and see that it now prints out log messages.
Fix logread bug but not closing socket before reading.
https://www.youtube.com/watch?v=AV9z0c1hjnA&pp=ygUPYmVzdCByYXQgdHJpY2tz
=> logread: do not close socket too early

docs/kernels.md, kernel/Makefile
For kernel Makefile 
* Added option to build for other ARCH, e.g. `make build-6.6.13 ARCH=amd64`
* Added option to specify a docker builder, and, if one is not specified, to fall back to `linuxkit-linux-{{.Arch}}-builder`
* Added `make list` to list all of the outputs and targets
* Documented it all in `kernels.md`
Changes in Makefile
Run it and see; I did 
Better kernel Makefile options
=> kernels Makefile support custom builders and archs

kernel/Makefile
Fixed a script where output was redirected to `/dev/nul` instead of `/dev/null` (missing `/`)
Typing
I ran it. This is so simple, not much more than that
Fixed typo in script with /dev/nul
=> use proper null in script and not mispelled nul

src/cmd/linuxkit/cache.go, src/cmd/linuxkit/cache/blob.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/cache_import.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
* Simplified how `cache.ImageLoad()` works
* used it to create `linuxkit cache import`
* Removed accidental adding of too many manifests to cache `index.json` because of how it processed `ImageLoad()`
Lots of hard work.
CI tests most of this. I also ran manual tests on a clean cache and on a populated cache
Simplified ImageLoad, support for importing to cache
=> enable import of images from tar files

docs/packages.md, src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go, test/cases/000_build/055_dockerfiles/000_missing_in_yml/Dockerfile, test/cases/000_build/055_dockerfiles/000_missing_in_yml/build.yml, test/cases/000_build/055_dockerfiles/000_missing_in_yml/test.sh, test/cases/000_build/055_dockerfiles/001_missing_in_yml_found_cli/Dockerfile, test/cases/000_build/055_dockerfiles/001_missing_in_yml_found_cli/build.yml, test/cases/000_build/055_dockerfiles/001_missing_in_yml_found_cli/test.sh, test/cases/000_build/055_dockerfiles/002_found_in_yml_missing_cli/Dockerfile, test/cases/000_build/055_dockerfiles/002_found_in_yml_missing_cli/build.yml, test/cases/000_build/055_dockerfiles/002_found_in_yml_missing_cli/test.sh, test/cases/000_build/055_dockerfiles/003_default/Dockerfile, test/cases/000_build/055_dockerfiles/003_default/build.yml, test/cases/000_build/055_dockerfiles/003_default/test.sh
Added two build options to `lkt pkg build`
* dockerfile can be specified both in `build.yaml` and as `--dockerfile` CLI flag
* added option to override the tag when building or show-tag via `--tag <tag>`
For the dockerfile specification, this fits perfectly with the linuxkit philosophy. Everything is reproducible as it is files on the disk. The same way you can specify a different `build.yml`, you can reference the specific dockerfile.
For the tag, we allow lots of flexibility in naming the generated image. This now lets you specify the actual tag, including using templates, e.g. `--tag "version2-{{.Hash}}`. Right now, only `.Hash` is supported, but we could add a more things if they fit.
Changes
I tested manually, and added tests …
=> Dockerfile in build yml and CLI; tag templates

src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/docker.go, test/cases/000_build/056_build_args/000_build_arg_yaml/Dockerfile, test/cases/000_build/056_build_args/000_build_arg_yaml/build.yml, test/cases/000_build/056_build_args/000_build_arg_yaml/test.sh, test/cases/000_build/056_build_args/001_build_arg_cli/Dockerfile, test/cases/000_build/056_build_args/001_build_arg_cli/build-args, test/cases/000_build/056_build_args/001_build_arg_cli/build.yml, test/cases/000_build/056_build_args/001_build_arg_cli/test.sh, test/cases/000_build/056_build_args/002_build_arg_cli_over_yaml/Dockerfile, test/cases/000_build/056_build_args/002_build_arg_cli_over_yaml/build-args, test/cases/000_build/056_build_args/002_build_arg_cli_over_yaml/build.yml, test/cases/000_build/056_build_args/002_build_arg_cli_over_yaml/test.sh
Added support for specifying build args to a package build from another file as `--build-arg-file file1`. You can specify multiple files as `--build-arg-file file1 --build-arg-file file2 ...`.
This allows interesting patterns, like a `build.yaml` that is usable for multiple structures and versions of something (kernel builds are on my mind) while changing some build args.
```sh
linuxkit pkg build --build-yml build.yaml --build-arg-file build-args-1 ./pkg/foo
linuxkit pkg build --build-yml build.yaml --build-arg-file build-args-2 ./pkg/foo
```
Or if you want to get kernel-specific:
```sh
linuxkit pkg build --build-yml build-kernel.yaml --build-arg-file build-args-6.6.x ./kernel
linuxkit pkg build --build-yml build-kernel.yaml --build-arg-file build-args-5.15.x ./kernel …
```
=> add support for build-arg files

src/cmd/linuxkit/cache.go, src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache_pull.go, src/cmd/linuxkit/cache_push.go, src/cmd/linuxkit/util/reference.go
Added ability to pull images from registry directly into cache, or push from cache to registry, based on image name.
Handles both concise names (like `nginx`) and fully qualified names (like `docker.io/library/nginx:latest`).
Fixes #3990 
Added the commands.
Tested by pulling and pushing
cache pull and push by names support
=> add support for pushing and pulling images

src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache_push.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go
Added option to `lkt cache push foo` to provide a remote tag as `lkt cache push foo --remote-name bar`, which means, "take the local image or index foo, and push it to the remote bar".
This is morally equivalent to the classical "tag&push", but much simpler
Code
I did. I pushed and tested
Ability to name images remotely differently
=> option to push local image to somewhere else

kernel/Dockerfile, test/cases/020_kernel/tags.sh
kernel was missing the builder LABEL, got lost in #3993; this restores it
Changed a single line in Dockerfile
Build, push, check that the label exists (it does)
restore missing label in kernel
=> in kernel build, have ARG in correct place to be usable

kernel/Makefile, scripts/update-component-sha.sh
Added `kernel/Makefile` targets to report the tag for the kernel and debug kernel, and to replace them using `update-component-sha.sh`.
Also updates the `update-component-sha.sh` to take regex for `--hash`.
The next PR will use this.
Changed Makefile
Manually, no need for anything else, as this just adds some new capabilities.
kernel Makefile tag management
=> kernel makefile target to replace tags using update-component-sha.sh

kernel/Makefile
Fix `kernel/Makefile`, which was replacing _all_ semver with latest, rather than server-without-hash with latest
Added some $ signs to Makefile
Run it. I did.
kernel Makefile regex fix
=> in kernel makefile tag update, ensure we only replace non-hashed semver

test/cases/020_kernel/019_config_6.6.x/test.yml, test/cases/020_kernel/119_kmod_6.6.x/Dockerfile, test/cases/020_kernel/119_kmod_6.6.x/test.yml
hash-specific version of 6.6.x kernel in some tests was out of date; updated
`make`
CI
updated hash for 6.6.x kernel in tests
=> hash for kernel changed, updating in test cases

kernel/Makefile, scripts/update-component-sha.sh, test/cases/020_kernel/019_config_6.6.x/test.yml, test/cases/020_kernel/119_kmod_6.6.x/Dockerfile, test/cases/020_kernel/119_kmod_6.6.x/test.yml
Final fix of `update-component-sha.sh` and `kernel/Makefile`, so that they handle all of the edge cases correctly.
Slowly and painfully
I ran multiple replace commands, each worked exactly as expected
More update-component-sha.sh fixes for kernel
=> Fix update component too broad match

.github/workflows/package_release.yml, .github/workflows/release.yml
pkg-release flow was not picking up tags. At the same time, `release.yml` was applying to all tags, even those that did not match the pattern.
This is because we used the pattern in the `on` event in the workflow, which GitHub actions does not support. Instead, moved it to `if` condition on the job.
Change yaml file
CI
=> ensure package release flow is picked up

.github/workflows/package_release.yml
Added a missing `|` in an actions command
Typing
CI
=> missing pipe in package_release workflow

src/cmd/linuxkit/util/reference.go
before a command like
linuxkit cache pull 127.0.0.1:5000/pkgalpine
would result in trying to pull the following image: docker.io/127.0.0.1:5000/pkgalpine
and this is wrong
Trying to fix pulling from a local registry.
Grumpily ;-)
```
docker run -d -p 5000:5000 --name registry registry:latest
docker build -t localhost:5000/pkgalpine .
docker push localhost:5000/pkgalpine
linuxkit cache pull 127.0.0.1:5000/pkgalpine
```
Allow pulling from local docker registry
https://en.wikipedia.org/wiki/Bunk%C5%8D#/media/File:Sculpture_of_Brave_Dog_Bunchan_-_Otaru_-_Hokkaido_-_Japan_(47984518556).jpg
=> util: allow pulling from local registry

README.md
linuxkit build expects '--format' or '-f' and not
'-format'
=> README.md: fix format parameter

docs/packages.md, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/pkglib.go
Added `PKG_HASH` and `PKG_IMAGE` build args when building packages, in addition to the existing ones `SOURCE`, `REVISION` and `GOPKGVERSION`. Added to docs as well.
Adding to the list of `imageBuildOpts.BuildArgs`
I ran it and checked that they are there. And CI of course
Build args to pass hash tag and image name.
=> add tag to args passed for package builds

kernel/Dockerfile.bcc, kernel/Dockerfile.perf, kernel/build-bcc.yml, kernel/build-perf.yml, test/cases/020_kernel/019_config_6.6.x/test.yml, test/cases/020_kernel/119_kmod_6.6.x/Dockerfile, test/cases/020_kernel/119_kmod_6.6.x/test.yml
The build for perf and bcc were reinstalling the kernel, rather than leveraging it to build the tools. This fixes it.
Changed the build.yaml and Dockerfile.perf / Dockerfile.bcc
CI
Correctly build perf and bcc kernel tools
=> fix kernel tools build.yml files to reflect correct dockerfiles

src/cmd/linuxkit/build.go, src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/moby/opts.go, test/cases/000_build/010_reproducible/004_input_tar/test.sh, test/cases/000_build/060_input_tar/README.md, test/cases/000_build/060_input_tar/test.sh, test/cases/000_build/060_input_tar/test1.yml, test/cases/000_build/060_input_tar/test2.yml
Add a new option called `--input-tar <in.tar>`. When it sees this option, it tries to read the `linuxkit.yml` build file (aka metadata) from `<in.tar>`.
If it does not find the metadata, it builds as normal.
If it finds the metadata, it compares it to the currently building image. For each one that is identical - image name, position in section (init, onboot, onshutdown, services), settings, etc. - it finds the files from the original tar and copies them over, rather than trying to find the image in the linuxkit cache and possibly pull it down. It uses the PAXRecords on the tar to read the files.
This is a performance speed-up. For example, building `linuxkit.yml` takes ~6 seconds on my test cloud VM, while using the input tar takes ~2 seconds. Since a large part of this …
=> add support for input-tar

src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/util/reference.go
It should always canonicalize package names before reading from or writing to cache. However, it missed it reading in one place. So `foo/bar:abc` would fail to find, even though the canonical `docker.io/foo/bar:abc` _was_ there. This fixes it.
Changed the source.
CI will catch all of this.
Better canonical names in cache
=> use canonical ref when looking in cache

.github/workflows/ci.yml, .github/workflows/package_release.yml, .github/workflows/publish.yaml, .github/workflows/release.yml
Bumped several GitHub actions from v3 to v4, because of deprecation:
* actions/checkout
* actions/cache
* actions/upload-artifact
* actions/download-artifact
Changed them
CI
Update versions of actions
=> bump actions to v4 to avoid deprecation

.github/workflows/publish.yaml
Explicitly pass the GITHUB_TOKEN to action-script, because it seems to fail without it.
Added a single line to yaml file
CI
Explicit token
=> explicitly use GITHUB_TOKEN for actions script

.github/workflows/publish.yaml
With the switch to `actions/github-script@v7`, the property `github.actions` in the script now is `github.rest.actions`, so move it there.
Change the GitHub script in the workflow yaml
CI
action script v7-compatible changes
=> use proper path for github-script properties

src/cmd/linuxkit/cache/source.go, src/cmd/linuxkit/cache_export.go, src/cmd/linuxkit/docker/source.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/image.go
Fixed the `cache export` structure. It nominally supported 2 formats:
* oct
* filesystem
However, `oci` was not _really_ OCI v1 layout, but rather the docker tar format.
I changed it so that `oci` becomes a true OCI v1 layout, and added `docker` format for the docker tar
Changed `cache_export.go` to add an option, and added it to the image source
CI, mainly to ensure no regressions. Doesn't matter, as nothing else is affected, but I also tested it manually.
cache export formats
=> add cache export format OCI

src/cmd/linuxkit/util/reference.go, src/cmd/linuxkit/util/reference_test.go
Fix `util.ReferenceExpand` to support image references from non-DockerHub remote registries.
If the first part of an image reference looks like a domain, we simply return it as is.
Improve support for image references from remote registries.
fixes #4045
=> Improve support for third-party registry images

pkg/memlogd/cmd/logread/main.go
Ensured setting `dumpFollow` in memlogd `logread` actually `follow`s as well. closes #4048 
included logic: if `dumpFollow` flag is set set the `follow` flag too
1. build memlogd container: `cd pkgs/memlogd && docker build -t logreadedit .`
2. build another container with the following dockerfile
```dockerfile
FROM linuxkit/memlogd:v1.0.0-amd64 AS memlogd-1.0
FROM logreadedit AS memlogd-edit
FROM alpine:3.19    
COPY --from=memlogd-1.0 /usr/bin/memlogd /usr/bin/memlogd
COPY --from=memlogd-1.0 /usr/bin/logread /usr/bin/logread-1.0
COPY --from=memlogd-edit /usr/bin/logread /usr/bin/logread-edit
```
3. start that container interactively: `docker run -it logreadtest /bin/sh`
4. perform the following operations
```shell
memlogd & …
```
=> ensured dumpFollow of logread includes 'follow' behaviour

src/cmd/linuxkit/build.go
according to the documentation the following command is valid: `linuxkit build equinixmetal.yml equinixmetal.arm64.yml` (docs/platform-equinixmetal.md)
So, make it valid.
Allow running `linuxkit build equinixmetal.yml equinixmetal.arm64.yml`  as described in the documentation.
Just changed the cobra-args checker.
`> linuxkit build --dry-run platform-equinixmetal.yml platform-equinixmetal.arm64.yml | grep cmdline`
should output `ttyAMA0`
while 
`> linuxkit build --dry-run platform-equinixmetal.yml | grep cmdline`
should output `ttyS1`
Allow more than one yaml config for build command …
=> cmd: allow more than one config yaml for build

src/cmd/linuxkit/Makefile, src/cmd/linuxkit/version.go
The version for the `linuxkit` binary was consistently giving `v0.8+` from something hard-coded into the Makefile.
This changes the `src/cmd/Makefile` so it calculates the version. The version will be almost the equivalent of `git describe --tags`.
* If the most recent tag of semver pattern `v*` points to the HEAD commit, then version is injected as `vX.Y.Z` (the semver)
* If the most recent tag points to an earlier commit, then version is injected as `vX.Y.Z-<count>-<shorthash>`, i.e. the equivalent of `git describe --tags`
* In all cases, if there are uncommitted changes, append `-dirty`
Changes to `src/cmd/linuxkit/Makefile`
CI obviously, although this should affect nothing in CI. Build it with various commits and run `linuxkit …
=> properly save linuxkit version

.github/workflows/release.yml, Makefile
The final release workflow - on tags starting with `v*` - builds all of the versions of linuxkit. These all work well via cross-compilation, except for macOS. macOS needs CGO, which is very messy in cross-compilation.
GitHub Actions support macOS runners, so this uses a macOS runner to build macOS linuxkit, then combines all of the binaries into a single directory and then creates the release.
Changed Makefile targets and `release.yml`.
CI and then cut a release, which I will do.
Native compilation for macOS in pipelines.
=> separate release builds of macOS CGO from others

src/cmd/linuxkit/moby/build/images.yaml, tools/grub-dev/Dockerfile, tools/grub/Dockerfile, tools/mkimage-iso-efi-initrd/Dockerfile, tools/mkimage-iso-efi-initrd/make-efi-initrd, tools/mkimage-iso-efi/Dockerfile, tools/mkimage-iso-efi/make-efi, tools/mkimage-qcow2-efi/Dockerfile, tools/mkimage-qcow2-efi/make-efi, tools/mkimage-raw-efi/Dockerfile, tools/mkimage-raw-efi/make-efi
Fixes #4068 
Removed any references to `linuxefi` and `initrdefi` when building EFI images for x86_64, as the EFI handover has been deprecated, per https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cc3fdda2876e58a7e83e558ab51853cf106afb6a
1. Removed `linuxefi` module from `linuxkit/grub-dev`
2. Regenerated `linuxkit/grub`
3. Changed the grub config files in the various packages
4. Ran `scripts/update-component-sha.sh` for all of the above
CI to ensure no regression, and build an image to check
Removal of deprecated `linuxefi` call.
=> remove linuxefi grub EFI handover to normal linux loading

src/cmd/linuxkit/docker/cmd.go, src/cmd/linuxkit/moby/build/images.go
Fixes that under certain cases the container image is already in the local docker registry, but with the wrong architecture; in this case just pretend it is not there and let the caller decide if they want to build it
Check that linuxkit does accidentaly take a docker image with the wrong architecture.
Check architecture before taking it.
https://github.com/lf-edge/eve/pull/4150 - enable DockerCache and run `make test`
https://media2.giphy.com/media/4Ho5aPCXJEzOqcwddj/giphy.webp?cid=ecf05e47j41oybtdpecws1b12gvms2d2wdg82uciccnty2bd&ep=v1_gifs_search&rid=giphy.webp&ct=g
=> moby: check architecture for docker image

src/cmd/linuxkit/cache/find.go, src/cmd/linuxkit/cache/imagesource.go, src/cmd/linuxkit/cache/indexsource.go, src/cmd/linuxkit/cache/layout.go, src/cmd/linuxkit/cache/platform.go, src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/cache_export.go, src/cmd/linuxkit/moby/build/build.go, src/cmd/linuxkit/moby/build/image.go, src/cmd/linuxkit/moby/build/images.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/spec/cache.go, src/cmd/linuxkit/spec/image.go
Internally, we used arch to define images we wanted, implicitly assuming OS always was `linux`. While mostly correct - this is _linuxkit_ - it makes the internal tools less useful, as you cannot pull down or check other platforms in images. That will become useful in future volume definitions. There is a follow-on PR ready for it, but I separated the "no functionality, all internal" changes from the "new functionality" changes.
Restructured internal cache commands and all references.
CI.
Internal changes to support cache on multiple platforms, not just OS=linux
=> internal restructure to use explicit platform instead of implicit arch in cache

docs/yaml.md, src/cmd/linuxkit/moby/build/build.go, src/cmd/linuxkit/moby/schema.go
Added support for volumes as OCI v1 layout.
`volumes` section already has the ability to populate a volume with the contents of an OCI Image by merging it into a filesystem. Sometimes, you want to just have the image as is. This gives an option to lay it out in OCI v1 layout format, with all of the blobs and index.json. You also can choose which architectures to include.
This is useful if one of your processes is not _running_ a container - the `onboot`, `services`, etc. are excellent for that - but _working with_ a container image.
Added options to the `volumes` section, updated the schema, updated the doc.
CI
Support for image-based volumes with OCI v1 layout rather than expanding filesystem
=> additional volume support in building

docs/packages.md, src/cmd/linuxkit/buildtemplate.go, src/cmd/linuxkit/const.go, src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/pkglib/pkglib.go, test/cases/000_build/057_pkg_tag/000_tag_yaml/Dockerfile, test/cases/000_build/057_pkg_tag/000_tag_yaml/build.yml, test/cases/000_build/057_pkg_tag/000_tag_yaml/test.sh, test/cases/000_build/057_pkg_tag/001_tag_cli/Dockerfile, test/cases/000_build/057_pkg_tag/001_tag_cli/build.yml, test/cases/000_build/057_pkg_tag/001_tag_cli/test.sh, test/cases/000_build/057_pkg_tag/002_tag_cli_over_yaml/Dockerfile, test/cases/000_build/057_pkg_tag/002_tag_cli_over_yaml/build.yml, test/cases/000_build/057_pkg_tag/002_tag_cli_over_yaml/test.sh
Added support for tag template in `build.yaml`. We already support `--tag <template>` in CLI, so add it to `build.yaml` as well.
Extended the definition of `pkgInfo` so it also includes `Tag`, which then will cause it to read it.
Of course, updated docs and added tests.
CI
Support for tag templates in build.yml
=> support --tag in build.yml for packages

src/cmd/linuxkit/moby/build/images.yaml, tools/mkimage-raw-efi/make-efi
fixes #4095
Adjusted the calculations in the raw-efi build script.
Looked into the FAT design (https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system) and `mkfs.fat` source code (https://github.com/dosfstools/dosfstools/blob/master/src/mkfs.fat.c).
I think the problem for the too small image size is the growing File Allocation Table. The current assumption of 511 KiB of headroom is only true for images with a size of around 250 MB.
This is still only an approximation of the total size an no guarantee that it will work under all circumstances as the calculations in https://github.com/dosfstools/dosfstools/blob/master/src/mkfs.fat.c are quite convoluted/complex.
**- A picture of a cute animal …
=> Fix raw efi build image size calculation

src/cmd/linuxkit/util/arch.go
kernel+squashfs flow didn't work for riscv64, which was due to it missing in MArch function
Added riscv64
Run minimal.yml with -arch riscv64
Fixed bug preventing kernel+squashfs to work for riscv64 target
=> feat: add riscv64 as supported arch

src/cmd/linuxkit/cache/open.go
Follow up to cache index locking. It worked, but fails on new cache because it tries to lock a non-existent file. Instead, it creates a different tmp file (consistent name) as a lock file, uses that, creates the proper `index.json`, and then releases the lock.
As described 
CI. Also, I tried it manually.
Proper lock handling for new cache.
=> ensure that new index does not break on missing lock file

docs/image-cache.md
Modified `docs/image-cache.md` to note how one can export from a local docker instance into linuxkit
closes #4126 
NA
NA
Add instructions for importing images from local docker instance
=> docs: Add instructions for OCI export from Docker

src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/pkglib/docker.go
Fixed how linuxkit asks buildkit to do auth, when explicit credentials are provided using CLI. Also, handle the special use case of `docker.io`.
Does not affect inserting creds from `docker login`.
With difficulty, until Tonis Tiigi explained the special case.
CI, plus tests I ran.
Handle docker.io registry-creds correctly.
=> fix registry auth

src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/cache_clean.go, src/cmd/linuxkit/cmd.go, src/cmd/linuxkit/pkg_remotetag.go, src/cmd/linuxkit/registry/manifest.go, src/cmd/linuxkit/registry/remote.go, test/cases/000_build/080_mirrors/config.yml, test/cases/000_build/080_mirrors/test.sh, test/cases/000_build/080_mirrors/test.yml, test/cases/040_packages/025_auth/test.sh
Fixes #4142 
Added support for using mirrors to override default registry for specific registries or all registries
You will be able to do:
```sh
$ lkt --mirror http://mymirror.local      # to mirror all
$ lkt --mirror ghcr.io=http://mymirror.local      # to mirror just ghcr.io
$ lkt --mirror ghcr.io=http://mymirror.local/ghcr --mirror http://mymirror.local/other      # to mirror ghcr and rest differently
```
Added the CLI flag, then rewrite the URL
CI
We probably should add a specific test for this, but I struggled to figure out how. Maybe I will get it
mirror support
=> provide mirror support

src/cmd/linuxkit/cmd.go, src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/registry/remote.go
Added ability to specify paths to cert files to use, in addition to system certs, when interacting with OCI registries
Added a persistent CLI flag and added to Transport
CI
Support for additional certs
=> add support for specifying additional certificates

src/cmd/linuxkit/pkglib/git.go
this makes `--dry-run` inconvenient as it includes a newline
trimming all whitespaces around the GOPKGVERSION
Run
```
~/src/linuxkit/src/cmd/linuxkit/linuxkit pkg build --platforms linux/amd64 --force --dry-run pkg/pillar
```
check that after `--build-arg=GOPKGVERSION=v0.0.0-20250828163257-a2e7a9467df0` there is no newline
Fix trailing newline after GOPKGVERSION
=>  pkglib/git: remove trailing spaces of GOPKGVERSION

src/cmd/linuxkit/cache/provider.go
even checking if the file-lock object is non-nil needs to be guarded with the lock
`go test -race` output:
```
==================
WARNING: DATA RACE
Read at 0x00c0005283f0 by goroutine 17:
github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache.(*Provider).Lock()
/home/runner/go/pkg/mod/github.com/linuxkit/linuxkit/src/cmd/linuxkit@v0.0.0-20250829112740-179f74ac245b/cache/provider.go:57 +0x55
github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache.(*Provider).Index()
/home/runner/go/pkg/mod/github.com/linuxkit/linuxkit/src/cmd/linuxkit@v0.0.0-20250829112740-179f74ac245b/cache/provider.go:47 +0x47
github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache.(*Provider).FindDescriptor()
/home/runner/go/pkg/mod/github.com/linuxkit/linuxkit/src/cmd/linuxkit@v0.0.0-20250829112740-179f74ac245b/cache/find.go:86 …
```
=> cache/provider: use lock correctly

src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/depends.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/dockerdryrun.go, src/cmd/linuxkit/pkglib/dockerimpl.go, src/cmd/linuxkit/pkglib/utils.go
there is already a public method "WithBuildDocker", so it makes sense that the parameter definition is public as well so that a user of this method can actually use it
also allow dry-run with specific docker-runner
no new feature was implemented, everything should work as before
make `dockerRunner` public
untangle `dockerRunner` and `DryRun`
(ChatGPT was very lazy today ...)
=> pkglib/build: make dockerRunner public

src/cmd/linuxkit/Makefile, src/cmd/linuxkit/cache_import.go, src/cmd/linuxkit/pkglib/build.go
Fixed a bug in the `linuxkit cache import` command where it was failing when trying to import from stdin. The command was incorrectly treating the dash "-" (which conventionally represents stdin in Unix tools) as a regular filename instead of recognizing it as the stdin indicator.
Modified the stdin handling logic in `src/cmd/linuxkit/cache_import.go` to properly detect when "-" is passed as the input argument and route it to stdin processing instead of file processing. Also fixed Go formatting issues in `pkglib/build.go` that were preventing the `make local-check` target from passing.
Try importing a docker image from stdin like
```bash
docker image save <image:tag> | linuxkit cache import -
```
it should not throw an error like …
=> Fix cache import from stdin
