README.md
There was a duplication in the README.md wording
=> fix wording in README.md

examples/sshd.md
=> examples: Add doc on how to use the SSHD example

docs/architecture.md
=> Fix link to kernels directory

kernel/README.md
=> Fix link. Cosmetic.

docs/architecture.md
=> Fix broken link to pkg dir

docs/dockercon-summit.md
My raw notes - might have missed some bits but hopefully captured the essence of the session. Also opened an issue for the mailing list.
=> summit: add notes from session 1 bof

examples/sshd.md
=> Typo in link to sshd.yml

examples/minimal.yml
=> examples: Add a minimal YAML file

src/cmd/linuxkit/push.go, src/cmd/linuxkit/push_gcp.go, src/cmd/linuxkit/run.go, src/cmd/linuxkit/run_gcp.go, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/run_vmware.go
Signed-off-by: Lorenzo Fontana <lo@linux.com>
=> Removed moby from the linuxkit's push help

docs/mac.md
=> docs: Clarify hyperkit networking

scripts/kernels/debian.sh, scripts/kernels/ubuntu.sh
The previous PR had two syntax errors from testing...
=> kernels: Fix annoying error in shell scripts

examples/swap.yml
cc @deitch the hash wasnt pushed to hub; we should have auto builds soon to fix this...
=> Update tag for swap package, having pushed to hub

reports/2017-04-30.md
https://en.wikipedia.org/wiki/European_robin#/media/File:Erithacus_rubecula_with_cocked_head.jpg
=> Development report for 30 April 2017

projects/okernel/README.md
Fix mispelling
Straight up
Correct spelling mistake
=> Spelling error: Dautenhan -> Dautenhahn

Makefile
=> Fix make clean to remove new -kernel files

src/cmd/linuxkit/run_qemu.go
I added the `-publish` option to the `qemu` runner for the linuxkit cmd
**Usage**
```bash
$ linuxkit run qemu -publish 8080:80 -publish 8081:80 example
```
or even
```bash
linuxkit run qemu -publish 1111:1111/udp -publish 8081:80/tcp example
```
**Help output**
```
Please specify the prefix to the image to boot
USAGE: linuxkit run qemu [options] prefix
'prefix' specifies the path to the VM image.
Options:
-arch string
Type of architecture to use, e.g. x86_64, aarch64 (default "x86_64")
-cpus string
Number of CPUs (default "1")
-diskpath string
Path to disk image to use
-disksize string
Size of disk to create, only created if it doesn't exist
-fwpath string
Path to OVMF firmware for UEFI boot (default "/usr/share/ovmf/bios.bin")
-gui
Set qemu to use video output instead of stdio
-iso
Set …
```
=> Port forwarding in qemu runner

tools/alpine/Dockerfile, tools/alpine/versions
=> Include virtual packages in alpine mirror

reports/2017-05-08.md
=> Add development report for 8 May

examples/docker.yml, examples/gcp.yml, examples/minimal.yml, examples/node_exporter.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/containerd/Dockerfile, pkg/containerd/Makefile, pkg/runc/Dockerfile, pkg/runc/Makefile, projects/etcd/etcd.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/okernel/examples/okernel_simple.yaml, test/cases/test-docker-bench.yml, test/cases/test-kernel-config.yml, test/cases/test-ltp.yml, test/cases/test-virtsock-server.yml, test/kmod/kmod.yml, tools/alpine/packages, tools/alpine/versions
From new Alpine base, with Go.
=> Multistage builds for containerd and runc

src/initrd/initrd.go
Remove duplicated code and clean up file handling a little.
=> Clean up initrd creation library

examples/docker.yml, pkg/docker-ce/Dockerfile, projects/kubernetes/image-cache/Dockerfile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, test/cases/test-docker-bench.yml
This means we can potentially start dogfooding the build as this has nested build support.
=> Update to Docker 17.05

docs/gcp.md
Just fixing a small typo in one of this document's links. 
=> Correct gcp.yml Example URL Path

test/cases/test-virtsock-server.yml, test/pkg/virtsock/Dockerfile
I've updated https://github.com/rneugeba/virtsock/
This PR updates the test package and test image
=> Update virtsock test

scripts/LinuxKit.ps1
=> scripts: Rename named pipe for the serial port on Hyper-V

examples/docker.yml, examples/gcp.yml, examples/minimal.yml, examples/packet.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/containerd/Dockerfile, projects/clear-containers/clear-containers.yml, projects/etcd/prom-us-central1-f.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/landlock/landlock.yml, projects/okernel/examples/okernel_simple.yaml, test/cases/test-docker-bench.yml, test/cases/test-kernel-config.yml, test/cases/test-ltp.yml, test/cases/test-virtsock-server.yml, test/kmod/kmod.yml
Updated to containerd that has the fix for the logging issue #1660. I havent managed to replicate #1661 yet so that is probably fixed.
=> Switch to containerd

Makefile
=> Update Moby tool

examples/gcp.yml, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/swarmd/swarmd.yml, projects/swarmd/swarmd/Dockerfile, projects/swarmd/swarmd/Dockerfile.pkg, projects/swarmd/swarmd/Makefile
* Updated swarmd pkg build (using multistage builds) and switch to current https://github.com/docker/swarmkit/pull/1965 commit.
* Added `metadata`, `ntpd` and persistent disk (`format` + `mount`). Disk is on `/var/lib/swarmkit`
* Switch to one shot DHCP mode
* Use host pid namespace
* Updated to latest `init`+`runc`+`containerd` packages.
In addition updates other users of `pkg/metadata` to the latest version while I was there.
Mainly emacs.
Build and run.
Updated swarmkit project assembly.
=> projects/swarmd: Updates

src/cmd/linuxkit/run_vmware.go
Added the capability to re-use or create a disk from the linuxkit VMware cli
Using the `vmware-diskmanager` that comes with Fusion/Workstation
Run `linuxkit run vmware` with the `-disk` `-disk-size` arguments
Persistent disk functionality added into the VMware backend.
=> Added matching capability to create a disk

reports/2017-05-15.md
=> Add development report for 15 May 2017

sigs/security/README.md
Missed this in my last PR by mistake
=> Update security SIG reports link

docs/kernels.md
=> docs: Add a section on custom kernel builds

reports/sig-security/2017-05-24.md
Adding namespaced IMA support to the agenda cc @tych0 
=> update SIG agenda with IMA namespace support

Makefile, examples/docker.yml, examples/gcp.yml, examples/packet.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/sysctl/.gitignore, pkg/sysctl/Dockerfile, pkg/sysfs/.gitignore, pkg/sysfs/Dockerfile, pkg/sysfs/Makefile, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/okernel/examples/okernel_simple.yaml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/040_packages/000_sysctl/test-sysctl.yml, tools/alpine/Dockerfile, tools/alpine/go-compile.sh, tools/alpine/versions, tools/go-compile/compile.sh
Minor tweaks to both versions of go-compile, update sysfs to use alpine base image and same build as sysctl.
=> more Go compile fixes

src/cmd/linuxkit/run_qemu.go
Default remains qcow2 but you can specify raw or other supported formats.
=> Allow specifying the format of a qemu drive

reports/sig-security/2017-05-24.md
=> Add time and announce info to security SIG report

reports/2017-05-22.md
=> Add development report for 22 May 2017

reports/sig-security/2017-05-24.md
For the Wednesday kickoff meeting!  cc @tych0 
=> Add more detail to security SIG agenda

.mailmap, AUTHORS
=> Add a few more aliases to .mailmap and re-generated AUTORS

test/cases/000_build/000_outputs/test.sh, test/cases/000_build/100_examples/000_minimal/test.sh, test/cases/000_build/100_examples/010_docker/test.sh, test/cases/000_build/100_examples/020_sshd/test.sh, test/cases/000_build/100_examples/030_redis/test.sh, test/cases/000_build/100_examples/040_swap/test.sh, test/cases/000_build/100_examples/050_node_exporter/test.sh, test/cases/010_platforms/000_qemu/000_run_kernel/test.sh, test/cases/010_platforms/000_qemu/010_run_iso/test.sh, test/cases/010_platforms/000_qemu/020_run_efi/test.sh, test/cases/010_platforms/000_qemu/030_run_qcow/test.sh, test/cases/010_platforms/000_qemu/100_container/test.sh, test/cases/010_platforms/010_hyperkit/000_run_kernel/test.sh, test/cases/020_kernel/000_config_4.4.x/test.sh, test/cases/020_kernel/001_config_4.9.x/test.sh, test/cases/020_kernel/002_config_4.10.x/test.sh, test/cases/020_kernel/003_config_4.11.x/test.sh, test/cases/020_kernel/010_kmod_4.9.x/test.sh, test/cases/040_packages/000_sysctl/test.sh
This goes against collective responsibility for code. If you want to know the
author use git.
=> Remove AUTHOR from tests

reports/sig-security/2017-05-24.md
Here are the meeting notes from the recent SIG-security meeting.
=> sig-security: 2017-05-24 meeting notes

reports/sig-security/2017-06-07.md
Will update more as I post to forum, get more agenda input.  cc @tych0 
=> sig-security: add draft agenda for 2017-06-07 meeting

reports/sig-security/2017-05-24.md
=> sig-security: Add video recording to meeting notes

reports/sig-security/2017-05-24.md
thank you @cyli for spotting this!
=> sig-security: Fix link to ima-namespace project

src/cmd/linuxkit/run_hyperkit.go
Add a new flag to set the VPNKit ethernet socket path. Defaults to auto,
which will try to use the existing socket from Docker for Mac.
This flag can be used to connect to the VPNKit instance started by
another linuxkit VM launched with `-start-vpnkit`. VMs connected to the
same VPNKit instance will be on the same virtual internal network.
(related to discussion in #1891)
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
=> linuxkit: add -vpnkit-socket flag

docs/virtual-os-tools.md, pkg/open-vm-tools/Dockerfile, pkg/open-vm-tools/Makefile
Added the package to build `open-vm-tools` for use within linuxkit and for use with VMs hosted on the VMware hypervisor.
Used the `linuxkit/alpine` image to install `open-vm-tools` to a fakeroot and copied that into a new scratch container. 
Use:
```
- name: open-vm-tools
image: "linuxkit/open-vm-tools:<HASH>"
```
as part of the `services:`
Added open-vm-tools as part of the packages for linuxkit.
=> open-vm-tools package

Makefile
=> rebuild bin/moby as necessary

examples/gcp.yml, examples/swap.yml, linuxkit.yml, projects/ima-namespace/ima-namespace.yml, projects/logging/examples/logging.yml, projects/wireguard/wireguard.yml
=> Remove unnecessary namespace I missed

reports/2017-05-28.md
Slightly late, due to holiday, sorry!
=> Add development report for week to 28 May 2017

pkg/metadata/main.go, pkg/metadata/provider_aws.go
Added an AWS provider to the metadata package as referenced here: #1918
Added a new provider to metadata package and wired it up.
I built the image and ran it on an EC2 instance and verified the correct data was added to /var/config
Added an AWS provider to the metadata package
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>
=> Added AWS provider to metadata package

docs/yaml.md
Fix section names, add internal links,
=> Update configuration docs

reports/2017-06-03.md
=> Add development report for 6 June

src/cmd/linuxkit/run_vcenter.go
Added a new flag to wait on the `run` command that will return the IP address from the new guest, once the `open-vm-tools` have started
New flag `-waitForIP` that adds an extra function once the host has started.
```
./bin/linuxkit run vcenter -datastore=vSphereNFS -network=HomeNetwork \
-hostname=esxi01.fnnrn.me -powerOn -persistentSize=1024 -\
vmfolder=linuxkitIP -waitForIP ./linuxkit.iso 
{...}
Powering on LinuxKit VM
Waiting for OpenVM Tools to come online
Guest IP Address: 192.168.0.198
```
Use of `OpenVM-Tools` to return the guest IP address once the VM has booted.
=> Added capability to wait for the OpenVM tools to report the IP of new VM

src/cmd/linuxkit/push_aws.go
Added more log statements to` linuxkit push aws`
added more debug statements where they were needed
If you run a linuxkit push aws command with verbose you will see more logs.
Added more log statements to` linuxkit push aws` command, for greater visibility. 
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>
=> Added more log statements to linuxkit push aws command

docs/aws.md, docs/metadata.md
improved the aws docs
wrote some more docs
read the docs
Improved the docs for AWS
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>
=> Improved the AWS docs

reports/sig-security/2017-06-07.md
thank you @mgoelzer for being our scribe!  The video recording is still processing on zoom, will update in a followup PR once the youtube link is ready
=> sig: notes for 2017-06-07

reports/sig-security/2017-06-07.md
=> sig: youtube link for 2017-06-07

reports/sig-security/2017-06-21.md
@l0kod: is 30 minutes sufficient for your deep dive?  Please feel free to suggest edits to my agenda items - this is only a draft :)
=> sig: initial draft schedule for next security sig meeting

pkg/swap/README.md, projects/kubernetes/boot-master.sh, projects/kubernetes/boot-node.sh, projects/miragesdk/README.md, test/pkg/virtsock/README.md
- change `-disk-size` to `-disk <optional_path>,size=$SIZE`
- bonus: update `moby run` to `linuxkit run`
Closes #2006
=> Tool disk syntax change

Makefile
This assumes you are in the right directory, have Go set up etc.
=> Add a "local" make target that does not use Docker

linuxkit.yml, test/cases/000_build/000_outputs/test.yml, test/cases/010_platforms/000_qemu/000_run_kernel/test.yml, test/cases/010_platforms/000_qemu/010_run_iso/test.yml, test/cases/010_platforms/000_qemu/020_run_efi/test.yml, test/cases/010_platforms/000_qemu/030_run_qcow/test.yml, test/cases/010_platforms/000_qemu/040_run_raw/test.yml, test/cases/010_platforms/000_qemu/100_container/test.yml, test/cases/010_platforms/010_hyperkit/000_run_kernel/test.yml, test/cases/020_kernel/000_config_4.4.x/test-kernel-config.yml, test/cases/020_kernel/001_config_4.9.x/test-kernel-config.yml, test/cases/020_kernel/003_config_4.11.x/test-kernel-config.yml, test/cases/020_kernel/010_kmod_4.9.x/kmod.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/030_security/010_ports/test.yml, test/cases/040_packages/002_binfmt/test-binfmt.yml, test/cases/040_packages/003_ca-certificates/test-ca-certificates.yml, test/cases/040_packages/004_dhcpcd/test-dhcpcd.yml, test/cases/040_packages/013_mkimage/mkimage.yml, test/cases/040_packages/013_mkimage/run.yml, test/cases/040_packages/019_sysctl/test-sysctl.yml, test/hack/test-ltp.yml, test/hack/test.yml
Missed in #2004
Not updated projects.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Migrate base linuxkit.yml to getty, and tests to new init

docs/platform-aws.md
- Replace img with raw for moby -output
Signed-off-by: Jes Ferrier <jes.ferrier@gmail.com>
=> Update aws platform docs

docs/platform-hyperkit.md
=> Remove stray `

reports/2017-06-11.md
Week 23 dev reports, comments welcome!
=> reports: add week 23 dev report

projects/kubernetes/README.md, projects/kubernetes/boot-master.sh, projects/kubernetes/boot-node.sh, projects/kubernetes/boot.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, src/cmd/linuxkit/run_qemu.go, test/cases/000_build/000_outputs/test.sh, test/cases/020_kernel/000_config_4.4.x/test.sh, test/cases/020_kernel/001_config_4.9.x/test.sh, test/cases/020_kernel/003_config_4.11.x/test.sh, test/cases/020_kernel/010_kmod_4.9.x/test.sh, test/cases/040_packages/002_binfmt/test.sh, test/cases/040_packages/003_ca-certificates/test.sh, test/cases/040_packages/004_dhcpcd/test.sh, test/cases/040_packages/013_mkimage/test.sh, test/cases/040_packages/019_sysctl/test.sh
Some small updates to `projects/kubernetes`:
* kubernetes: update to latest init
* kubernetes: Combine boot-{master,node}.sh into a single script
* kubernetes: give each instance a specific state directory
* kubernetes: Create disk in state dir
and some improvements to the qemu runner:
* Add state dir support to Qemu runner.
* Add metadata support to Qemu runner.
The scripting can now be used to boot master & nodes on both Linux and MacOS.
After building `./boot.sh` and `./boot.sh 0 -join wibble` should boot on both MacOS and Linux, although due to #2031 I've not been able to fully test that. Note that on Linux the node is not yet expected to be able to contact the master, since I haven't sorted out the networking side yet.
**- …
=> Small improvements to projects/kubernetes

examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/minimal.yml, examples/node_exporter.yml, examples/redis-os.yml, examples/sshd.yml, examples/swap.yml, examples/vmware.yml, linuxkit.yml, pkg/getty/README.md, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml
New getty images to pick up updates from #2036, I pushed and signed `linuxkit/getty:886d35fe30c47750e8cfbf2f73016e9d2cc6361a`
cc @deitch 
=> Update getty image for setsid changes

docs/platform-packet.md
Closes #2046 
Documentation for Linuxkit on Packet
Bring up linuxkit on Packet, take notes, incorporate them into documentation.
Someone who is familiar with Packet should verify correct information.
Someone who is not familiar with Packet but familiar with linuxkit should be able to get started from these notes.
Improve documentation for booting Linuxkit on Packet
=> [Work in progress] Packet documentation

reports/2017-06-19.md
Signed-off-by: Anil Madhavapeddy <anil@docker.com>
=> reports: Add week 24 development report

projects/miragesdk/src/sdk/api.ml, projects/miragesdk/src/sdk/ctl.ml, projects/miragesdk/src/sdk/ctl.mli
=> sdk: add missing files

reports/sig-security/2017-06-21.md
=> sig-security: add forum link to announcement

kernel/Makefile
inuxkit/kernel -> linuxkit/kernel
sourcs -> sources
Fixed spelling errors in kernel/Makefile
Fixed spelling errors in kernel/Makefile
=> Fix spelling errors

reports/sig-security/2017-06-21.md
=> sig-security: add meeting notes for 2017-06-21

reports/sig-security/2017-06-21.md
=> sig-security: add video link

reports/2017-06-19-summit.md
Thanks to @mgoelzer for note taking.
=> Add notes from BoF at Summit

reports/2017-06-19-summit.md
See https://github.com/linuxkit/linuxkit/pull/2090#issuecomment-310403710
=> Fix typo in report

README.md
Could do with a better tutorial, but at least make the ordering clearer
=> Slighly clearer getting started docs

src/cmd/linuxkit/run_qemu.go
The default is set by probing for /dev/kvm. Use of KVM can be forcibly disabled
with `-enable-kvm=false`. Note that passing `-enable-kvm=true` when `/dev/kvm` is
not present still boots but complains:
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory
Back to tcg accelerator.
Added `-enable-kvm` option to `linuxkit run qemu`.
Plumbed in some new golang `flags` usage.
Try passing `-enable-kvm` or `-enable-kvm=false` before and after renaming `/dev/kvm` to something else.
LinuxKit run using QEMU backend can now opt-in/out to use of KVM. Default remains to autodetect.
**- A picture …
=> qemu: Add -enable-kvm to force (attempted) use (or not) of KVM

reports/sig-security/2017-07-05.md
cc @ndauten - let me know if I should add/tweak things!  I'll post in moby forum / email out the agenda after this is merged
=> sig-security: agenda for 2017-07-05

examples/vultr.yml
cc @furious-luke: could you please validate this `vultr.yml`?  I'm not too familiar with vultr and will try to do so myself as well.
=> add vultr example

blueprints/docker-for-mac.yml, examples/docker.yml, pkg/docker-ce/Dockerfile, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/kubernetes/image-cache/Dockerfile, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
=> Update Docker CE to 17.06.0

reports/sig-security/2017-07-05.md
=> sig-security: add announcement for memorizer

projects/miragesdk/examples/fdd.yml, projects/miragesdk/src/fdd/Dockerfile, projects/miragesdk/src/fdd/Makefile, projects/miragesdk/src/fdd/exec.ml, projects/miragesdk/src/fdd/exec.mli, projects/miragesdk/src/fdd/fdd.ml, projects/miragesdk/src/fdd/jbuild, projects/miragesdk/src/fdd/share.ml
Lots of boilerplate for now on, will work on upstreaming that in the tool
properly if needed later.
=> sdk: add a yml example on how to use fdd to create container channels

projects/swarmd/README.md, projects/swarmd/swarmd.yml, projects/swarmd/swarmd/Dockerfile, projects/swarmd/swarmd/Makefile
A basic containerd executor has now been merged into swarmkit, but there are additional enhancements in my WIP branch, including CNI networking, so continue to track that for now.
This also integrates a weave container and adds the weave and reference CNI plugins to the swarmd container.
Also updates the build and resyncs with mainline linuxkit.yml.
Buidl an image from projects/swarmd/swarmd.yml and marvel in the swarmy goodness.
Updated projects/swarmd.
[![](https://www.metal-archives.com/images/2/0/8/7/208724.jpg?3819 "Bison B.C., Quiet Earth")](https://www.metal-archives.com/albums/Bison_B.C./Quiet_Earth/208724)
=> Refresh projects/swarmd and add networking support

reports/2017-07-02.md
=> reports: week 26 development report

reports/sig-security/2017-07-05.md
cc @ndauten please let me know if you'd like us to include slides/other notes
=> sig-security: add meeting notes from 2017-07-05

reports/sig-security/2017-07-05.md
=> SIG: add slides link for ops+memorizer

src/cmd/linuxkit/run_qemu.go
Current implementation hardcodes the virtual machine as
"q35" for x86, this patch remove this hardcode and configure
the machine type according to the ARCH the VM is running on.
Also, in order to make sure the qemu can run on arm64 platform,
we need to specify the vcpu type in the command line.
This commit will not affect the behavior of x86, and can verified by:
#linuxkit run qemu -arch "aarch64" ... or
#linuxkit run qemu ...
=> ARM64: Remove the hardcode of virtual machine type

docs/security-events.md
=> docs: add some more CVE writeups

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/gcp.yml, examples/vultr.yml, pkg/metadata/Dockerfile, pkg/metadata/main.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/swarmd/swarmd.yml
This should enable adding defaults to the image and over write them with metadata/userdata/
=> Allow metadata package to over write existing config files

Makefile
=> Add raw files to make clean

reports/2017-07-09.md
=> reports: week 27 development report

kernel/Makefile, pkg/package.mk
- use image spec metadata https://github.com/opencontainers/image-spec/blob/master/annotations.md
- omit commit if dirty
fix https://github.com/moby/tool/issues/20
Initial commit for discussion before rebuilding everything...
=> Add labels for repo and commit to packages

reports/sig-security/2017-07-19.md
I guess I didn't have coffee the other morning...
As noted, the agenda will likely differ but that's fine cc @zx2c4
=> fixup sig-security agenda

blueprints/docker-for-mac/base.yml, docs/external-disk.md, examples/docker.yml, examples/swap.yml, pkg/mount/mount.sh, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/kubernetes/mounts.rb, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
=> pkg/mount: Remove set -x

tools/guestfs/Makefile
Signed-off-by: Liqdfire <liqdfire@gmail.com>
fixes #2215 
Corrected BASE defined in Makefile
=> fix BASE in Makefile to match Dockerfile

blueprints/docker-for-mac/base.yml, linuxkit.yml, pkg/getty/etc/securetty, pkg/getty/usr/bin/rungetty.sh, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/shiftfs/shiftfs.yml, test/cases/040_packages/007_getty-containerd/test-ctr.yml
Was annoying me by being ultra verbose...
cc @deitch
=> remove -x from getty script

docs/platform-vmware.md
Added documentation that details the usage and architecture behind the VMware backends.
N/A
N/A
VMware documentation that details the VMware Fusion/vSphere/vCenter backends.
=> Added VMware documentation

blueprints/lcow.yml, pkg/init-lcow/Dockerfile, pkg/init-lcow/init
- New improved init script borrowed from `pkg/init/bin/rc.init`
- Updated version of opengcs which has a fix for permissions of the container root fs
(this is still using my dev tree as neither the networking nor the fs permission PR have been merged)
=> Additional LCOW fixes

reports/sig-security/2017-07-19.md
Here's the notes from the recent sig-security meeting.
=> sig-security: add notes from 2017-07-19

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
My PRs have been merged. no need to use my dev tree
=> LCOW: Use master of the main opengcs repo again

tools/alpine/versions
Following up on #2265, I've already pushed and signed `linuxkit/alpine:4248059c38452217ff63853869df36034a890401`
=> tools/alpine: update version

src/cmd/linuxkit/run_qemu.go
The motivation for this is networking out (in particular, testing NFS
support) from the VM.
We could be a lot more user friendly (a la libvirt) by creating the tap
device for users and allowing them to specify a bridge instead, but then
we'd need root to create this tap device. For now, let's make people do
their own tap devices, and just use them. A tap device can be created for a
bridge as follows:
and then used by:
$ ./bin/linuxkit run qemu -tap-device linuxkit0 linuxkit
=> support tap devices in qemu backend

projects/swarmd/swarmd.yml
I think this was missed by #2274 due to a race with #2272.
Nothing else was missed AFAICT.
=> swarmd: Bump getty again

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
No major changes, just an update. Did some light testing with busybox
=> Update LCOW to latest opengcs version

blueprints/docker-for-mac/base.yml, examples/docker.yml, linuxkit.yml, pkg/binfmt/Dockerfile, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/shiftfs/shiftfs.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/040_packages/002_binfmt/test-binfmt.yml
As this is read only it should be explicitly created.
=> Add mountpoint to binfmt image

blueprints/docker-for-mac/base.yml, examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/packet.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/sysctl/etc/sysctl.d/00-linuxkit.conf, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/miragesdk/examples/fdd.yml, projects/miragesdk/examples/mirage-dhcp.yml, projects/okernel/examples/okernel_simple.yaml, projects/shiftfs/shiftfs.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml, test/cases/040_packages/003_containerd/test-containerd.yml, test/cases/040_packages/019_sysctl/test-sysctl.yml
The value we set is the default anyway.
=> Remove kernel.random.write_wakeup_threshold from sysctl

reports/sig-security/2017-08-02.md
first-cut at next week's agenda – very excited to get an overview of Alpine Linux's security mission and roadmap from @ncopa!
=> sig-security: add agenda for 2017-08-02

tools/alpine/go-compile.sh, tools/alpine/versions.x86_64
available as
linuxkit/alpine:c23813875499d85163dc358fc6370c9de650df57
=> Provide way for programs to use CGO with go-compile script if they need to

docs/kernel-perf.md
=> doc: Add documentation on how to use the 'perf' utility.

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
=> LCOW: Update GCS to the latest version

reports/sig-security/2017-08-02.md
=> add notes from security sig yesterday

reports/sig-security/2017-08-02.md
=> sig-security: add video for alpine SIG

docs/platform-hyperkit.md, src/cmd/linuxkit/run_hyperkit.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/vendor.conf, src/cmd/linuxkit/vendor/github.com/moby/hyperkit/README.md, src/cmd/linuxkit/vendor/github.com/moby/hyperkit/go/hyperkit.go, src/cmd/linuxkit/vendor/github.com/moby/hyperkit/src/include/xhyve/virtio.h
Code in line with QEMU, other than hyperkit only boots off UEFI ISOs not BIOS ISOs at present.
=> Support UEFI ISO boot on hyperkit

examples/aws.yml, examples/azure.yml, examples/docker.yml, examples/gcp.yml, examples/getty.yml, examples/node_exporter.yml, examples/packet.yml, examples/sshd.yml, examples/swap.yml, examples/tpm.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml, pkg/rngd/Makefile, pkg/rngd/cmd/rngd/main.go, pkg/rngd/cmd/rngd/rng_linux_amd64.go, pkg/rngd/cmd/rngd/rng_linux_arm64.go, pkg/rngd/cmd/rngd/rng_unsupported.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/etcd/etcd.yml, projects/ima-namespace/ima-namespace.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, projects/logging/examples/logging.yml, projects/miragesdk/examples/fdd.yml, projects/okernel/examples/okernel_simple.yaml, projects/shiftfs/shiftfs.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
Although it does not do anything, as there is no CPU rng on arm64 at present.
=> Support rngd on arm64

src/cmd/linuxkit/run_qemu.go
Signed-off-by: Zachery Hostens <zacheryph@gmail.com>
Have qemu runner save the mac address that is generated within state to be reused on restart. Without this each run (even with an existing state) generates a new mac address. In turn the hostname changes since it uses the mac address.
This is useful for [at least] `projects/kubernetes` if you want the master/nodes to stick around after a reboot without having to drain/delete the nodes.
Check state directory for a `mac-addr` file and use this for the mac address. If not found generate a random one and save for future runs.
run an image and check state directory for `mac-addr` file.  Kill / run again using same state directory and validate same mac address is used.
**- Description …
=> save mac address within state for qemu

docs/packages.md
=> docs: Clarify restrictions for packages builds/signing

src/cmd/linuxkit/run_hyperkit.go
Much easier to follow and more correct; also ignores directories.
fix #2385
=> Robustify ISO/kernel detection on hyperkit

projects/kubernetes/ssh_into_kubelet.sh
PR #1299 moved "ctr exec" into "ctr tasks exec" so update the kubernetes project to reflect this.
Signed-off-by: Tim Potter <tpot@hpe.com>
Fix ssh_into_kubelet.sh script to work.
s/ctr exec/ctr tasks exec/
Follow instructions in projects/kubernetes/README.md to create a cluster and verify running ./ssh_into_kubelet.sh actually runs ssh into the kubelet container.
Update ssh_into_kubelet.sh to use ctr tasks exec.
```
_.-'\          |\-"""-/|          /`-._
_.-`     `.       /         \       ,'     '-._
_.'           `._   ;   \   /   ;   _,'           `._
.'                 `-.:           :.-'                 `.
,` …
```
=> Update ssh_into_kubelet.sh to use ctr tasks exec

.mailmap, AUTHORS
=> Update authors with recent first-time contributors

reports/sig-security/2017-08-16.md
=> add agenda for security SIG on the 16th

tools/alpine/packages
Added `sgdisk` package to `tools/alpine` so we can use it in builds of packages
Just added it to the `packages` file
Create a Dockerfile `FROM` the version, and `add sgdisk`. If it works, it was installed.
Add sgdisk package to tools/alpine
I know I am supposed to do something as well with `packages.versions`, but not sure what?
=> Add sgdisk package to linuxkit/alpine

tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
=> tools/alpine: Update base image

src/cmd/linuxkit/run_packet.go
Note it cannot deal with hashed host keys still... but slightly cleaner.
=> Simpler known_hosts parsing

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
=> tools/alpine: Add ethtool

log.txt
=> Delete accidentally committed and merge file

projects/kubernetes/README.md
As I keep forgetting where this is documented...
=> Add documentation for how to run a single node Kube cluster

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
I manually tested it with busybox and it seems to work
=> Update to latest OpenGCS for LCOW

projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml
Meant to do this in the runtime PR...
=> Use new runtime mkdir instead of mkdir container

blueprints/docker-for-mac/docker-17.06-ce.yml, examples/docker.yml, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, projects/kubernetes/kube-master.yml, projects/kubernetes/kube-node.yml, test/cases/030_security/000_docker-bench/test-docker-bench.yml
=> Update Docker CE image to 17.06.1

reports/sig-security/2017-08-16.md
=> sig-security: add okernel video and forum post

src/cmd/linuxkit/run_hyperkit.go
=> Add missing case when running non existent file in hyperkit

projects/kubernetes/README.md
Having described all the setup describing the acgual usage seems useful!
=> kubernetes: document the final step for bridged networking

src/cmd/linuxkit/run_qemu.go
Tested with:
- boot from kernel + initrd with metadata (appears as sr0)
- boot from iso with no metadata (root is sr0)
- boot from iso with metadata (root is sr0, metadata is sr1)
- boot from iso with metadata using containerized qemu
In all cases where it was present the metadata was correctly expanded to
/var/config.
=> qemu: Support ISO boot at the same time as metadata

projects/miragesdk/src/Dockerfile, projects/miragesdk/src/sdk/api.ml, projects/miragesdk/src/sdk/conf.ml, projects/miragesdk/src/sdk/flow.ml, projects/miragesdk/src/sdk/host.ml, projects/miragesdk/src/sdk/jbuild, projects/miragesdk/src/sdk/net.ml
This commit removes pins to development version of capnp for the SDK. Now everything compiles with only properly released versions.
=> [miragesdk] Update to latest capnp & capnp-rpc & charrua

src/cmd/linuxkit/run_qemu.go
This PR is used to fix the issue #2488.
Currently we use '-net' the old way to initialize a host nic
interface, this method will not work on arm64 platform(#2488 issue),
so we use the '-netdev' method which will work on both arm64 and amd64.
Fix the networking issue in 'tap' mode on arm64 platform
1.Add a new networking device 2. Add a networking interface in QEMU backed by the device created in step 1.
Test it on both arm64 and amd64 platform after applied this patch, both system can enter into shell with valid network connection with outside world, eg, we can access the nginx service remotely from another machine.
**- A picture of a cute animal …
=> qemu: Fix the networking issue in 'tap' mode on arm64

blueprints/lcow.yml, pkg/init-lcow/Dockerfile
=> Update OpenGCS and LCOW blueprint

projects/kubernetes/.gitignore, projects/kubernetes/Makefile, projects/kubernetes/boot.sh, projects/kubernetes/cri-containerd.yml, projects/kubernetes/cri-containerd/Dockerfile, projects/kubernetes/kube.yml, projects/kubernetes/kubernetes/Dockerfile, projects/kubernetes/kubernetes/kubeadm-init.sh, projects/kubernetes/kubernetes/kubelet.sh, tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
* Refactored and reworked metadata handling to allow automatic startup of master nodes as well.
* Refactored initial set of yaml files to be applied to be controlled by the end user rather than baking into the kubelet image.
* Newer version of cri-containerd
* Fixed a bug with kubelet's monitoring of disk usage by providing it a version of `du` which it likes.
=> Kubernetes updates

Makefile
Includes update EFI ISO generation.
=> Update moby tool to latest version

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
available as: linuxkit/alpine:a94acee63dc1d0bd5cd5006d66514f62373650f2
Package for x86 and arm64 signed and pushed.
relates #2541 
/cc nuald
=> tools/alpine: Add wireless-tools and wpa_supplicant

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
=> tools/alpine: Add cifs-utils

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.x86_64
New package is at: linuxkit/alpine:3fb44354a34b05134fbf585a00217cd2f8c8f0bf
=> tools/alpine: Add nfs-utils

Makefile
=> Add fmt/lint/etc and test to local target

projects/README.md
Added a link to the Kubernetes linuxkit project
Addition in the README.md
Click on the link should go to the relevant linuxkit kubernetes project 
Addition of the link to the kubernetes linuxkit project
=> Update README.md to include link towards Kubernetes project

pkg/ip/Dockerfile
- opened issue #2606 for `linuxkit/alpine` pre-reqs 
- added iptables, ebtables, ipvsadm, and bridge-utils to `pkg/ip`
Edited `pkg/ip/Dockerfile`
`pkg/ip` builds
pkg/ip: added iptables, ebtables, ipvsadm, and bridge-utils
=> pkg/ip: added iptables, ebtables, ipvsadm, and bridge-utils

src/cmd/linuxkit/run_openstack.go
Signed-off-by: Marco Mariani <marco.mariani@alterway.fr>
Fixed a typo which leaved a %s in the log message.
=> log message fix: Info() -> Infof()

blueprints/docker-for-mac/base.yml, test/cases/040_packages/002_binfmt/test.yml
=> Update binfmt hashes

examples/redis-os.yml
=> Update the redis OS example to Redis 4.0

src/cmd/linuxkit/pkglib/pkglib.go
Fixed a trivial description error
=> fixed -disable-content-trust parameter description

projects/kubernetes/docker.yml
I should try and remember to do this more regularly it seems...
=> kubernetes: Bump to Docker 17.10-ce

.travis.yml
=> Do not test on Go master

src/cmd/linuxkit/pkglib/pkglib.go
$USER and "dev" respectively.
Might be too specific to my personal workflow but figured I'd throw it out there in case there was interest.
=> linuxkit pkg: add `--dev` to force local org and hash

projects/kubernetes/README.md, projects/kubernetes/boot.sh
Autoinit does not harm after initial bootstrap and state should not be deleted by default.
=> Kubernetes: Autoinit and persistent state by default

README.md, docs/platform-rpi3.md
=> docs: Add documentation for the Raspberry Pi 3b

blueprints/docker-for-mac/base.yml, blueprints/docker-for-mac/metadata.json, docs/metadata.md, examples/aws.yml, examples/gcp.yml, examples/openstack.yml, examples/packet.yml, examples/vultr.yml, pkg/metadata/main.go, pkg/metadata/main_test.go, projects/etcd/etcd.yml, projects/etcd/prom-us-central1-f.yml, projects/swarmd/swarmd.yml
This PR intends to fix https://github.com/linuxkit/linuxkit/issues/2641
It introduces a new recursive JSON structure.
=> metadata: handle json with more than 2 levels

projects/kubernetes/Makefile
This was not actually detecting Darwinianism.
=> Fix darwin conditional in Kub Makefile

projects/kubernetes/boot.sh
=> Create state dir before trying to touch file in it

pkg/format/format.go
After partitioning make waiting for the device durable again
stat can fail - simply don't exit when it does
This is hard to reproduce but we were getting this bug with fresh disks numerous times today
format pkg has retries `stat` again when waiting for the partition device
=> After partitioning we now retry the stat prior to formatting

blueprints/docker-for-mac/base.yml, examples/docker.yml, examples/swap.yml, projects/kubernetes/kube.yml, projects/swarmd/swarmd.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/005_by_device_force/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
=> Update tags for format

.circleci/config.yml, README.md
- Use `.exe` extension for windows binary
- Add CircleCI Batch to README.md
=> Minor tweaks to CircleCI config

examples/aws.yml, examples/gcp.yml, examples/openstack.yml, examples/swap.yml, examples/vmware.yml, examples/vultr.yml, linuxkit.yml
Also make them more consistent in small ways
=> Bind mount /etc/resolv.conf into nginx container

src/cmd/linuxkit/run_vbox.go
=> Connect cable on virtualbox networking

src/cmd/linuxkit/run_hyperkit.go
Allow the VPNKit executable to be specified via a flag
You can change the path via a command line flag
Use the new flag `linuxkit run hyperkit -vpnkit $some_vpnkit_executable` 
Allow the VPNKit executable to be specified via a flag
=> Allow vpnkit executable path to be specified

docs/platform-aws.md, src/cmd/linuxkit/push_aws.go
This needs to be set to nil if empty.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Fix sriov flag on AWS

src/cmd/linuxkit/run_vbox.go
this was more-or-less discussed at https://github.com/linuxkit/linuxkit/issues/2076
=> add the -gui flag to vbox run

src/cmd/linuxkit/run_vcenter.go
At the request of a user on slack, added in the capability to auto find a host that can be used to push an image to a vCenter cluster.
If `-hostname` isn't used it will return all hosts in the DC cluster and then use `rand` to choose one of them.
Tested using the `-hostname` and omitting the flag, both pushed to the datastore successfully.
This adds the capability to auto-find a vSphere host in a vCenter cluster as one is needed for image upload. This doesn't add any additional load to the cluster as no virtual machines are started or created.
=> Added capability to find a host if -hostname isn't specified

blueprints/docker-for-mac/base.yml, examples/cadvisor.yml, examples/docker.yml, examples/swap.yml, pkg/format/format.go, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, test/cases/030_security/000_docker-bench/test.yml, test/cases/040_packages/003_containerd/test.yml, test/cases/040_packages/005_extend/000_ext4/test-create.yml, test/cases/040_packages/005_extend/001_btrfs/test-create.yml, test/cases/040_packages/005_extend/002_xfs/test-create.yml, test/cases/040_packages/006_format_mount/000_auto/test.yml, test/cases/040_packages/006_format_mount/001_by_label/test.yml, test/cases/040_packages/006_format_mount/002_by_name/test.yml.in, test/cases/040_packages/006_format_mount/003_btrfs/test.yml, test/cases/040_packages/006_format_mount/004_xfs/test.yml, test/cases/040_packages/006_format_mount/005_by_device_force/test.yml, test/cases/040_packages/006_format_mount/010_multiple/test.yml
fix #2844
check if last char of partition is numeric
run on nvme
mount: fix for nvme naming convention
=> format: fix for nvme

blueprints/docker-for-mac/base.yml, docs/metadata.md, examples/aws.yml, examples/gcp.yml, examples/openstack.yml, examples/packet.yml, examples/vultr.yml
Update hashes in `examples/` and `docker-for-mac/` to use the latest `linuxkit/metadata` with `/run/config`
Changed hashes in 7 files
Build and run images.
Use `linuxkit/metadata` with `/run` support
=> Update hashes to use latest metadata

src/cmd/linuxkit/run_hyperv.go
The Windows 10 Fall Creators Update added a new 'Default
Switch' (which is a NAT switch). Use it if present and the
user has not specified a switch.
Also, handle External switches with spaces in them.
resolves #2373
=> cmd/hyperv: Use Default Switch if present

docs/platform-qemu.md
=> docs: Add initial qemu documentation

src/cmd/linuxkit/pkglib/git.go
Closes #2887
Signed-off-by: Roman Shaposhnik <rvs@zededa.com>
Added a logic that determines whether the package is at the top level of the git repo. If it is we use the tree hash from the commit itself.
Modified treeHash function to take above into account
I built the current packages in LK (to make sure there are no
regressions) plus I also built this:
https://github.com/rvs/zen-dnsmasq
It is now possible to have linuxkit package definition at the very top of the git repository (one package per git repo model)
=> Make it possible to key the package tags off of top level tree hash

.mailmap, AUTHORS, docs/kernels.md, examples/rt-for-vmware.yml, scripts/prefix-with-number.sh
Signed-off-by: Tiejun Chen <tiejun.china@gmail.com>
------
v4:
* Fix one missing change in .mailmap
v3:
* Keep .mailmap sorted alphabetically
v2:
* Separate the last commit
* Update AUTHOR
v1:
* As promised in #2897, I submit this script as well. 
* Add one example yml file, and mention this support in docs/kernels.md and will maintain this part in the future.
=> Clarify to support Preempt-RT kernel

src/cmd/linuxkit/pkglib/docker.go
Signed-off-by: Garth Bushell <garth.bushell@oracle.com>
Add --build-arg to the docker build command if there is any http proxy vars set so the build uses them to.  
Modify the docker runner
Run behind a http_proxy and run `linuxkit -v pkg build -dev ./tools/mkimage-iso-efi/` this whould fail before patch. Notice the --build-arg added to docker command
Adds all proxy environment vars as docker build --build-arg if set
=> Support http proxy environment variables in linuxkit build

reports/2018-01-31.md
=> reports: Add Jan 2018 report

reports/2018-02-28.md
=> reports: Add February 2018 report

Makefile
static pie only seems to work on Alpine currently, but static is
a good default. Give the user choices...
=> Add more local build options and make static non-pie the default

reports/2018-04-30.md
=> Add April 2018 report

src/cmd/linuxkit/run_hyperkit.go
=> Update to allow the new locations for Docker for Mac socket paths

docs/releasing.md
=> docs: Add document on how to do releases

reports/2018-05-31.md
=> LinuxKit report May 2018

tools/alpine/packages, tools/alpine/versions.aarch64, tools/alpine/versions.s390x, tools/alpine/versions.x86_64
sntpc is a very simple ntpc client, which may be useful
for some setups.
=> tools/alpine: Add sntpc to alpine base

src/cmd/linuxkit/run_aws.go
- set userdata for AWS
- set security group
=> Add support for aws metadata and security groups in linuxkit run

reports/2018-06-30.md
=> June 2018 LinuxKit report

Makefile
=> Bump version to v0.5+

Makefile
Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>
=> Update version to v0.6+

reports/2018-07-31.md
A little late due to holidays, but here is the July 2018 LinuxKit development report.
=> July 2018 report

docs/releasing.md, examples/cadvisor.yml, examples/docker-for-mac.yml, test/cases/030_security/000_docker-bench/test.yml
Also update the release note which files need updating.
=> Update all uses of DinD to 18.06.0-ce

reports/2018-08-31.md
=> Add August 2018 development report

reports/2018-09-30.md
=> September 2018 development report

.circleci/config.yml, test/hack/test.yml
=> Fix golint on circleci and GCP testing

README.md
Just adding another project to the list of sub-projects
Editing some text :)
Look at the README :)
=> README: add the LinuxKit Nix project

reports/2018-10-31.md
=> October 2018 development report

ADOPTERS.md, README.md
Please add your use cases here. There are many adopters that I know about but have not
documented here, please fill this in.
I divided this into production users, and also linked a selection of open source projects
that I know about here.
=> Add incomplete ADOPTERS file

reports/2018-11-30.md
=> November 2018 development report

src/cmd/linuxkit/run_qemu.go
Add config flags to allow "linuxkit run qemu" to mount host USB devices.
The "usb" flag enables the qemu USB host controller, and "devices" multi-flag to specify each device added. This doesn't work for "containerized" qemu runs since that requires passing devices to docker as well.
`linuxkit run qemu -usb -device usb-ehci,id=ehci -device usb-host,vendorid=0x0001,productid=0x0001`
Add USB host devices to linuxkit qemu run
=> Add qemu USB device pass through

reports/2018-12-31.md
=> December 2018 development report

reports/2019-01-31.md
Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>
=> January 2019 development report

reports/2019-02-28.md
=> February 2019 report

projects/compose/image/Dockerfile
Signed-off-by: James McCoy <james@mcy.email>
Updated Compose and Docker versions in the Dockerfile.
Updated the version and download links.
Built locally and rebuilt linuxkit
Updated Compose image to 1.23.2 and Docker versions to 18.06.3-ce.
=> Updated Compose and Docker versions.

docs/kernels.md
The directory the link previously went to has changed.
=> Update example link

examples/static-ip.yml
Signed-off-by: mcy <james@mcy.email>
Added a minimal static IP example yml.
Static IP based on  #2516 which will hopefully save someone some time and frustration......
Built localy and ran, checked IP was set and could ping IP.
Added static IP example.
Sorry not today :open_mouth:
=> Add static IP example

src/cmd/linuxkit/moby/docker.go
=> Update Docker API version

reports/2019-03-31.md
=> March 2019 development report

Makefile
=> Bump version to v0.7+

AUTHORS, reports/2019-04-30.md
=> April 2019 report and authors update

AUTHORS, reports/2019-05-31.md
=> May 2019 development report (and Author update)

src/cmd/linuxkit/moby/config.go
Nothing special, just an error message fix.
=> Error message is related to init image, not on boot.

README.md
=> Add local build requirements

src/cmd/linuxkit/run_qemu.go
With rng-random, booting hangs before switching
to the initrd.
fixes https://github.com/linuxkit/linuxkit/issues/3320
=> cmd/qemu: Disable rng on macOS

MAINTAINERS
Added myself to the maintainers list as I would like to help maintain this project.
Edited the MAINTAINERS file
N/A
=> Add Dave Tucker as a Maintainer

.mailmap, AUTHORS, examples/aws.yml, examples/docker-for-mac.yml, examples/gcp.yml, examples/hetzner.yml, examples/openstack.yml, examples/packet.yml, examples/scaleway.yml, examples/swap.yml, examples/vultr.yml
- Update the use of the swap and metadata packages in the YAMLs
- Update Authors
=> Update use of packages and AUTHORS

.github/workflows/ci.yml
Moved the linuxkit binary in to /usr/local/bin.
Removed trailing spaces (oops)
With VS Code
N/A
=> actions: Clean Up Post Merge

ADOPTERS.md
Trivial update to the documentation
=> Updating pointer to EVE

docs/platform-aws.md
This is the same as #3468 
Signed-off-by: Aymen EL AMRI <aymen@eralabs.io>
=> add SG to linuxkit run command

README.md
=> [README] deprecated infrakit

examples/docker-for-mac.yml, pkg/binfmt/Dockerfile, test/cases/040_packages/002_binfmt/test.yml
fix #3339
This has fixed a lot of outstanding emulation issues, see comments
in https://github.com/docker/binfmt/pull/24
=> Update to Qemu 4.2.0 from Debian testing

linuxkit.yml
The original one is not supported on arm64
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
=> Update nginx image in example

src/cmd/linuxkit/pkglib/manifest.go
fixed a var naming issue that triggered lint
Fixes #3580 
renaming a var
CI
Fix lint issue
=> fix lint issue

Makefile
=> build: Bump rtf to latest

docs/packages.md, src/cmd/linuxkit/cache/find.go, src/cmd/linuxkit/cache/provider.go, src/cmd/linuxkit/cache/pull.go, src/cmd/linuxkit/cache/push.go, src/cmd/linuxkit/cache/resolvabledescriptor.go, src/cmd/linuxkit/cache/source.go, src/cmd/linuxkit/cache/write.go, src/cmd/linuxkit/docker/source.go, src/cmd/linuxkit/moby/image.go, src/cmd/linuxkit/moby/images.go, src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkg_push.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/pkglib.go, src/cmd/linuxkit/pkglib/readerctx.go, src/cmd/linuxkit/spec/cache.go, src/cmd/linuxkit/spec/image.go
Support cross-building packages (cross-building OS images already is complete)
Modify the linuxkit binary to support `--platform` options
CI
Support image cross-build
=> cross build packages

pkg/trim-after-delete/main.go
Trigger fstrim for image/container/builder/volume prune events.
=> [POS-17] Add more docker event types to trigger fstrim

examples/cadvisor.yml, examples/docker-for-mac.yml, examples/docker.yml, projects/compose/compose-dynamic.yml, projects/compose/compose-static.yml, test/cases/030_security/000_docker-bench/test.yml
Wasn't sure if anything else was needed to bring these up to date 😅 
/cc @rn @justincormack
=> Update docker 20.10.6

tools/alpine/packages
Include `lvm2`
Include `lvm2` in `tools/alpine/packages`
Include `lvm2`
https://images-cdn.9gag.com/photo/aGpMQqK_700b.jpg
=> Include `lvm2`

src/cmd/linuxkit/pkglib/docker.go
Make `linuxkit pkg build` work again on Windows. It works in v0.8.
Previously when we set `cmd.Stderr = os.Stderr`, the stderr from buildx would be mixed with the image tar, corrupting it.
Work around this (Windows-specific) problem by adding an explicit indirection via a io.Pipe(). This loses console formatting (but perhaps it's the Windows "console" that was the root cause).
On Windows:
Before:
```
PS C:\Users\dave\github.com\djs55\linuxkit> .\src\cmd\linuxkit\linuxkit.exe pkg build -force .\pkg\format
Building "linuxkit/format:cf335053c7d0b4cd8cc2d136e9392ea5904a71dc"
building docker.io/linuxkit/format:cf335053c7d0b4cd8cc2d136e9392ea5904a71dc
Building for arch amd64 as …
```
=> linuxkit: fix pkg build on Windows

scripts/update-component-sha.sh
Added an option to `update-component-sha.sh` that allows you to do `--pkg`, so if you want to update everything to whatever the latest is in `pkg/init`, you just need to do:
```
./scripts/update-component-sha.sh --pkg ./pkg/init
```
Modified the shell script
Run it. I did.
Easier to use update-component-sha
=> update-component-sha --pkg option

src/cmd/linuxkit/moby/linuxkit.go, src/cmd/linuxkit/moby/output.go
Signed-off-by: 谢瑶瑶 <yaoyao.xyy@alibaba-inc.com>
=> fix: #3742 golint requires comments on non-main package for blank import

.github/workflows/publish.yaml
Ensure dir bin/ exists when downloading linuxkit binary in release.yaml workflow
Changes to `release.yaml`
CI, then merge to master and hope
=> ensure bin/ dir exists, parametrize linuxkit filename

docs/kernels.md
Added docs about the three ways to find the kernel builder image
Updated `docs/kernels.md`
Just read it; it is docs.
Document how to find the builder for kernels.
=> add docs about how to find the builder

src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/push_gcp.go, src/cmd/linuxkit/run_gcp.go
Add options to support vTPM-enabled VMs on GCP
=> Support for vTPM on GCP

src/cmd/linuxkit/pkglib/docker.go
Signed-off-by: Davide Brini <waldner@katamail.com>
=> Fix: #3799 golint requires comments on non-main package for blank import

pkg/trim-after-delete/main.go
Docker Desktop proxies the docker socket at its default location
(/var/run/docker.sock), but allows connecting to the non-proxied
socket through /var/run/docker.sock.raw.
This patch allows the trim-after-delete utility to customize
the docker socket path, so that it can connect to the non-proxied
socket.
Related: https://github.com/linuxkit/linuxkit/pull/3539
```markdown
Add `-docker-socket` flag to `trim-after-delete` utility
```
=> pkg/trim-after-delete: make docker socket path configurable

src/cmd/linuxkit/pkglib/docker.go
We check only for existence of builder container and do not start it in
case of not running state. We should start it for example after reboot
of node to be able to build something.
=> Restart of the builder container

src/cmd/linuxkit/cache_export.go
Add ability to export cache in layered filesystem format rather than just OCI layout
Added CLI flag option to `lkt cache export`. Default remains `"oci"`, but now can do `-format "filesystem"`
Run it. I did.
Can export filesystems from cache.
=> add ability to export filesystem

src/cmd/linuxkit/pkglib/git.go
If we cannot open file for some reason it is better to skip it instead of exit. Also we should skip symlinks and directories.
=> Skip files in contentHash()

src/cmd/linuxkit/pkglib/build.go
We cannot build for another arch after building for one arch because of setting `skipBuild` to true if one arch found. In other words `linuxkit pkg build --platforms linux/riscv64,linux/amd64 ...` after `linuxkit pkg build --platforms linux/amd64 ...` will not build for linux/riscv64  which is not expected.
In general when we check for available images and able to found part of platforms we do not want to rebuild all of them. So this PR includes `platformsToBuild` slice which we fill with platforms we want to build for.
=> Fix bug: when request to build multiple arches, if one already found, it skips the others

src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/pkg_builder.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go, src/cmd/linuxkit/pkglib/utils.go
We use dedicated docker container as builder and we are able to clean data inside only by re-creating of it. Let's add disk usage and clean commands for builder.
=> Builder disk usage and clean

docs/platform-aws.md
as per description - add crucial note about ENA for `linuxkit push aws` to platform-aws.md
=> docs/platform-aws.md: add crucial note about ENA for `linuxkit push aws`

src/cmd/linuxkit/moby/build.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/registry/manifest.go, src/cmd/linuxkit/run_packet.go, src/cmd/linuxkit/run_qemu.go, src/cmd/linuxkit/scaleway.go, src/cmd/linuxkit/util.go
=> Prefer nil empty slices (src/cmd/linuxkit)

.github/workflows/release.yml
=> Fix workflow's name

.github/workflows/release.yml
Fixes https://github.com/linuxkit/linuxkit/issues/3839
=> Auto generate Release Notes

docs/troubleshooting.md
Started a troubleshooting doc, if only to help us remember how to solve problems.
Right now it has only one issue listed, but since I spent quite some time tracking it down yesterday, let's avoid that happening to anyone a second time.
markdown
Read it
troubleshooting doc
=> start troubleshooting doc

examples/logging.yml, pkg/logwrite/logwrite.go, test/cases/040_packages/011_kmsg/test.yml, test/cases/040_packages/012_logwrite/test.yml
Fix logwrite to work after #3807 broke it
Change to `pkg/logwrite`
CI will do it. Changing this package should cause all logwrite to be updated.
logwrite can read json
**Note:** this blocks #3888
=> Logwrite sync with memlogd

.github/workflows/ci.yml, .github/workflows/publish.yaml
Updated the following actions versions from v2 to v3:
* upload-artifact
* download-artfifact
* cache
Search and replace
CI: if it works, it is good
Updated actions versions
=> bump actions artifact upload/download versions

src/cmd/linuxkit/pkglib/build_test.go
=> chore: import packages only once

docs/kernels.md
Updated kernel documents so they are easier to understand, and reflect the recent changes.
By hand.
Read it.
Updated kernel docs
=> updated kernel documents

docs/yaml.md, linuxkit-template.yml, src/cmd/linuxkit/build.go, src/cmd/linuxkit/buildtemplate.go, src/cmd/linuxkit/const.go, src/cmd/linuxkit/moby/config.go, src/cmd/linuxkit/moby/linuxkit.go, src/cmd/linuxkit/pkg.go, src/cmd/linuxkit/spec/packagefinder.go, test/cases/000_build/010_reproducible/test.yml
Added support for package templates in our image build `yml`. This still references files, so it stays with the "linuxkit philosophy" of everything checked in and reproducible (or as close as possible).
Of course, documented as well.
This will help significantly in our tests.
Changed files, added documentation, added a sample template
CI.
Support for templates
=> template in yaml file

src/cmd/linuxkit/pkg_build.go, src/cmd/linuxkit/pkglib/build.go, src/cmd/linuxkit/pkglib/build_test.go, src/cmd/linuxkit/pkglib/docker.go
Added option to have different reporting formats for `lkt pkg build`, like `docker buildx build` does; even using same name `--progress`. 
Changed it
Run a build, check the output
Package build more verbose logging option
=> option to control progress in pkg build

docs/kernels.md, kernel/Makefile
Added another kernel Makefile target that updates all yamls appropriately for the correct supported versions
Changed the Makefile and the doc
Run `make` and see.
kernel Makefile targets for updating yamls
=> update kernel Makefile for targets for yamls

.github/workflows/ci.yml, .github/workflows/publish.yaml, scripts/update-component-sha.sh
Make kernel build, check for dependency changes, and publish part of CI
Added steps to `ci.yaml` and `publish.yaml`
This is part of CI, so let CI do it
kernel build and publish part of CI
=> make kernel read/build and check part of CI

.github/workflows/package_release.yml
Fixed the GitHub workflow for releasing packages with tags
Changed the workflow file
CI. The last one failed, hopefully this will work.
=> fix pkg release action workflow

.github/workflows/package_release.yml, .github/workflows/release.yml
* Building linuxkit during pkg-release was broken; fixed `go build`
* renamed the two release flows to make them easier to understand
Changed yaml files
CI
=> fix pkg-release flow for building linuxkit

src/cmd/linuxkit/run_virtualizationframework_darwin_cgo_enabled.go
The `-disk` parameter is not working with `linuxkit run virtualization`. Fixed
Changed conditions about disk check and created image if file not provided
CI
`-disk` usage fixed for `linuxkit run virtualization`
Here is my cat Sanji
=> FIX disk parameter usage

.github/workflows/publish.yaml
Bump action-script to v7
Changed the yaml file
CI
action-script v7
=> github script v7

.github/workflows/ci.yml, .github/workflows/package_release.yml, .github/workflows/release.yml
Bump GitHub actions/setup-go to v5 across the board and use go version 1.22.3 to build
Changed the yaml files
CI
CI latest go
=> bump actions/setup-go to v5 and go-version to 1.22.3

.github/workflows/release.yml, Makefile
Follow-up to previous PR #4056 further clarifies build targets
=> make targets separated by OS

examples/containerd-debug-runtime-config.toml, examples/containerd-debug.yml
Add an example that includes debugging containerd
Added a single file
I ran it. No need beyond that.
debug containerd example
=> include example for debugging containerd

pkg/extend/extend.go, test/cases/040_packages/005_extend/000_ext4/test.yml, test/cases/040_packages/005_extend/001_btrfs/test.yml, test/cases/040_packages/005_extend/002_xfs/test.yml, test/cases/040_packages/005_extend/003_gpt/test.yml
fixes #4098 
Change the pkg/extend so that extension is tried on all found devices.
=> Try resizing all found devices

.github/workflows/ci.yml, src/cmd/linuxkit/gcp.go, src/cmd/linuxkit/run_aws.go, src/cmd/linuxkit/scaleway.go
bump golangci-lint version to avoid false errors
changed the version
CI
bump golangci-lint version to 1.63.4
=> bump golangci-lint-action

src/cmd/linuxkit/moby/build/images.yaml, tools/grub-dev/Dockerfile, tools/grub/Dockerfile, tools/mkimage-iso-efi-initrd/Dockerfile, tools/mkimage-iso-efi/Dockerfile, tools/mkimage-qcow2-efi/Dockerfile, tools/mkimage-raw-efi/Dockerfile
fixes #4075
add the `efi_gop` module to the grub tools package
=> add efi_gop module to grub

src/cmd/linuxkit/pkglib/docker.go
If two lkt processes attempt to create a builder container at the same time, they both do an inspect, it fails, so they both try to create. The first one succeeds, the second one gets a name conflict and fails. Handle that situation.
Add a retry loop. After a create fails, try it again after one second, up to 3 times.
I did it manually by stopping the code right before the "create" clause, started a second process, let it create, and then continued the first. Before this it failed, with this it works. And, of course, CI will catch regressions.
Handle builder container process starting in parallel.
=> pkg build: handle race condition where builder is started at same time

src/cmd/linuxkit/pkglib/git.go
if `pkglib.NewFromConfig` is used in parallel, it calls
```
git -C /some/directory update-index -q --refresh
```
in parallel.
But `git` does not like this and exits with 128.
This can be easily tried with:
```
git -C /some/dir update-index -q --refresh & \
git -C /some/dir update-index -q --refresh
```
call `pkglib.NewFromConfig` in parallel
https://github.com/christoph-zededa/eve/commit/1d09b27c399fcb76517a20f7a02bb631f6681184#diff-0d57db8877b73415b85ec56b72d4b265790a1d353d906b3574f6168227295719R149
run the code with this fix
fix parallel `pkglib.NewFromConfig`
=> git: synchronize `update-index` with a mutex

src/cmd/linuxkit/moby/build/images.yaml, src/cmd/linuxkit/moby/build/output.go, test/cases/000_build/000_formats/014_kernel+erofs/test.sh, tools/mkimage-erofs/Dockerfile, tools/mkimage-erofs/build.yml, tools/mkimage-erofs/make-erofs
- **add erofs as output option**
- **unify nearly identical functions**
Created a new tool for erofs output, and added it to linuxkit build. Also unified some identical functions.
And of course a test.
By changing the code.
CI. I added a new test.
erofs output
=> erofs output
